// GENERATED by tool/gen_c_suite.dart from oniguruma-master/test/test_options.c.
// 1:1 translation of the Oniguruma C test cases. Do not edit.
import 'package:oniguruma_dart/oniguruma_dart.dart';
import 'c_harness.dart';

void main() {
  group('test_options', () {
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase,
    ).x2('a', 'A', 0, 1, 164);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCaseIsAscii,
    ).n('a', 'A', 165);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase,
    ).x2('\xe2\x84\xaa', 'k', 0, 1, 167);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase,
    ).x2('k', '\xe2\x84\xaa', 0, 3, 168);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).n('\xe2\x84\xaa', 'k', 169);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).n('k', '\xe2\x84\xaa', 170);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('a', 'a', 0, 1, 171);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('A', 'A', 0, 1, 172);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('a', 'A', 0, 1, 173);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('A', 'a', 0, 1, 174);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2(
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      'abcdefghijklmnopqrstuvwxyz',
      0,
      26,
      175,
    );
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2(
      'abcdefghijklmnopqrstuvwxyz',
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      0,
      26,
      176,
    );
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2(
      'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
      'ABCabcdefghijklmnopqrstuvwxyz',
      3,
      29,
      177,
    );
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2(
      'abcdefghijklmnopqrstuvwxyz',
      'abcABCDEFGHIJKLMNOPQRSTUVWXYZ',
      3,
      29,
      178,
    );
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x3('#%(a!;)(b&)', '#%A!;B&', 5, 7, 2, 179);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase,
    ).x2('ss', '\xc3\x9f', 0, 2, 181);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase,
    ).x2('\xc3\x9f', 'SS', 0, 2, 182);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).n('ss', '\xc3\x9f', 183);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).n('\xc3\x9f', 'ss', 184);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('ss', 'SS', 0, 2, 185);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.ignoreCase | OnigOption.ignoreCaseIsAscii,
    ).x2('Ss', 'sS', 0, 2, 186);
    CSuite(enc: utf8Encoding, option: OnigOption.notBol).n('^ab', 'ab', 188);
    CSuite(enc: utf8Encoding, option: OnigOption.notBol).n('\\Aab', 'ab', 189);
    CSuite(enc: utf8Encoding, option: OnigOption.notEol).n('ab\$', 'ab', 190);
    CSuite(enc: utf8Encoding, option: OnigOption.notEol).n('ab\\z', 'ab', 191);
    CSuite(enc: utf8Encoding, option: OnigOption.notEol).n('ab\\Z', 'ab', 192);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.notEol,
    ).n('ab\\Z', 'ab\x0a', 193);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.notBeginString,
    ).n('\\Aab', 'ab', 195);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.notEndString,
    ).n('ab\\z', 'ab', 196);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.notEndString,
    ).n('ab\\Z', 'ab', 197);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.notEndString,
    ).n('ab\\Z', 'ab\x0a', 198);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.none,
    ).x2('a|abc', 'abc', 0, 1, 200);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.none,
    ).x2('(a|abc)\\Z', 'abc', 0, 3, 201);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.matchWholeString,
    ).x2('a|abc', 'abc', 0, 3, 202);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.matchWholeString,
    ).x2('a|abc', 'a', 0, 1, 203);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.wordIsAscii,
    ).x2('\\w', '@g', 1, 2, 205);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.wordIsAscii,
    ).n('\\w', '\xe3\x81\x82', 206);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.none,
    ).x2('\\d', '\xef\xbc\x91', 0, 3, 207);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.digitIsAscii,
    ).n('\\d', '\xef\xbc\x91', 208);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.spaceIsAscii,
    ).x2('\\s', ' ', 0, 1, 209);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.none,
    ).x2('\\s', '\xe3\x80\x80', 0, 3, 210);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.spaceIsAscii,
    ).n('\\s', '\xe3\x80\x80', 211);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.posixIsAscii,
    ).x2('\\w\\d\\s', 'c3 ', 0, 3, 213);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.posixIsAscii,
    ).n('\\w|\\d|\\s', '\xe3\x81\x82\xef\xbc\x94\xe3\x80\x80', 214);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.extend,
    ).x2(' abc  \x0a def', 'abcdef', 0, 6, 216);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.findLongest,
    ).x2('\\w+', 'abc defg hij', 4, 8, 217);
    CSuite(
      enc: utf8Encoding,
      option: OnigOption.findNotEmpty,
    ).x2('\\w*', '@@@ abc defg hij', 4, 7, 218);
  });
}
