// GENERATED by tool/gen_c_suite.dart from oniguruma-master/test/testc.c.
// 1:1 translation of the Oniguruma C test cases. Do not edit.
import 'package:oniguruma_dart/oniguruma_dart.dart';
import 'c_harness.dart';

void main() {
  group('testc', () {
    CSuite(enc: eucJpEncoding).x2('', '', 0, 0, 109);
    CSuite(enc: eucJpEncoding).x2('^', '', 0, 0, 110);
    CSuite(enc: eucJpEncoding).x2('\$', '', 0, 0, 111);
    CSuite(enc: eucJpEncoding).x2('\\G', '', 0, 0, 112);
    CSuite(enc: eucJpEncoding).x2('\\A', '', 0, 0, 113);
    CSuite(enc: eucJpEncoding).x2('\\Z', '', 0, 0, 114);
    CSuite(enc: eucJpEncoding).x2('\\z', '', 0, 0, 115);
    CSuite(enc: eucJpEncoding).x2('^\$', '', 0, 0, 116);
    CSuite(enc: eucJpEncoding).x2('\\ca', '\x01', 0, 1, 117);
    CSuite(enc: eucJpEncoding).x2('\\C-b', '\x02', 0, 1, 118);
    CSuite(enc: eucJpEncoding).x2('\\c\\\\', '\x1c', 0, 1, 119);
    CSuite(enc: eucJpEncoding).x2('q[\\c\\\\]', 'q\x1c', 0, 2, 120);
    CSuite(enc: eucJpEncoding).x2('', 'a', 0, 0, 121);
    CSuite(enc: eucJpEncoding).x2('a', 'a', 0, 1, 122);
    CSuite(enc: eucJpEncoding).x2('\\x61', 'a', 0, 1, 123);
    CSuite(enc: eucJpEncoding).x2('aa', 'aa', 0, 2, 124);
    CSuite(enc: eucJpEncoding).x2('aaa', 'aaa', 0, 3, 125);
    CSuite(enc: eucJpEncoding).x2(
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      0,
      35,
      126,
    );
    CSuite(enc: eucJpEncoding).x2('ab', 'ab', 0, 2, 127);
    CSuite(enc: eucJpEncoding).x2('b', 'ab', 1, 2, 128);
    CSuite(enc: eucJpEncoding).x2('bc', 'abc', 1, 3, 129);
    CSuite(enc: eucJpEncoding).x2('(?i:#RET#)', '#INS##RET#', 5, 10, 130);
    CSuite(enc: eucJpEncoding).x2('\\17', '\x0f', 0, 1, 131);
    CSuite(enc: eucJpEncoding).x2('\\x1f', '\x1f', 0, 1, 132);
    CSuite(enc: eucJpEncoding).x2('a(?#....\\\\JJJJ)b', 'ab', 0, 2, 133);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?x)  G (o O(?-x)oO) g L', 'GoOoOgLe', 0, 7, 134);
    CSuite(enc: eucJpEncoding).x2('.', 'a', 0, 1, 135);
    CSuite(enc: eucJpEncoding).n('.', '', 136);
    CSuite(enc: eucJpEncoding).x2('..', 'ab', 0, 2, 137);
    CSuite(enc: eucJpEncoding).x2('\\w', 'e', 0, 1, 138);
    CSuite(enc: eucJpEncoding).n('\\W', 'e', 139);
    CSuite(enc: eucJpEncoding).x2('\\s', ' ', 0, 1, 140);
    CSuite(enc: eucJpEncoding).x2('\\S', 'b', 0, 1, 141);
    CSuite(enc: eucJpEncoding).x2('\\d', '4', 0, 1, 142);
    CSuite(enc: eucJpEncoding).n('\\D', '4', 143);
    CSuite(enc: eucJpEncoding).x2('\\b', 'z ', 0, 0, 144);
    CSuite(enc: eucJpEncoding).x2('\\b', ' z', 1, 1, 145);
    CSuite(enc: eucJpEncoding).x2('\\B', 'zz ', 1, 1, 146);
    CSuite(enc: eucJpEncoding).x2('\\B', 'z ', 2, 2, 147);
    CSuite(enc: eucJpEncoding).x2('\\B', ' z', 0, 0, 148);
    CSuite(enc: eucJpEncoding).x2('[ab]', 'b', 0, 1, 149);
    CSuite(enc: eucJpEncoding).n('[ab]', 'c', 150);
    CSuite(enc: eucJpEncoding).x2('[a-z]', 't', 0, 1, 151);
    CSuite(enc: eucJpEncoding).n('[^a]', 'a', 152);
    CSuite(enc: eucJpEncoding).x2('[^a]', '\x0a', 0, 1, 153);
    CSuite(enc: eucJpEncoding).x2('[]]', ']', 0, 1, 154);
    CSuite(enc: eucJpEncoding).n('[^]]', ']', 155);
    CSuite(enc: eucJpEncoding).x2('[\\^]+', '0^^1', 1, 3, 156);
    CSuite(enc: eucJpEncoding).x2('[b-]', 'b', 0, 1, 157);
    CSuite(enc: eucJpEncoding).x2('[b-]', '-', 0, 1, 158);
    CSuite(enc: eucJpEncoding).x2('[\\w]', 'z', 0, 1, 159);
    CSuite(enc: eucJpEncoding).n('[\\w]', ' ', 160);
    CSuite(enc: eucJpEncoding).x2('[\\W]', 'b\$', 1, 2, 161);
    CSuite(enc: eucJpEncoding).x2('[\\d]', '5', 0, 1, 162);
    CSuite(enc: eucJpEncoding).n('[\\d]', 'e', 163);
    CSuite(enc: eucJpEncoding).x2('[\\D]', 't', 0, 1, 164);
    CSuite(enc: eucJpEncoding).n('[\\D]', '3', 165);
    CSuite(enc: eucJpEncoding).x2('[\\s]', ' ', 0, 1, 166);
    CSuite(enc: eucJpEncoding).n('[\\s]', 'a', 167);
    CSuite(enc: eucJpEncoding).x2('[\\S]', 'b', 0, 1, 168);
    CSuite(enc: eucJpEncoding).n('[\\S]', ' ', 169);
    CSuite(enc: eucJpEncoding).x2('[\\w\\d]', '2', 0, 1, 170);
    CSuite(enc: eucJpEncoding).n('[\\w\\d]', ' ', 171);
    CSuite(enc: eucJpEncoding).x2('[[:upper:]]', 'B', 0, 1, 172);
    CSuite(enc: eucJpEncoding).x2('[*[:xdigit:]+]', '+', 0, 1, 173);
    CSuite(enc: eucJpEncoding).x2('[*[:xdigit:]+]', 'GHIKK-9+*', 6, 7, 174);
    CSuite(enc: eucJpEncoding).x2('[*[:xdigit:]+]', '-@^+', 3, 4, 175);
    CSuite(enc: eucJpEncoding).n('[[:upper]]', 'A', 176);
    CSuite(enc: eucJpEncoding).x2('[[:upper]]', ':', 0, 1, 177);
    CSuite(enc: eucJpEncoding).x2('[\\044-\\047]', '&', 0, 1, 178);
    CSuite(enc: eucJpEncoding).x2('[\\x5a-\\x5c]', '[', 0, 1, 179);
    CSuite(enc: eucJpEncoding).x2('[\\x6A-\\x6D]', 'l', 0, 1, 180);
    CSuite(enc: eucJpEncoding).n('[\\x6A-\\x6D]', 'n', 181);
    CSuite(enc: eucJpEncoding).n(
      '^[0-9A-F]+ 0+ UNDEF ',
      '75F 00000000 SECT14A notype ()    External    | _rb_apply',
      182,
    );
    CSuite(enc: eucJpEncoding).x2('[\\[]', '[', 0, 1, 183);
    CSuite(enc: eucJpEncoding).x2('[\\]]', ']', 0, 1, 184);
    CSuite(enc: eucJpEncoding).x2('[&]', '&', 0, 1, 185);
    CSuite(enc: eucJpEncoding).x2('[[ab]]', 'b', 0, 1, 186);
    CSuite(enc: eucJpEncoding).x2('[[ab]c]', 'c', 0, 1, 187);
    CSuite(enc: eucJpEncoding).n('[[^a]]', 'a', 188);
    CSuite(enc: eucJpEncoding).n('[^[a]]', 'a', 189);
    CSuite(enc: eucJpEncoding).x2('[[ab]&&bc]', 'b', 0, 1, 190);
    CSuite(enc: eucJpEncoding).n('[[ab]&&bc]', 'a', 191);
    CSuite(enc: eucJpEncoding).n('[[ab]&&bc]', 'c', 192);
    CSuite(enc: eucJpEncoding).x2('[a-z&&b-y&&c-x]', 'w', 0, 1, 193);
    CSuite(enc: eucJpEncoding).n('[^a-z&&b-y&&c-x]', 'w', 194);
    CSuite(enc: eucJpEncoding).x2('[[^a&&a]&&a-z]', 'b', 0, 1, 195);
    CSuite(enc: eucJpEncoding).n('[[^a&&a]&&a-z]', 'a', 196);
    CSuite(enc: eucJpEncoding).x2('[[^a-z&&bcdef]&&[^c-g]]', 'h', 0, 1, 197);
    CSuite(enc: eucJpEncoding).n('[[^a-z&&bcdef]&&[^c-g]]', 'c', 198);
    CSuite(enc: eucJpEncoding).x2('[^[^abc]&&[^cde]]', 'c', 0, 1, 199);
    CSuite(enc: eucJpEncoding).x2('[^[^abc]&&[^cde]]', 'e', 0, 1, 200);
    CSuite(enc: eucJpEncoding).n('[^[^abc]&&[^cde]]', 'f', 201);
    CSuite(enc: eucJpEncoding).x2('[a-&&-a]', '-', 0, 1, 202);
    CSuite(enc: eucJpEncoding).n('[a\\-&&\\-a]', '&', 203);
    CSuite(enc: eucJpEncoding).n('\\wabc', ' abc', 204);
    CSuite(enc: eucJpEncoding).x2('a\\Wbc', 'a bc', 0, 4, 205);
    CSuite(enc: eucJpEncoding).x2('a.b.c', 'aabbc', 0, 5, 206);
    CSuite(enc: eucJpEncoding).x2('.\\wb\\W..c', 'abb bcc', 0, 7, 207);
    CSuite(enc: eucJpEncoding).x2('\\s\\wzzz', ' zzzz', 0, 5, 208);
    CSuite(enc: eucJpEncoding).x2('aa.b', 'aabb', 0, 4, 209);
    CSuite(enc: eucJpEncoding).n('.a', 'ab', 210);
    CSuite(enc: eucJpEncoding).x2('.a', 'aa', 0, 2, 211);
    CSuite(enc: eucJpEncoding).x2('^a', 'a', 0, 1, 212);
    CSuite(enc: eucJpEncoding).x2('^a\$', 'a', 0, 1, 213);
    CSuite(enc: eucJpEncoding).x2('^\\w\$', 'a', 0, 1, 214);
    CSuite(enc: eucJpEncoding).n('^\\w\$', ' ', 215);
    CSuite(enc: eucJpEncoding).x2('^\\wab\$', 'zab', 0, 3, 216);
    CSuite(enc: eucJpEncoding).x2('^\\wabcdef\$', 'zabcdef', 0, 7, 217);
    CSuite(enc: eucJpEncoding).x2('^\\w...def\$', 'zabcdef', 0, 7, 218);
    CSuite(enc: eucJpEncoding).x2('\\w\\w\\s\\Waaa\\d', 'aa  aaa4', 0, 8, 219);
    CSuite(enc: eucJpEncoding).x2('\\A\\Z', '', 0, 0, 220);
    CSuite(enc: eucJpEncoding).x2('\\Axyz', 'xyz', 0, 3, 221);
    CSuite(enc: eucJpEncoding).x2('xyz\\Z', 'xyz', 0, 3, 222);
    CSuite(enc: eucJpEncoding).x2('xyz\\z', 'xyz', 0, 3, 223);
    CSuite(enc: eucJpEncoding).x2('a\\Z', 'a', 0, 1, 224);
    CSuite(enc: eucJpEncoding).x2('\\Gaz', 'az', 0, 2, 225);
    CSuite(enc: eucJpEncoding).n('\\Gz', 'bza', 226);
    CSuite(enc: eucJpEncoding).n('az\\G', 'az', 227);
    CSuite(enc: eucJpEncoding).n('az\\A', 'az', 228);
    CSuite(enc: eucJpEncoding).n('a\\Az', 'az', 229);
    CSuite(enc: eucJpEncoding).x2('\\^\\\$', '^\$', 0, 2, 230);
    CSuite(enc: eucJpEncoding).x2('^x?y', 'xy', 0, 2, 231);
    CSuite(enc: eucJpEncoding).x2('^(x?y)', 'xy', 0, 2, 232);
    CSuite(enc: eucJpEncoding).x2('\\w', '_', 0, 1, 233);
    CSuite(enc: eucJpEncoding).n('\\W', '_', 234);
    CSuite(enc: eucJpEncoding).x2('(?=z)z', 'z', 0, 1, 235);
    CSuite(enc: eucJpEncoding).n('(?=z).', 'a', 236);
    CSuite(enc: eucJpEncoding).x2('(?!z)a', 'a', 0, 1, 237);
    CSuite(enc: eucJpEncoding).n('(?!z)a', 'z', 238);
    CSuite(enc: eucJpEncoding).x2('(?i:a)', 'a', 0, 1, 239);
    CSuite(enc: eucJpEncoding).x2('(?i:a)', 'A', 0, 1, 240);
    CSuite(enc: eucJpEncoding).x2('(?i:A)', 'a', 0, 1, 241);
    CSuite(enc: eucJpEncoding).n('(?i:A)', 'b', 242);
    CSuite(enc: eucJpEncoding).x2('(?i:[A-Z])', 'a', 0, 1, 243);
    CSuite(enc: eucJpEncoding).x2('(?i:[f-m])', 'H', 0, 1, 244);
    CSuite(enc: eucJpEncoding).x2('(?i:[f-m])', 'h', 0, 1, 245);
    CSuite(enc: eucJpEncoding).n('(?i:[f-m])', 'e', 246);
    CSuite(enc: eucJpEncoding).x2('(?i:[A-c])', 'D', 0, 1, 247);
    CSuite(enc: eucJpEncoding).n('(?i:[^a-z])', 'A', 248);
    CSuite(enc: eucJpEncoding).n('(?i:[^a-z])', 'a', 249);
    CSuite(enc: eucJpEncoding).x2('(?i:[!-k])', 'Z', 0, 1, 250);
    CSuite(enc: eucJpEncoding).x2('(?i:[!-k])', '7', 0, 1, 251);
    CSuite(enc: eucJpEncoding).x2('(?i:[T-}])', 'b', 0, 1, 252);
    CSuite(enc: eucJpEncoding).x2('(?i:[T-}])', '{', 0, 1, 253);
    CSuite(enc: eucJpEncoding).x2('(?i:\\?a)', '?A', 0, 2, 254);
    CSuite(enc: eucJpEncoding).x2('(?i:\\*A)', '*a', 0, 2, 255);
    CSuite(enc: eucJpEncoding).n('.', '\x0a', 256);
    CSuite(enc: eucJpEncoding).x2('(?m:.)', '\x0a', 0, 1, 257);
    CSuite(enc: eucJpEncoding).x2('(?m:a.)', 'a\x0a', 0, 2, 258);
    CSuite(enc: eucJpEncoding).x2('(?m:.b)', 'a\x0ab', 1, 3, 259);
    CSuite(enc: eucJpEncoding).x2('.*abc', 'dddabdd\x0addabc', 8, 13, 260);
    CSuite(enc: eucJpEncoding).x2('(?m:.*abc)', 'dddabddabc', 0, 10, 261);
    CSuite(enc: eucJpEncoding).n('(?i)(?-i)a', 'A', 262);
    CSuite(enc: eucJpEncoding).n('(?i)(?-i:a)', 'A', 263);
    CSuite(enc: eucJpEncoding).x2('a?', '', 0, 0, 264);
    CSuite(enc: eucJpEncoding).x2('a?', 'b', 0, 0, 265);
    CSuite(enc: eucJpEncoding).x2('a?', 'a', 0, 1, 266);
    CSuite(enc: eucJpEncoding).x2('a*', '', 0, 0, 267);
    CSuite(enc: eucJpEncoding).x2('a*', 'a', 0, 1, 268);
    CSuite(enc: eucJpEncoding).x2('a*', 'aaa', 0, 3, 269);
    CSuite(enc: eucJpEncoding).x2('a*', 'baaaa', 0, 0, 270);
    CSuite(enc: eucJpEncoding).n('a+', '', 271);
    CSuite(enc: eucJpEncoding).x2('a+', 'a', 0, 1, 272);
    CSuite(enc: eucJpEncoding).x2('a+', 'aaaa', 0, 4, 273);
    CSuite(enc: eucJpEncoding).x2('a+', 'aabbb', 0, 2, 274);
    CSuite(enc: eucJpEncoding).x2('a+', 'baaaa', 1, 5, 275);
    CSuite(enc: eucJpEncoding).x2('.?', '', 0, 0, 276);
    CSuite(enc: eucJpEncoding).x2('.?', 'f', 0, 1, 277);
    CSuite(enc: eucJpEncoding).x2('.?', '\x0a', 0, 0, 278);
    CSuite(enc: eucJpEncoding).x2('.*', '', 0, 0, 279);
    CSuite(enc: eucJpEncoding).x2('.*', 'abcde', 0, 5, 280);
    CSuite(enc: eucJpEncoding).x2('.+', 'z', 0, 1, 281);
    CSuite(enc: eucJpEncoding).x2('.+', 'zdswer\x0a', 0, 6, 282);
    CSuite(enc: eucJpEncoding).x2('(.*)a\\1f', 'babfbac', 0, 4, 283);
    CSuite(enc: eucJpEncoding).x2('(.*)a\\1f', 'bacbabf', 3, 7, 284);
    CSuite(enc: eucJpEncoding).x2('((.*)a\\2f)', 'bacbabf', 3, 7, 285);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(.*)a\\1f', 'baczzzzzz\x0abazz\x0azzzzbabf', 19, 23, 286);
    CSuite(enc: eucJpEncoding).x2('a|b', 'a', 0, 1, 287);
    CSuite(enc: eucJpEncoding).x2('a|b', 'b', 0, 1, 288);
    CSuite(enc: eucJpEncoding).x2('|a', 'a', 0, 0, 289);
    CSuite(enc: eucJpEncoding).x2('(|a)', 'a', 0, 0, 290);
    CSuite(enc: eucJpEncoding).x2('ab|bc', 'ab', 0, 2, 291);
    CSuite(enc: eucJpEncoding).x2('ab|bc', 'bc', 0, 2, 292);
    CSuite(enc: eucJpEncoding).x2('z(?:ab|bc)', 'zbc', 0, 3, 293);
    CSuite(enc: eucJpEncoding).x2('a(?:ab|bc)c', 'aabc', 0, 4, 294);
    CSuite(enc: eucJpEncoding).x2('ab|(?:ac|az)', 'az', 0, 2, 295);
    CSuite(enc: eucJpEncoding).x2('a|b|c', 'dc', 1, 2, 296);
    CSuite(
      enc: eucJpEncoding,
    ).x2('a|b|cd|efg|h|ijk|lmn|o|pq|rstuvwx|yz', 'pqr', 0, 2, 297);
    CSuite(
      enc: eucJpEncoding,
    ).n('a|b|cd|efg|h|ijk|lmn|o|pq|rstuvwx|yz', 'mn', 298);
    CSuite(enc: eucJpEncoding).x2('a|^z', 'ba', 1, 2, 299);
    CSuite(enc: eucJpEncoding).x2('a|^z', 'za', 0, 1, 300);
    CSuite(enc: eucJpEncoding).x2('a|\\Gz', 'bza', 2, 3, 301);
    CSuite(enc: eucJpEncoding).x2('a|\\Gz', 'za', 0, 1, 302);
    CSuite(enc: eucJpEncoding).x2('a|\\Az', 'bza', 2, 3, 303);
    CSuite(enc: eucJpEncoding).x2('a|\\Az', 'za', 0, 1, 304);
    CSuite(enc: eucJpEncoding).x2('a|b\\Z', 'ba', 1, 2, 305);
    CSuite(enc: eucJpEncoding).x2('a|b\\Z', 'b', 0, 1, 306);
    CSuite(enc: eucJpEncoding).x2('a|b\\z', 'ba', 1, 2, 307);
    CSuite(enc: eucJpEncoding).x2('a|b\\z', 'b', 0, 1, 308);
    CSuite(enc: eucJpEncoding).x2('\\w|\\s', ' ', 0, 1, 309);
    CSuite(enc: eucJpEncoding).n('\\w|\\w', ' ', 310);
    CSuite(enc: eucJpEncoding).x2('\\w|%', '%', 0, 1, 311);
    CSuite(enc: eucJpEncoding).x2('\\w|[&\$]', '&', 0, 1, 312);
    CSuite(enc: eucJpEncoding).x2('[b-d]|[^e-z]', 'a', 0, 1, 313);
    CSuite(enc: eucJpEncoding).x2('(?:a|[c-f])|bz', 'dz', 0, 1, 314);
    CSuite(enc: eucJpEncoding).x2('(?:a|[c-f])|bz', 'bz', 0, 2, 315);
    CSuite(enc: eucJpEncoding).x2('abc|(?=zz)..f', 'zzf', 0, 3, 316);
    CSuite(enc: eucJpEncoding).x2('abc|(?!zz)..f', 'abf', 0, 3, 317);
    CSuite(enc: eucJpEncoding).x2('(?=za)..a|(?=zz)..a', 'zza', 0, 3, 318);
    CSuite(enc: eucJpEncoding).n('(?>a|abd)c', 'abdc', 319);
    CSuite(enc: eucJpEncoding).x2('(?>abd|a)c', 'abdc', 0, 4, 320);
    CSuite(enc: eucJpEncoding).x2('a?|b', 'a', 0, 1, 321);
    CSuite(enc: eucJpEncoding).x2('a?|b', 'b', 0, 0, 322);
    CSuite(enc: eucJpEncoding).x2('a?|b', '', 0, 0, 323);
    CSuite(enc: eucJpEncoding).x2('a*|b', 'aa', 0, 2, 324);
    CSuite(enc: eucJpEncoding).x2('a*|b*', 'ba', 0, 0, 325);
    CSuite(enc: eucJpEncoding).x2('a*|b*', 'ab', 0, 1, 326);
    CSuite(enc: eucJpEncoding).x2('a+|b*', '', 0, 0, 327);
    CSuite(enc: eucJpEncoding).x2('a+|b*', 'bbb', 0, 3, 328);
    CSuite(enc: eucJpEncoding).x2('a+|b*', 'abbb', 0, 1, 329);
    CSuite(enc: eucJpEncoding).n('a+|b+', '', 330);
    CSuite(enc: eucJpEncoding).x2('(a|b)?', 'b', 0, 1, 331);
    CSuite(enc: eucJpEncoding).x2('(a|b)*', 'ba', 0, 2, 332);
    CSuite(enc: eucJpEncoding).x2('(a|b)+', 'bab', 0, 3, 333);
    CSuite(enc: eucJpEncoding).x2('(ab|ca)+', 'caabbc', 0, 4, 334);
    CSuite(enc: eucJpEncoding).x2('(ab|ca)+', 'aabca', 1, 5, 335);
    CSuite(enc: eucJpEncoding).x2('(ab|ca)+', 'abzca', 0, 2, 336);
    CSuite(enc: eucJpEncoding).x2('(a|bab)+', 'ababa', 0, 5, 337);
    CSuite(enc: eucJpEncoding).x2('(a|bab)+', 'ba', 1, 2, 338);
    CSuite(enc: eucJpEncoding).x2('(a|bab)+', 'baaaba', 1, 4, 339);
    CSuite(enc: eucJpEncoding).x2('(?:a|b)(?:a|b)', 'ab', 0, 2, 340);
    CSuite(enc: eucJpEncoding).x2('(?:a*|b*)(?:a*|b*)', 'aaabbb', 0, 3, 341);
    CSuite(enc: eucJpEncoding).x2('(?:a*|b*)(?:a+|b+)', 'aaabbb', 0, 6, 342);
    CSuite(enc: eucJpEncoding).x2('(?:a+|b+){2}', 'aaabbb', 0, 6, 343);
    CSuite(enc: eucJpEncoding).x2('h{0,}', 'hhhh', 0, 4, 344);
    CSuite(enc: eucJpEncoding).x2('(?:a+|b+){1,2}', 'aaabbb', 0, 6, 345);
    CSuite(enc: eucJpEncoding).n('ax{2}*a', '0axxxa1', 346);
    CSuite(enc: eucJpEncoding).n('a.{0,2}a', '0aXXXa0', 347);
    CSuite(enc: eucJpEncoding).n('a.{0,2}?a', '0aXXXa0', 348);
    CSuite(enc: eucJpEncoding).n('a.{0,2}?a', '0aXXXXa0', 349);
    CSuite(enc: eucJpEncoding).x2('^a{2,}?a\$', 'aaa', 0, 3, 350);
    CSuite(enc: eucJpEncoding).x2('^[a-z]{2,}?\$', 'aaa', 0, 3, 351);
    CSuite(enc: eucJpEncoding).x2('(?:a+|\\Ab*)cc', 'cc', 0, 2, 352);
    CSuite(enc: eucJpEncoding).n('(?:a+|\\Ab*)cc', 'abcc', 353);
    CSuite(enc: eucJpEncoding).x2('(?:^a+|b+)*c', 'aabbbabc', 6, 8, 354);
    CSuite(enc: eucJpEncoding).x2('(?:^a+|b+)*c', 'aabbbbc', 0, 7, 355);
    CSuite(enc: eucJpEncoding).x2('a|(?i)c', 'C', 0, 1, 356);
    CSuite(enc: eucJpEncoding).x2('(?i)c|a', 'C', 0, 1, 357);
    CSuite(enc: eucJpEncoding).x2('(?i)c|a', 'A', 0, 1, 358);
    CSuite(enc: eucJpEncoding).x2('(?i:c)|a', 'C', 0, 1, 359);
    CSuite(enc: eucJpEncoding).n('(?i:c)|a', 'A', 360);
    CSuite(enc: eucJpEncoding).x2('[abc]?', 'abc', 0, 1, 361);
    CSuite(enc: eucJpEncoding).x2('[abc]*', 'abc', 0, 3, 362);
    CSuite(enc: eucJpEncoding).x2('[^abc]*', 'abc', 0, 0, 363);
    CSuite(enc: eucJpEncoding).n('[^abc]+', 'abc', 364);
    CSuite(enc: eucJpEncoding).x2('a??', 'aaa', 0, 0, 365);
    CSuite(enc: eucJpEncoding).x2('ba??b', 'bab', 0, 3, 366);
    CSuite(enc: eucJpEncoding).x2('a*?', 'aaa', 0, 0, 367);
    CSuite(enc: eucJpEncoding).x2('ba*?', 'baa', 0, 1, 368);
    CSuite(enc: eucJpEncoding).x2('ba*?b', 'baab', 0, 4, 369);
    CSuite(enc: eucJpEncoding).x2('a+?', 'aaa', 0, 1, 370);
    CSuite(enc: eucJpEncoding).x2('ba+?', 'baa', 0, 2, 371);
    CSuite(enc: eucJpEncoding).x2('ba+?b', 'baab', 0, 4, 372);
    CSuite(enc: eucJpEncoding).x2('(?:a?)??', 'a', 0, 0, 373);
    CSuite(enc: eucJpEncoding).x2('(?:a??)?', 'a', 0, 0, 374);
    CSuite(enc: eucJpEncoding).x2('(?:a?)+?', 'aaa', 0, 1, 375);
    CSuite(enc: eucJpEncoding).x2('(?:a+)??', 'aaa', 0, 0, 376);
    CSuite(enc: eucJpEncoding).x2('(?:a+)??b', 'aaab', 0, 4, 377);
    CSuite(enc: eucJpEncoding).x2('(?:ab)?{2}', '', 0, 0, 378);
    CSuite(enc: eucJpEncoding).x2('(?:ab)?{2}', 'ababa', 0, 4, 379);
    CSuite(enc: eucJpEncoding).x2('(?:ab)*{0}', 'ababa', 0, 0, 380);
    CSuite(enc: eucJpEncoding).x2('(?:ab){3,}', 'abababab', 0, 8, 381);
    CSuite(enc: eucJpEncoding).n('(?:ab){3,}', 'abab', 382);
    CSuite(enc: eucJpEncoding).x2('(?:ab){2,4}', 'ababab', 0, 6, 383);
    CSuite(enc: eucJpEncoding).x2('(?:ab){2,4}', 'ababababab', 0, 8, 384);
    CSuite(enc: eucJpEncoding).x2('(?:ab){2,4}?', 'ababababab', 0, 4, 385);
    CSuite(enc: eucJpEncoding).x2('(?:ab){,}', 'ab{,}', 0, 5, 386);
    CSuite(enc: eucJpEncoding).x2('(?:abc)+?{2}', 'abcabcabc', 0, 6, 387);
    CSuite(enc: eucJpEncoding).x2('(?:X*)(?i:xa)', 'XXXa', 0, 4, 388);
    CSuite(enc: eucJpEncoding).x2('(d+)([^abc]z)', 'dddz', 0, 4, 389);
    CSuite(enc: eucJpEncoding).x2('([^abc]*)([^abc]z)', 'dddz', 0, 4, 390);
    CSuite(enc: eucJpEncoding).x2('(\\w+)(\\wz)', 'dddz', 0, 4, 391);
    CSuite(enc: eucJpEncoding).x3('(a)', 'a', 0, 1, 1, 392);
    CSuite(enc: eucJpEncoding).x3('(ab)', 'ab', 0, 2, 1, 393);
    CSuite(enc: eucJpEncoding).x2('((ab))', 'ab', 0, 2, 394);
    CSuite(enc: eucJpEncoding).x3('((ab))', 'ab', 0, 2, 1, 395);
    CSuite(enc: eucJpEncoding).x3('((ab))', 'ab', 0, 2, 2, 396);
    CSuite(
      enc: eucJpEncoding,
    ).x3('((((((((((((((((((((ab))))))))))))))))))))', 'ab', 0, 2, 20, 397);
    CSuite(enc: eucJpEncoding).x3('(ab)(cd)', 'abcd', 0, 2, 1, 398);
    CSuite(enc: eucJpEncoding).x3('(ab)(cd)', 'abcd', 2, 4, 2, 399);
    CSuite(
      enc: eucJpEncoding,
    ).x3('()(a)bc(def)ghijk', 'abcdefghijk', 3, 6, 3, 400);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(()(a)bc(def)ghijk)', 'abcdefghijk', 3, 6, 4, 401);
    CSuite(enc: eucJpEncoding).x2('(^a)', 'a', 0, 1, 402);
    CSuite(enc: eucJpEncoding).x3('(a)|(a)', 'ba', 1, 2, 1, 403);
    CSuite(enc: eucJpEncoding).x3('(^a)|(a)', 'ba', 1, 2, 2, 404);
    CSuite(enc: eucJpEncoding).x3('(a?)', 'aaa', 0, 1, 1, 405);
    CSuite(enc: eucJpEncoding).x3('(a*)', 'aaa', 0, 3, 1, 406);
    CSuite(enc: eucJpEncoding).x3('(a*)', '', 0, 0, 1, 407);
    CSuite(enc: eucJpEncoding).x3('(a+)', 'aaaaaaa', 0, 7, 1, 408);
    CSuite(enc: eucJpEncoding).x3('(a+|b*)', 'bbbaa', 0, 3, 1, 409);
    CSuite(enc: eucJpEncoding).x3('(a+|b?)', 'bbbaa', 0, 1, 1, 410);
    CSuite(enc: eucJpEncoding).x3('(abc)?', 'abc', 0, 3, 1, 411);
    CSuite(enc: eucJpEncoding).x3('(abc)*', 'abc', 0, 3, 1, 412);
    CSuite(enc: eucJpEncoding).x3('(abc)+', 'abc', 0, 3, 1, 413);
    CSuite(enc: eucJpEncoding).x3('(xyz|abc)+', 'abc', 0, 3, 1, 414);
    CSuite(enc: eucJpEncoding).x3('([xyz][abc]|abc)+', 'abc', 0, 3, 1, 415);
    CSuite(enc: eucJpEncoding).x3('((?i:abc))', 'AbC', 0, 3, 1, 416);
    CSuite(enc: eucJpEncoding).x2('(abc)(?i:\\1)', 'abcABC', 0, 6, 417);
    CSuite(enc: eucJpEncoding).x3('((?m:a.c))', 'a\x0ac', 0, 3, 1, 418);
    CSuite(enc: eucJpEncoding).x3('((?=az)a)', 'azb', 0, 1, 1, 419);
    CSuite(enc: eucJpEncoding).x3('abc|(.abd)', 'zabd', 0, 4, 1, 420);
    CSuite(enc: eucJpEncoding).x2('(?:abc)|(ABC)', 'abc', 0, 3, 421);
    CSuite(enc: eucJpEncoding).x3('(?i:(abc))|(zzz)', 'ABC', 0, 3, 1, 422);
    CSuite(enc: eucJpEncoding).x3('a*(.)', 'aaaaz', 4, 5, 1, 423);
    CSuite(enc: eucJpEncoding).x3('a*?(.)', 'aaaaz', 0, 1, 1, 424);
    CSuite(enc: eucJpEncoding).x3('a*?(c)', 'aaaac', 4, 5, 1, 425);
    CSuite(enc: eucJpEncoding).x3('[bcd]a*(.)', 'caaaaz', 5, 6, 1, 426);
    CSuite(enc: eucJpEncoding).x3('(\\Abb)cc', 'bbcc', 0, 2, 1, 427);
    CSuite(enc: eucJpEncoding).n('(\\Abb)cc', 'zbbcc', 428);
    CSuite(enc: eucJpEncoding).x3('(^bb)cc', 'bbcc', 0, 2, 1, 429);
    CSuite(enc: eucJpEncoding).n('(^bb)cc', 'zbbcc', 430);
    CSuite(enc: eucJpEncoding).x3('cc(bb\$)', 'ccbb', 2, 4, 1, 431);
    CSuite(enc: eucJpEncoding).n('cc(bb\$)', 'ccbbb', 432);
    CSuite(enc: eucJpEncoding).n('(\\1)', '', 433);
    CSuite(enc: eucJpEncoding).n('\\1(a)', 'aa', 434);
    CSuite(enc: eucJpEncoding).n('(a(b)\\1)\\2+', 'ababb', 435);
    CSuite(enc: eucJpEncoding).n('(?:(?:\\1|z)(a))+\$', 'zaa', 436);
    CSuite(enc: eucJpEncoding).x2('(?:(?:\\1|z)(a))+\$', 'zaaa', 0, 4, 437);
    CSuite(enc: eucJpEncoding).x2('(a)(?=\\1)', 'aa', 0, 1, 438);
    CSuite(enc: eucJpEncoding).n('(a)\$|\\1', 'az', 439);
    CSuite(enc: eucJpEncoding).x2('(a)\\1', 'aa', 0, 2, 440);
    CSuite(enc: eucJpEncoding).n('(a)\\1', 'ab', 441);
    CSuite(enc: eucJpEncoding).x2('(a?)\\1', 'aa', 0, 2, 442);
    CSuite(enc: eucJpEncoding).x2('(a??)\\1', 'aa', 0, 0, 443);
    CSuite(enc: eucJpEncoding).x2('(a*)\\1', 'aaaaa', 0, 4, 444);
    CSuite(enc: eucJpEncoding).x3('(a*)\\1', 'aaaaa', 0, 2, 1, 445);
    CSuite(enc: eucJpEncoding).x2('a(b*)\\1', 'abbbb', 0, 5, 446);
    CSuite(enc: eucJpEncoding).x2('a(b*)\\1', 'ab', 0, 1, 447);
    CSuite(enc: eucJpEncoding).x2('(a*)(b*)\\1\\2', 'aaabbaaabb', 0, 10, 448);
    CSuite(enc: eucJpEncoding).x2('(a*)(b*)\\2', 'aaabbbb', 0, 7, 449);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(((((((a*)b))))))c\\7', 'aaabcaaa', 0, 8, 450);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(((((((a*)b))))))c\\7', 'aaabcaaa', 0, 3, 7, 451);
    CSuite(enc: eucJpEncoding).x2('(a)(b)(c)\\2\\1\\3', 'abcbac', 0, 6, 452);
    CSuite(enc: eucJpEncoding).x2('([a-d])\\1', 'cc', 0, 2, 453);
    CSuite(enc: eucJpEncoding).x2('(\\w\\d\\s)\\1', 'f5 f5 ', 0, 6, 454);
    CSuite(enc: eucJpEncoding).n('(\\w\\d\\s)\\1', 'f5 f5', 455);
    CSuite(enc: eucJpEncoding).x2('(who|[a-c]{3})\\1', 'whowho', 0, 6, 456);
    CSuite(
      enc: eucJpEncoding,
    ).x2('...(who|[a-c]{3})\\1', 'abcwhowho', 0, 9, 457);
    CSuite(enc: eucJpEncoding).x2('(who|[a-c]{3})\\1', 'cbccbc', 0, 6, 458);
    CSuite(enc: eucJpEncoding).x2('(^a)\\1', 'aa', 0, 2, 459);
    CSuite(enc: eucJpEncoding).n('(^a)\\1', 'baa', 460);
    CSuite(enc: eucJpEncoding).n('(a\$)\\1', 'aa', 461);
    CSuite(enc: eucJpEncoding).n('(ab\\Z)\\1', 'ab', 462);
    CSuite(enc: eucJpEncoding).x2('(a*\\Z)\\1', 'a', 1, 1, 463);
    CSuite(enc: eucJpEncoding).x2('.(a*\\Z)\\1', 'ba', 1, 2, 464);
    CSuite(enc: eucJpEncoding).x3('(.(abc)\\2)', 'zabcabc', 0, 7, 1, 465);
    CSuite(enc: eucJpEncoding).x3('(.(..\\d.)\\2)', 'z12341234', 0, 9, 1, 466);
    CSuite(enc: eucJpEncoding).x2('((?i:az))\\1', 'AzAz', 0, 4, 467);
    CSuite(enc: eucJpEncoding).n('((?i:az))\\1', 'Azaz', 468);
    CSuite(enc: eucJpEncoding).x2('(?<=a)b', 'ab', 1, 2, 469);
    CSuite(enc: eucJpEncoding).n('(?<=a)b', 'bb', 470);
    CSuite(enc: eucJpEncoding).x2('(?<=a|b)b', 'bb', 1, 2, 471);
    CSuite(enc: eucJpEncoding).x2('(?<=a|bc)b', 'bcb', 2, 3, 472);
    CSuite(enc: eucJpEncoding).x2('(?<=a|bc)b', 'ab', 1, 2, 473);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<=a|bc||defghij|klmnopq|r)z', 'rz', 1, 2, 474);
    CSuite(enc: eucJpEncoding).x2('(a)\\g<1>', 'aa', 0, 2, 475);
    CSuite(enc: eucJpEncoding).x2('(?<!a)b', 'cb', 1, 2, 476);
    CSuite(enc: eucJpEncoding).n('(?<!a)b', 'ab', 477);
    CSuite(enc: eucJpEncoding).x2('(?<!a|bc)b', 'bbb', 0, 1, 478);
    CSuite(enc: eucJpEncoding).n('(?<!a|bc)z', 'bcz', 479);
    CSuite(enc: eucJpEncoding).x2('(?<name1>a)', 'a', 0, 1, 480);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<name_2>ab)\\g<name_2>', 'abab', 0, 4, 481);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<name_3>.zv.)\\k<name_3>', 'azvbazvb', 0, 8, 482);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<=\\g<ab>)|-\\zEND (?<ab>XyZ)', 'XyZ', 3, 3, 483);
    CSuite(enc: eucJpEncoding).x2('(?<n>|a\\g<n>)+', '', 0, 0, 484);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<n>|\\(\\g<n>\\))+\$', '()(())', 0, 6, 485);
    CSuite(enc: eucJpEncoding).x3('\\g<n>(?<n>.){0}', 'X', 0, 1, 1, 486);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\g<n>(abc|df(?<n>.YZ){2,8}){0}', 'XYZ', 0, 3, 487);
    CSuite(enc: eucJpEncoding).x2('\\A(?<n>(a\\g<n>)|)\\z', 'aaaa', 0, 4, 488);
    CSuite(enc: eucJpEncoding).x2(
      '(?<n>|\\g<m>\\g<n>)\\z|\\zEND (?<m>a|(b)\\g<m>)',
      'bbbbabba',
      0,
      8,
      489,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?<name1240>\\w+\\sx)a+\\k<name1240>',
      '  fg xaaaaaaaafg x',
      2,
      18,
      490,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x3('(z)()()(?<_9>a)\\g<_9>', 'zaa', 2, 3, 1, 491);
    CSuite(enc: eucJpEncoding).x2('(.)(((?<_>a)))\\k<_>', 'zaa', 0, 3, 492);
    CSuite(enc: eucJpEncoding).x2(
      '((?<name1>\\d)|(?<name2>\\w))(\\k<name1>|\\k<name2>)',
      'ff',
      0,
      2,
      493,
    );
    CSuite(enc: eucJpEncoding).x2('(?:(?<x>)|(?<x>efg))\\k<x>', '', 0, 0, 494);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:(?<x>abc)|(?<x>efg))\\k<x>', 'abcefgefg', 3, 9, 495);
    CSuite(
      enc: eucJpEncoding,
    ).n('(?:(?<x>abc)|(?<x>efg))\\k<x>', 'abcefg', 496);
    CSuite(enc: eucJpEncoding).x2(
      '(?:(?<n1>.)|(?<n1>..)|(?<n1>...)|(?<n1>....)|(?<n1>.....)|(?<n1>......)|(?<n1>.......)|(?<n1>........)|(?<n1>.........)|(?<n1>..........)|(?<n1>...........)|(?<n1>............)|(?<n1>.............)|(?<n1>..............))\\k<n1>\$',
      'a-pyumpyum',
      2,
      10,
      497,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(?:(?<n1>.)|(?<n1>..)|(?<n1>...)|(?<n1>....)|(?<n1>.....)|(?<n1>......)|(?<n1>.......)|(?<n1>........)|(?<n1>.........)|(?<n1>..........)|(?<n1>...........)|(?<n1>............)|(?<n1>.............)|(?<n1>..............))\\k<n1>\$',
      'xxxxabcdefghijklmnabcdefghijklmn',
      4,
      18,
      14,
      498,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(?<name1>)(?<name2>)(?<name3>)(?<name4>)(?<name5>)(?<name6>)(?<name7>)(?<name8>)(?<name9>)(?<name10>)(?<name11>)(?<name12>)(?<name13>)(?<name14>)(?<name15>)(?<name16>aaa)(?<name17>)\$',
      'aaa',
      0,
      3,
      16,
      499,
    );
    CSuite(enc: eucJpEncoding).x2('(?<foo>a|\\(\\g<foo>\\))', 'a', 0, 1, 500);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<foo>a|\\(\\g<foo>\\))', '((((((a))))))', 0, 13, 501);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(?<foo>a|\\(\\g<foo>\\))', '((((((((a))))))))', 0, 17, 1, 502);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\g<bar>|\\zEND(?<bar>.*abc\$)', 'abcxxxabc', 0, 9, 503);
    CSuite(enc: eucJpEncoding).x2('\\g<1>|\\zEND(.a.)', 'bac', 0, 3, 504);
    CSuite(
      enc: eucJpEncoding,
    ).x3('\\g<_A>\\g<_A>|\\zEND(.a.)(?<_A>.b.)', 'xbxyby', 3, 6, 1, 505);
    CSuite(enc: eucJpEncoding).x2(
      '\\A(?:\\g<pon>|\\g<pan>|\\zEND  (?<pan>a|c\\g<pon>c)(?<pon>b|d\\g<pan>d))\$',
      'cdcbcdc',
      0,
      7,
      506,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\A(?<n>|a\\g<m>)\\z|\\zEND (?<m>\\g<n>)', 'aaaa', 0, 4, 507);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<n>(a|b\\g<n>c){3,5})', 'baaaaca', 1, 5, 508);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<n>(a|b\\g<n>c){3,5})', 'baaaacaaaaa', 0, 10, 509);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<pare>\\(([^\\(\\)]++|\\g<pare>)*+\\))', '((a))', 0, 5, 510);
    CSuite(enc: eucJpEncoding).x2('()*\\1', '', 0, 0, 511);
    CSuite(enc: eucJpEncoding).x2('(?:()|())*\\1\\2', '', 0, 0, 512);
    CSuite(enc: eucJpEncoding).x3('(?:\\1a|())*', 'a', 0, 0, 1, 513);
    CSuite(enc: eucJpEncoding).x2('x((.)*)*x', '0x1x2x3', 1, 6, 514);
    CSuite(
      enc: eucJpEncoding,
    ).x2('x((.)*)*x(?i:\\1)\\Z', '0x1x2x1X2', 1, 9, 515);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:()|()|()|()|()|())*\\2\\5', '', 0, 0, 516);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:()|()|()|(x)|()|())*\\2b\\5', 'b', 0, 1, 517);
    CSuite(enc: eucJpEncoding).x2('\\xED\\xF2', '\xed\xf2', 0, 2, 518);
    CSuite(enc: eucJpEncoding).x2('[0-9-a]', '-', 0, 1, 519);
    CSuite(enc: eucJpEncoding).n('[0-9-a]', ':', 520);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(\\(((?:[^(]|\\g<1>)*)\\))', '(abc)(abc)', 1, 4, 2, 521);
    CSuite(enc: eucJpEncoding).x2('\\o{101}', 'A', 0, 1, 522);
    CSuite(enc: eucJpEncoding).x2('(?:\\k\'+1\'B|(A)C)*', 'ACAB', 0, 4, 523);
    CSuite(enc: eucJpEncoding).x2('\\g<+2>(abc)(ABC){0}', 'ABCabc', 0, 6, 524);
    CSuite(enc: eucJpEncoding).x2('A\\g\'0\'|B()', 'AAAAB', 0, 5, 525);
    CSuite(enc: eucJpEncoding).x3('(A\\g\'0\')|B', 'AAAAB', 0, 5, 1, 526);
    CSuite(enc: eucJpEncoding).x2('(a*)(?(1))aa', 'aaaaa', 0, 5, 527);
    CSuite(enc: eucJpEncoding).x2('(a*)(?(-1))aa', 'aaaaa', 0, 5, 528);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?<name>aaa)(?(\'name\'))aa', 'aaaaa', 0, 5, 529);
    CSuite(enc: eucJpEncoding).x2('(a)(?(1)aa|bb)a', 'aaaaa', 0, 4, 530);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:aa|())(?(<1>)aa|bb)a', 'aabba', 0, 5, 531);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:aa|())(?(\'1\')aa|bb|cc)a', 'aacca', 0, 5, 532);
    CSuite(enc: eucJpEncoding).x3('(a*)(?(1)aa|a)b', 'aaab', 0, 1, 1, 533);
    CSuite(enc: eucJpEncoding).n('(a)(?(1)a|b)c', 'abc', 534);
    CSuite(enc: eucJpEncoding).x2('(a)(?(1)|)c', 'ac', 0, 2, 535);
    CSuite(enc: eucJpEncoding).n('(?()aaa|bbb)', 'bbb', 536);
    CSuite(enc: eucJpEncoding).x2('(a)(?(1+0)b|c)d', 'abd', 0, 3, 537);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:(?\'name\'a)|(?\'name\'b))(?(\'name\')c|d)e', 'ace', 0, 3, 538);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:(?\'name\'a)|(?\'name\'b))(?(\'name\')c|d)e', 'bce', 0, 3, 539);
    CSuite(enc: eucJpEncoding).x2('\\R', '\x0d\x0a', 0, 2, 540);
    CSuite(enc: eucJpEncoding).x2('\\R', '\x0d', 0, 1, 541);
    CSuite(enc: eucJpEncoding).x2('\\R', '\x0a', 0, 1, 542);
    CSuite(enc: eucJpEncoding).x2('\\R', '\x0b', 0, 1, 543);
    CSuite(enc: eucJpEncoding).n('\\R\\n', '\x0d\x0a', 544);
    CSuite(enc: eucJpEncoding).n('\\R', '\xc2\x85', 545);
    CSuite(enc: eucJpEncoding).x2('\\N', 'a', 0, 1, 546);
    CSuite(enc: eucJpEncoding).n('\\N', '\x0a', 547);
    CSuite(enc: eucJpEncoding).n('(?m:\\N)', '\x0a', 548);
    CSuite(enc: eucJpEncoding).n('(?-m:\\N)', '\x0a', 549);
    CSuite(enc: eucJpEncoding).x2('\\O', 'a', 0, 1, 550);
    CSuite(enc: eucJpEncoding).x2('\\O', '\x0a', 0, 1, 551);
    CSuite(enc: eucJpEncoding).x2('(?m:\\O)', '\x0a', 0, 1, 552);
    CSuite(enc: eucJpEncoding).x2('(?-m:\\O)', '\x0a', 0, 1, 553);
    CSuite(enc: eucJpEncoding).x2('\\K', 'a', 0, 0, 554);
    CSuite(enc: eucJpEncoding).x2('a\\K', 'a', 1, 1, 555);
    CSuite(enc: eucJpEncoding).x2('a\\Kb', 'ab', 1, 2, 556);
    CSuite(enc: eucJpEncoding).x2('(a\\Kb|ac\\Kd)', 'acd', 2, 3, 557);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(a\\Kb|\\Kac\\K)*', 'acababacab', 9, 10, 558);
    CSuite(enc: eucJpEncoding).x2('(?~)', '', 0, 0, 560);
    CSuite(enc: eucJpEncoding).x2('(?~)', 'A', 0, 0, 561);
    CSuite(enc: eucJpEncoding).x2('aaaaa(?~)', 'aaaaaaaaaa', 0, 5, 562);
    CSuite(enc: eucJpEncoding).x2('(?~(?:|aaa))', 'aaa', 0, 0, 563);
    CSuite(enc: eucJpEncoding).x2('(?~aaa|)', 'aaa', 0, 0, 564);
    CSuite(
      enc: eucJpEncoding,
    ).x2('a(?~(?~)).', 'abcdefghijklmnopqrstuvwxyz', 0, 26, 565);
    CSuite(enc: eucJpEncoding).x2('/\\*(?~\\*/)\\*/', '/* */ */', 0, 5, 566);
    CSuite(enc: eucJpEncoding).x2('(?~\\w+)zzzzz', 'zzzzz', 0, 5, 567);
    CSuite(enc: eucJpEncoding).x2('(?~\\w*)zzzzz', 'zzzzz', 0, 5, 568);
    CSuite(enc: eucJpEncoding).x2('(?~A.C|B)', 'ABC', 0, 0, 569);
    CSuite(enc: eucJpEncoding).x2('(?~XYZ|ABC)a', 'ABCa', 1, 4, 570);
    CSuite(enc: eucJpEncoding).x2('(?~XYZ|ABC)a', 'aABCa', 0, 1, 571);
    CSuite(
      enc: eucJpEncoding,
    ).x2('<[^>]*>(?~[<>])</[^>]*>', '<a>vvv</a>   <b>  </b>', 0, 10, 572);
    CSuite(enc: eucJpEncoding).x2('(?~ab)', 'ccc\x0adab', 0, 5, 573);
    CSuite(enc: eucJpEncoding).x2('(?m:(?~ab))', 'ccc\x0adab', 0, 5, 574);
    CSuite(enc: eucJpEncoding).x2('(?-m:(?~ab))', 'ccc\x0adab', 0, 5, 575);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~abc)xyz', 'xyz012345678901234567890123456789abc', 0, 3, 576);
    CSuite(enc: eucJpEncoding).x2('(?~|78|\\d*)', '123456789', 0, 6, 579);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|def|(?:abc|de|f){0,100})', 'abcdedeabcfdefabc', 0, 11, 580);
    CSuite(enc: eucJpEncoding).x2('(?~|ab|.*)', 'ccc\x0addd', 0, 3, 581);
    CSuite(enc: eucJpEncoding).x2('(?~|ab|\\O*)', 'ccc\x0adab', 0, 5, 582);
    CSuite(enc: eucJpEncoding).x2('(?~|ab|\\O{2,10})', 'ccc\x0adab', 0, 5, 583);
    CSuite(enc: eucJpEncoding).x2('(?~|ab|\\O{1,10})', 'ab', 1, 2, 584);
    CSuite(enc: eucJpEncoding).n('(?~|ab|\\O{2,10})', 'ab', 585);
    CSuite(enc: eucJpEncoding).x2('(?~|abc|\\O{1,10})', 'abc', 1, 3, 586);
    CSuite(enc: eucJpEncoding).x2('(?~|ab|\\O{5,10})|abc', 'abc', 0, 3, 587);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|ab|\\O{1,10})', 'cccccccccccab', 0, 10, 588);
    CSuite(enc: eucJpEncoding).x2('(?~|aaa|)', 'aaa', 0, 0, 589);
    CSuite(enc: eucJpEncoding).x2('(?~||a*)', 'aaaaaa', 0, 0, 590);
    CSuite(enc: eucJpEncoding).x2('(?~||a*?)', 'aaaaaa', 0, 0, 591);
    CSuite(enc: eucJpEncoding).x2('(a)(?~|b|\\1)', 'aaaaaa', 0, 2, 592);
    CSuite(enc: eucJpEncoding).x2('(a)(?~|bb|(?:a\\1)*)', 'aaaaaa', 0, 5, 593);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(b|c)(?~|abac|(?:a\\1)*)', 'abababacabab', 1, 4, 594);
    CSuite(enc: eucJpEncoding).n('(?~|c|a*+)a', 'aaaaa', 595);
    CSuite(enc: eucJpEncoding).x2('(?~|aaaaa|a*+)', 'aaaaa', 0, 0, 596);
    CSuite(enc: eucJpEncoding).x2('(?~|aaaaaa|a*+)b', 'aaaaaab', 1, 7, 597);
    CSuite(enc: eucJpEncoding).x2('(?~|abcd|(?>))', 'zzzabcd', 0, 0, 598);
    CSuite(enc: eucJpEncoding).x2('(?~|abc|a*?)', 'aaaabc', 0, 0, 599);
    CSuite(enc: eucJpEncoding).x2('(?~|abc)a*', 'aaaaaabc', 0, 5, 602);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|abc)a*z|aaaaaabc', 'aaaaaabc', 0, 8, 603);
    CSuite(enc: eucJpEncoding).x2('(?~|aaaaaa)a*', 'aaaaaa', 0, 0, 604);
    CSuite(enc: eucJpEncoding).x2('(?~|abc)aaaa|aaaabc', 'aaaabc', 0, 6, 605);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?>(?~|abc))aaaa|aaaabc', 'aaaabc', 0, 6, 606);
    CSuite(enc: eucJpEncoding).x2('(?~|)a', 'a', 0, 1, 607);
    CSuite(enc: eucJpEncoding).n('(?~|a)a', 'a', 608);
    CSuite(enc: eucJpEncoding).x2('(?~|a)(?~|)a', 'a', 0, 1, 609);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|a).*(?~|)a', 'bbbbbbbbbbbbbbbbbbbba', 0, 21, 610);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|abc).*(xyz|pqr)(?~|)abc', 'aaaaxyzaaapqrabc', 0, 16, 611);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?~|abc).*(xyz|pqr)(?~|)abc', 'aaaaxyzaaaabcpqrabc', 11, 19, 612);
    CSuite(
      enc: eucJpEncoding,
    ).n('\\A(?~|abc).*(xyz|pqrabc)(?~|)abc', 'aaaaxyzaaaabcpqrabcabc', 613);
    CSuite(enc: eucJpEncoding).x2('(?~|a)(?~|)c|ab|a|', 'ab', 0, 2, 614);
    CSuite(enc: eucJpEncoding).x2('(?~|a)((?~|)c|ab|a|)', 'ab', 0, 0, 615);
    CSuite(enc: eucJpEncoding).x2('(?~|a)((?>(?~|))c|ab|a|)', 'ab', 0, 0, 616);
    CSuite(enc: eucJpEncoding).n('.\\y\\O', '\x0d\x0a', 621);
    CSuite(enc: eucJpEncoding).x2('.\\Y\\O', '\x0d\x0a', 0, 2, 622);
    CSuite(enc: eucJpEncoding).n('\\X\\X', '\x0d\x0a', 623);
    CSuite(enc: eucJpEncoding).x2('^\\X\$', '\x0d\x0a', 0, 2, 624);
    CSuite(enc: eucJpEncoding).x2('^\\X\\X\\X\$', 'ab\x0d\x0a', 0, 4, 625);
    CSuite(enc: eucJpEncoding).x2('', '\xa4\xa2', 0, 0, 627);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2', '\xa4\xa2', 0, 2, 628);
    CSuite(enc: eucJpEncoding).n('\xa4\xa4', '\xa4\xa2', 629);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa6\xa4\xa6', '\xa4\xa6\xa4\xa6', 0, 4, 630);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2\xa4\xa4\xa4\xa6', '\xa4\xa2\xa4\xa4\xa4\xa6', 0, 6, 631);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3',
      '\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3',
      0,
      70,
      632,
    );
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2', '\xa4\xa4\xa4\xa2', 2, 4, 633);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa4\xa4\xa6', '\xa4\xa2\xa4\xa4\xa4\xa6', 2, 6, 634);
    CSuite(enc: eucJpEncoding).x2('\\xca\\xb8', '\xca\xb8', 0, 2, 635);
    CSuite(enc: eucJpEncoding).x2('.', '\xa4\xa2', 0, 2, 636);
    CSuite(enc: eucJpEncoding).x2('..', '\xa4\xab\xa4\xad', 0, 4, 637);
    CSuite(enc: eucJpEncoding).x2('\\w', '\xa4\xaa', 0, 2, 638);
    CSuite(enc: eucJpEncoding).n('\\W', '\xa4\xa2', 639);
    CSuite(enc: eucJpEncoding).x2('[\\W]', '\xa4\xa6\$', 2, 3, 640);
    CSuite(enc: eucJpEncoding).x2('\\S', '\xa4\xbd', 0, 2, 641);
    CSuite(enc: eucJpEncoding).x2('\\S', '\xb4\xc1', 0, 2, 642);
    CSuite(enc: eucJpEncoding).x2('\\b', '\xb5\xa4 ', 0, 0, 643);
    CSuite(enc: eucJpEncoding).x2('\\b', ' \xa4\xdb', 1, 1, 644);
    CSuite(enc: eucJpEncoding).x2('\\B', '\xa4\xbb\xa4\xbd ', 2, 2, 645);
    CSuite(enc: eucJpEncoding).x2('\\B', '\xa4\xa6 ', 3, 3, 646);
    CSuite(enc: eucJpEncoding).x2('\\B', ' \xa4\xa4', 0, 0, 647);
    CSuite(enc: eucJpEncoding).x2('[\xa4\xbf\xa4\xc1]', '\xa4\xc1', 0, 2, 648);
    CSuite(enc: eucJpEncoding).n('[\xa4\xca\xa4\xcb]', '\xa4\xcc', 649);
    CSuite(enc: eucJpEncoding).x2('[\xa4\xa6-\xa4\xaa]', '\xa4\xa8', 0, 2, 650);
    CSuite(enc: eucJpEncoding).n('[^\xa4\xb1]', '\xa4\xb1', 651);
    CSuite(enc: eucJpEncoding).x2('[\\w]', '\xa4\xcd', 0, 2, 652);
    CSuite(enc: eucJpEncoding).n('[\\d]', '\xa4\xd5', 653);
    CSuite(enc: eucJpEncoding).x2('[\\D]', '\xa4\xcf', 0, 2, 654);
    CSuite(enc: eucJpEncoding).n('[\\s]', '\xa4\xaf', 655);
    CSuite(enc: eucJpEncoding).x2('[\\S]', '\xa4\xd8', 0, 2, 656);
    CSuite(enc: eucJpEncoding).x2('[\\w\\d]', '\xa4\xe8', 0, 2, 657);
    CSuite(enc: eucJpEncoding).x2('[\\w\\d]', '   \xa4\xe8', 3, 5, 658);
    CSuite(
      enc: eucJpEncoding,
    ).n('\\w\xb5\xb4\xbc\xd6', ' \xb5\xb4\xbc\xd6', 659);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4\\W\xbc\xd6', '\xb5\xb4 \xbc\xd6', 0, 5, 660);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2.\xa4\xa4.\xa4\xa6',
      '\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa6',
      0,
      10,
      661,
    );
    CSuite(enc: eucJpEncoding).x2(
      '.\\w\xa4\xa6\\W..\xa4\xbe',
      '\xa4\xa8\xa4\xa6\xa4\xa6 \xa4\xa6\xa4\xbe\xa4\xbe',
      0,
      13,
      662,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\\s\\w\xa4\xb3\xa4\xb3\xa4\xb3',
      ' \xa4\xb3\xa4\xb3\xa4\xb3\xa4\xb3',
      0,
      9,
      663,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2\xa4\xa2.\xa4\xb1',
      '\xa4\xa2\xa4\xa2\xa4\xb1\xa4\xb1',
      0,
      8,
      664,
    );
    CSuite(enc: eucJpEncoding).n('.\xa4\xa4', '\xa4\xa4\xa4\xa8', 665);
    CSuite(enc: eucJpEncoding).x2('.\xa4\xaa', '\xa4\xaa\xa4\xaa', 0, 4, 666);
    CSuite(enc: eucJpEncoding).x2('^\xa4\xa2', '\xa4\xa2', 0, 2, 667);
    CSuite(enc: eucJpEncoding).x2('^\xa4\xe0\$', '\xa4\xe0', 0, 2, 668);
    CSuite(enc: eucJpEncoding).x2('^\\w\$', '\xa4\xcb', 0, 2, 669);
    CSuite(enc: eucJpEncoding).x2(
      '^\\w\xa4\xab\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3\$',
      'z\xa4\xab\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3',
      0,
      11,
      670,
    );
    CSuite(enc: eucJpEncoding).x2(
      '^\\w...\xa4\xa6\xa4\xa8\xa4\xaa\$',
      'z\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa6\xa4\xa8\xa4\xaa',
      0,
      13,
      671,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\\w\\w\\s\\W\xa4\xaa\xa4\xaa\xa4\xaa\\d',
      'a\xa4\xaa  \xa4\xaa\xa4\xaa\xa4\xaa4',
      0,
      12,
      672,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\A\xa4\xbf\xa4\xc1\xa4\xc4', '\xa4\xbf\xa4\xc1\xa4\xc4', 0, 6, 673);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xe0\xa4\xe1\xa4\xe2\\Z', '\xa4\xe0\xa4\xe1\xa4\xe2', 0, 6, 674);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xab\xa4\xad\xa4\xaf\\z', '\xa4\xab\xa4\xad\xa4\xaf', 0, 6, 675);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xab\xa4\xad\xa4\xaf\\Z',
      '\xa4\xab\xa4\xad\xa4\xaf\x0a',
      0,
      6,
      676,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\G\xa4\xdd\xa4\xd4', '\xa4\xdd\xa4\xd4', 0, 4, 677);
    CSuite(
      enc: eucJpEncoding,
    ).n('\\G\xa4\xa8', '\xa4\xa6\xa4\xa8\xa4\xaa', 678);
    CSuite(
      enc: eucJpEncoding,
    ).n('\xa4\xc8\xa4\xc6\\G', '\xa4\xc8\xa4\xc6', 679);
    CSuite(
      enc: eucJpEncoding,
    ).n('\xa4\xde\xa4\xdf\\A', '\xa4\xde\xa4\xdf', 680);
    CSuite(
      enc: eucJpEncoding,
    ).n('\xa4\xde\\A\xa4\xdf', '\xa4\xde\xa4\xdf', 681);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?=\xa4\xbb)\xa4\xbb', '\xa4\xbb', 0, 2, 682);
    CSuite(enc: eucJpEncoding).n('(?=\xa4\xa6).', '\xa4\xa4', 683);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?!\xa4\xa6)\xa4\xab', '\xa4\xab', 0, 2, 684);
    CSuite(enc: eucJpEncoding).n('(?!\xa4\xc8)\xa4\xa2', '\xa4\xc8', 685);
    CSuite(enc: eucJpEncoding).x2('(?i:\xa4\xa2)', '\xa4\xa2', 0, 2, 686);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?i:\xa4\xd6\xa4\xd9)', '\xa4\xd6\xa4\xd9', 0, 4, 687);
    CSuite(enc: eucJpEncoding).n('(?i:\xa4\xa4)', '\xa4\xa6', 688);
    CSuite(enc: eucJpEncoding).x2('(?m:\xa4\xe8.)', '\xa4\xe8\x0a', 0, 3, 689);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?m:.\xa4\xe1)', '\xa4\xde\x0a\xa4\xe1', 2, 5, 690);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2?', '', 0, 0, 691);
    CSuite(enc: eucJpEncoding).x2('\xca\xd1?', '\xb2\xbd', 0, 0, 692);
    CSuite(enc: eucJpEncoding).x2('\xca\xd1?', '\xca\xd1', 0, 2, 693);
    CSuite(enc: eucJpEncoding).x2('\xce\xcc*', '', 0, 0, 694);
    CSuite(enc: eucJpEncoding).x2('\xce\xcc*', '\xce\xcc', 0, 2, 695);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xbb\xd2*', '\xbb\xd2\xbb\xd2\xbb\xd2', 0, 6, 696);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xc7\xcf*', '\xbc\xaf\xc7\xcf\xc7\xcf\xc7\xcf\xc7\xcf', 0, 0, 697);
    CSuite(enc: eucJpEncoding).n('\xbb\xb3+', '', 698);
    CSuite(enc: eucJpEncoding).x2('\xb2\xcf+', '\xb2\xcf', 0, 2, 699);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xbb\xfe+', '\xbb\xfe\xbb\xfe\xbb\xfe\xbb\xfe', 0, 8, 700);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa8+', '\xa4\xa8\xa4\xa8\xa4\xa6\xa4\xa6\xa4\xa6', 0, 4, 701);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa6+', '\xa4\xaa\xa4\xa6\xa4\xa6\xa4\xa6\xa4\xa6', 2, 10, 702);
    CSuite(enc: eucJpEncoding).x2('.?', '\xa4\xbf', 0, 2, 703);
    CSuite(
      enc: eucJpEncoding,
    ).x2('.*', '\xa4\xd1\xa4\xd4\xa4\xd7\xa4\xda', 0, 8, 704);
    CSuite(enc: eucJpEncoding).x2('.+', '\xa4\xed', 0, 2, 705);
    CSuite(
      enc: eucJpEncoding,
    ).x2('.+', '\xa4\xa4\xa4\xa6\xa4\xa8\xa4\xab\x0a', 0, 8, 706);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2|\xa4\xa4', '\xa4\xa2', 0, 2, 707);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2|\xa4\xa4', '\xa4\xa4', 0, 2, 708);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2\xa4\xa4|\xa4\xa4\xa4\xa6', '\xa4\xa2\xa4\xa4', 0, 4, 709);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2\xa4\xa4|\xa4\xa4\xa4\xa6', '\xa4\xa4\xa4\xa6', 0, 4, 710);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xf2(?:\xa4\xab\xa4\xad|\xa4\xad\xa4\xaf)',
      '\xa4\xf2\xa4\xab\xa4\xad',
      0,
      6,
      711,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xf2(?:\xa4\xab\xa4\xad|\xa4\xad\xa4\xaf)\xa4\xb1',
      '\xa4\xf2\xa4\xad\xa4\xaf\xa4\xb1',
      0,
      8,
      712,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2\xa4\xa4|(?:\xa4\xa2\xa4\xa6|\xa4\xa2\xa4\xf2)',
      '\xa4\xa2\xa4\xf2',
      0,
      4,
      713,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2|\xa4\xa4|\xa4\xa6', '\xa4\xa8\xa4\xa6', 2, 4, 714);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2|\xa4\xa4|\xa4\xa6\xa4\xa8|\xa4\xaa\xa4\xab\xa4\xad|\xa4\xaf|\xa4\xb1\xa4\xb3\xa4\xb5|\xa4\xb7\xa4\xb9\xa4\xbb|\xa4\xbd|\xa4\xbf\xa4\xc1|\xa4\xc4\xa4\xc6\xa4\xc8\xa4\xca\xa4\xcb|\xa4\xcc\xa4\xcd',
      '\xa4\xb7\xa4\xb9\xa4\xbb',
      0,
      6,
      715,
    );
    CSuite(enc: eucJpEncoding).n(
      '\xa4\xa2|\xa4\xa4|\xa4\xa6\xa4\xa8|\xa4\xaa\xa4\xab\xa4\xad|\xa4\xaf|\xa4\xb1\xa4\xb3\xa4\xb5|\xa4\xb7\xa4\xb9\xa4\xbb|\xa4\xbd|\xa4\xbf\xa4\xc1|\xa4\xc4\xa4\xc6\xa4\xc8\xa4\xca\xa4\xcb|\xa4\xcc\xa4\xcd',
      '\xa4\xb9\xa4\xbb',
      716,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2|^\xa4\xef', '\xa4\xd6\xa4\xa2', 2, 4, 717);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2|^\xa4\xf2', '\xa4\xf2\xa4\xa2', 0, 2, 718);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\\G\xbc\xd6', '\xa4\xb1\xbc\xd6\xb5\xb4', 4, 6, 719);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\\G\xbc\xd6', '\xbc\xd6\xb5\xb4', 0, 2, 720);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\\A\xbc\xd6', 'b\xbc\xd6\xb5\xb4', 3, 5, 721);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\\A\xbc\xd6', '\xbc\xd6', 0, 2, 722);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\xbc\xd6\\Z', '\xbc\xd6\xb5\xb4', 2, 4, 723);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\xbc\xd6\\Z', '\xbc\xd6', 0, 2, 724);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\xbc\xd6\\Z', '\xbc\xd6\x0a', 0, 2, 725);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\xbc\xd6\\z', '\xbc\xd6\xb5\xb4', 2, 4, 726);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xb5\xb4|\xbc\xd6\\z', '\xbc\xd6', 0, 2, 727);
    CSuite(enc: eucJpEncoding).x2('\\w|\\s', '\xa4\xaa', 0, 2, 728);
    CSuite(enc: eucJpEncoding).x2('\\w|%', '%\xa4\xaa', 0, 1, 729);
    CSuite(enc: eucJpEncoding).x2('\\w|[&\$]', '\xa4\xa6&', 0, 2, 730);
    CSuite(enc: eucJpEncoding).x2('[\xa4\xa4-\xa4\xb1]', '\xa4\xa6', 0, 2, 731);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[\xa4\xa4-\xa4\xb1]|[^\xa4\xab-\xa4\xb3]', '\xa4\xa2', 0, 2, 732);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[\xa4\xa4-\xa4\xb1]|[^\xa4\xab-\xa4\xb3]', '\xa4\xab', 0, 2, 733);
    CSuite(enc: eucJpEncoding).x2('[^\xa4\xa2]', '\x0a', 0, 1, 734);
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2|[\xa4\xa6-\xa4\xad])|\xa4\xa4\xa4\xf2',
      '\xa4\xa6\xa4\xf2',
      0,
      2,
      735,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2|[\xa4\xa6-\xa4\xad])|\xa4\xa4\xa4\xf2',
      '\xa4\xa4\xa4\xf2',
      0,
      4,
      736,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2\xa4\xa4\xa4\xa6|(?=\xa4\xb1\xa4\xb1)..\xa4\xdb',
      '\xa4\xb1\xa4\xb1\xa4\xdb',
      0,
      6,
      737,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2\xa4\xa4\xa4\xa6|(?!\xa4\xb1\xa4\xb1)..\xa4\xdb',
      '\xa4\xa2\xa4\xa4\xa4\xdb',
      0,
      6,
      738,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?=\xa4\xf2\xa4\xa2)..\xa4\xa2|(?=\xa4\xf2\xa4\xf2)..\xa4\xa2',
      '\xa4\xf2\xa4\xf2\xa4\xa2',
      0,
      6,
      739,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?<=\xa4\xa2|\xa4\xa4\xa4\xa6)\xa4\xa4',
      '\xa4\xa4\xa4\xa6\xa4\xa4',
      4,
      6,
      740,
    );
    CSuite(enc: eucJpEncoding).n(
      '(?>\xa4\xa2|\xa4\xa2\xa4\xa4\xa4\xa8)\xa4\xa6',
      '\xa4\xa2\xa4\xa4\xa4\xa8\xa4\xa6',
      741,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?>\xa4\xa2\xa4\xa4\xa4\xa8|\xa4\xa2)\xa4\xa6',
      '\xa4\xa2\xa4\xa4\xa4\xa8\xa4\xa6',
      0,
      8,
      742,
    );
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2?|\xa4\xa4', '\xa4\xa2', 0, 2, 743);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2?|\xa4\xa4', '\xa4\xa4', 0, 0, 744);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2?|\xa4\xa4', '', 0, 0, 745);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2*|\xa4\xa4', '\xa4\xa2\xa4\xa2', 0, 4, 746);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2*|\xa4\xa4*', '\xa4\xa4\xa4\xa2', 0, 0, 747);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2*|\xa4\xa4*', '\xa4\xa2\xa4\xa4', 0, 2, 748);
    CSuite(enc: eucJpEncoding).x2(
      '[a\xa4\xa2]*|\xa4\xa4*',
      'a\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      3,
      749,
    );
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2+|\xa4\xa4*', '', 0, 0, 750);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2+|\xa4\xa4*', '\xa4\xa4\xa4\xa4\xa4\xa4', 0, 6, 751);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2+|\xa4\xa4*', '\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4', 0, 2, 752);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2+|\xa4\xa4*', 'a\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4', 0, 0, 753);
    CSuite(enc: eucJpEncoding).n('\xa4\xa2+|\xa4\xa4+', '', 754);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xa4\xa2|\xa4\xa4)?', '\xa4\xa4', 0, 2, 755);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xa4\xa2|\xa4\xa4)*', '\xa4\xa4\xa4\xa2', 0, 4, 756);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xa4\xa2|\xa4\xa4)+', '\xa4\xa4\xa4\xa2\xa4\xa4', 0, 6, 757);
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2\xa4\xa4|\xa4\xa6\xa4\xa2)+',
      '\xa4\xa6\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8',
      0,
      8,
      758,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2\xa4\xa4|\xa4\xa6\xa4\xa8)+',
      '\xa4\xa6\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8',
      4,
      12,
      759,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2\xa4\xa4|\xa4\xa6\xa4\xa2)+',
      '\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa2',
      2,
      10,
      760,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2\xa4\xa4|\xa4\xa6\xa4\xa2)+',
      '\xa4\xa2\xa4\xa4\xa4\xf2\xa4\xa6\xa4\xa2',
      0,
      4,
      761,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2\xa4\xa4|\xa4\xa6\xa4\xa2)+',
      '\$\$zzzz\xa4\xa2\xa4\xa4\xa4\xf2\xa4\xa6\xa4\xa2',
      6,
      10,
      762,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2|\xa4\xa4\xa4\xa2\xa4\xa4)+',
      '\xa4\xa2\xa4\xa4\xa4\xa2\xa4\xa4\xa4\xa2',
      0,
      10,
      763,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xa4\xa2|\xa4\xa4\xa4\xa2\xa4\xa4)+', '\xa4\xa4\xa4\xa2', 2, 4, 764);
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2|\xa4\xa4\xa4\xa2\xa4\xa4)+',
      '\xa4\xa4\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa2',
      2,
      8,
      765,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2|\xa4\xa4)(?:\xa4\xa2|\xa4\xa4)',
      '\xa4\xa2\xa4\xa4',
      0,
      4,
      766,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2*|\xa4\xa4*)(?:\xa4\xa2*|\xa4\xa4*)',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      6,
      767,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2*|\xa4\xa4*)(?:\xa4\xa2+|\xa4\xa4+)',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      12,
      768,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2+|\xa4\xa4+){2}',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      12,
      769,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2+|\xa4\xa4+){1,2}',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      12,
      770,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xa2+|\\A\xa4\xa4*)\xa4\xa6\xa4\xa6',
      '\xa4\xa6\xa4\xa6',
      0,
      4,
      771,
    );
    CSuite(enc: eucJpEncoding).n(
      '(?:\xa4\xa2+|\\A\xa4\xa4*)\xa4\xa6\xa4\xa6',
      '\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa6',
      772,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:^\xa4\xa2+|\xa4\xa4+)*\xa4\xa6',
      '\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa2\xa4\xa4\xa4\xa6',
      12,
      16,
      773,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:^\xa4\xa2+|\xa4\xa4+)*\xa4\xa6',
      '\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa6',
      0,
      14,
      774,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa6{0,}', '\xa4\xa6\xa4\xa6\xa4\xa6\xa4\xa6', 0, 8, 775);
    CSuite(enc: eucJpEncoding).x2('\xa4\xa2|(?i)c', 'C', 0, 1, 776);
    CSuite(enc: eucJpEncoding).x2('(?i)c|\xa4\xa2', 'C', 0, 1, 777);
    CSuite(enc: eucJpEncoding).x2('(?i:\xa4\xa2)|a', 'a', 0, 1, 778);
    CSuite(enc: eucJpEncoding).n('(?i:\xa4\xa2)|a', 'A', 779);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[\xa4\xa2\xa4\xa4\xa4\xa6]?', '\xa4\xa2\xa4\xa4\xa4\xa6', 0, 2, 780);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[\xa4\xa2\xa4\xa4\xa4\xa6]*', '\xa4\xa2\xa4\xa4\xa4\xa6', 0, 6, 781);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[^\xa4\xa2\xa4\xa4\xa4\xa6]*', '\xa4\xa2\xa4\xa4\xa4\xa6', 0, 0, 782);
    CSuite(
      enc: eucJpEncoding,
    ).n('[^\xa4\xa2\xa4\xa4\xa4\xa6]+', '\xa4\xa2\xa4\xa4\xa4\xa6', 783);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2??', '\xa4\xa2\xa4\xa2\xa4\xa2', 0, 0, 784);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa4\xa4\xa2??\xa4\xa4', '\xa4\xa4\xa4\xa2\xa4\xa4', 0, 6, 785);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2*?', '\xa4\xa2\xa4\xa2\xa4\xa2', 0, 0, 786);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa4\xa4\xa2*?', '\xa4\xa4\xa4\xa2\xa4\xa2', 0, 2, 787);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa4\xa4\xa2*?\xa4\xa4',
      '\xa4\xa4\xa4\xa2\xa4\xa2\xa4\xa4',
      0,
      8,
      788,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2+?', '\xa4\xa2\xa4\xa2\xa4\xa2', 0, 2, 789);
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa4\xa4\xa2+?', '\xa4\xa4\xa4\xa2\xa4\xa2', 0, 4, 790);
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa4\xa4\xa2+?\xa4\xa4',
      '\xa4\xa4\xa4\xa2\xa4\xa2\xa4\xa4',
      0,
      8,
      791,
    );
    CSuite(enc: eucJpEncoding).x2('(?:\xc5\xb7?)??', '\xc5\xb7', 0, 0, 792);
    CSuite(enc: eucJpEncoding).x2('(?:\xc5\xb7??)?', '\xc5\xb7', 0, 0, 793);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:\xcc\xb4?)+?', '\xcc\xb4\xcc\xb4\xcc\xb4', 0, 2, 794);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:\xc9\xf7+)??', '\xc9\xf7\xc9\xf7\xc9\xf7', 0, 0, 795);
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xc0\xe3+)??\xc1\xfa',
      '\xc0\xe3\xc0\xe3\xc0\xe3\xc1\xfa',
      0,
      8,
      796,
    );
    CSuite(enc: eucJpEncoding).x2('(?:\xa4\xa2\xa4\xa4)?{2}', '', 0, 0, 797);
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6)?{2}',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4',
      0,
      8,
      798,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6)*{0}',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4',
      0,
      0,
      799,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6){3,}',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6',
      0,
      16,
      800,
    );
    CSuite(
      enc: eucJpEncoding,
    ).n('(?:\xb5\xb4\xbc\xd6){3,}', '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6', 801);
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6){2,4}',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6',
      0,
      12,
      802,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6){2,4}',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6',
      0,
      16,
      803,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xb5\xb4\xbc\xd6){2,4}?',
      '\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6\xb5\xb4\xbc\xd6',
      0,
      8,
      804,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('(?:\xb5\xb4\xbc\xd6){,}', '\xb5\xb4\xbc\xd6{,}', 0, 7, 805);
    CSuite(enc: eucJpEncoding).x2(
      '(?:\xa4\xab\xa4\xad\xa4\xaf)+?{2}',
      '\xa4\xab\xa4\xad\xa4\xaf\xa4\xab\xa4\xad\xa4\xaf\xa4\xab\xa4\xad\xa4\xaf',
      0,
      12,
      806,
    );
    CSuite(enc: eucJpEncoding).x3('(\xb2\xd0)', '\xb2\xd0', 0, 2, 1, 807);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(\xb2\xd0\xbf\xe5)', '\xb2\xd0\xbf\xe5', 0, 4, 1, 808);
    CSuite(
      enc: eucJpEncoding,
    ).x2('((\xbb\xfe\xb4\xd6))', '\xbb\xfe\xb4\xd6', 0, 4, 809);
    CSuite(
      enc: eucJpEncoding,
    ).x3('((\xc9\xf7\xbf\xe5))', '\xc9\xf7\xbf\xe5', 0, 4, 1, 810);
    CSuite(
      enc: eucJpEncoding,
    ).x3('((\xba\xf2\xc6\xfc))', '\xba\xf2\xc6\xfc', 0, 4, 2, 811);
    CSuite(enc: eucJpEncoding).x3(
      '((((((((((((((((((((\xce\xcc\xbb\xd2))))))))))))))))))))',
      '\xce\xcc\xbb\xd2',
      0,
      4,
      20,
      812,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2\xa4\xa4)(\xa4\xa6\xa4\xa8)',
      '\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8',
      0,
      4,
      1,
      813,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2\xa4\xa4)(\xa4\xa6\xa4\xa8)',
      '\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8',
      4,
      8,
      2,
      814,
    );
    CSuite(enc: eucJpEncoding).x3(
      '()(\xa4\xa2)\xa4\xa4\xa4\xa6(\xa4\xa8\xa4\xaa\xa4\xab)\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3',
      '\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8\xa4\xaa\xa4\xab\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3',
      6,
      12,
      3,
      815,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(()(\xa4\xa2)\xa4\xa4\xa4\xa6(\xa4\xa8\xa4\xaa\xa4\xab)\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3)',
      '\xa4\xa2\xa4\xa4\xa4\xa6\xa4\xa8\xa4\xaa\xa4\xab\xa4\xad\xa4\xaf\xa4\xb1\xa4\xb3',
      6,
      12,
      4,
      816,
    );
    CSuite(enc: eucJpEncoding).x3(
      '.*(\xa5\xd5\xa5\xa9)\xa5\xf3\xa1\xa6\xa5\xde(\xa5\xf3()\xa5\xb7\xa5\xe5\xa5\xbf)\xa5\xa4\xa5\xf3',
      '\xa5\xd5\xa5\xa9\xa5\xf3\xa1\xa6\xa5\xde\xa5\xf3\xa5\xb7\xa5\xe5\xa5\xbf\xa5\xa4\xa5\xf3',
      10,
      18,
      2,
      817,
    );
    CSuite(enc: eucJpEncoding).x2('(^\xa4\xa2)', '\xa4\xa2', 0, 2, 818);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(\xa4\xa2)|(\xa4\xa2)', '\xa4\xa4\xa4\xa2', 2, 4, 1, 819);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(^\xa4\xa2)|(\xa4\xa2)', '\xa4\xa4\xa4\xa2', 2, 4, 2, 820);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(\xa4\xa2?)', '\xa4\xa2\xa4\xa2\xa4\xa2', 0, 2, 1, 821);
    CSuite(
      enc: eucJpEncoding,
    ).x3('(\xa4\xde*)', '\xa4\xde\xa4\xde\xa4\xde', 0, 6, 1, 822);
    CSuite(enc: eucJpEncoding).x3('(\xa4\xc8*)', '', 0, 0, 1, 823);
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xeb+)',
      '\xa4\xeb\xa4\xeb\xa4\xeb\xa4\xeb\xa4\xeb\xa4\xeb\xa4\xeb',
      0,
      14,
      1,
      824,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xd5+|\xa4\xd8*)',
      '\xa4\xd5\xa4\xd5\xa4\xd5\xa4\xd8\xa4\xd8',
      0,
      6,
      1,
      825,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2+|\xa4\xa4?)',
      '\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa2\xa4\xa2',
      0,
      2,
      1,
      826,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2\xa4\xa4\xa4\xa6)?',
      '\xa4\xa2\xa4\xa4\xa4\xa6',
      0,
      6,
      1,
      827,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2\xa4\xa4\xa4\xa6)*',
      '\xa4\xa2\xa4\xa4\xa4\xa6',
      0,
      6,
      1,
      828,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2\xa4\xa4\xa4\xa6)+',
      '\xa4\xa2\xa4\xa4\xa4\xa6',
      0,
      6,
      1,
      829,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xb5\xa4\xb7\xa4\xb9|\xa4\xa2\xa4\xa4\xa4\xa6)+',
      '\xa4\xa2\xa4\xa4\xa4\xa6',
      0,
      6,
      1,
      830,
    );
    CSuite(enc: eucJpEncoding).x3(
      '([\xa4\xca\xa4\xcb\xa4\xcc][\xa4\xab\xa4\xad\xa4\xaf]|\xa4\xab\xa4\xad\xa4\xaf)+',
      '\xa4\xab\xa4\xad\xa4\xaf',
      0,
      6,
      1,
      831,
    );
    CSuite(enc: eucJpEncoding).x3(
      '((?i:\xa4\xa2\xa4\xa4\xa4\xa6))',
      '\xa4\xa2\xa4\xa4\xa4\xa6',
      0,
      6,
      1,
      832,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x3('((?m:\xa4\xa2.\xa4\xa6))', '\xa4\xa2\x0a\xa4\xa6', 0, 5, 1, 833);
    CSuite(enc: eucJpEncoding).x3(
      '((?=\xa4\xa2\xa4\xf3)\xa4\xa2)',
      '\xa4\xa2\xa4\xf3\xa4\xa4',
      0,
      2,
      1,
      834,
    );
    CSuite(enc: eucJpEncoding).x3(
      '\xa4\xa2\xa4\xa4\xa4\xa6|(.\xa4\xa2\xa4\xa4\xa4\xa8)',
      '\xa4\xf3\xa4\xa2\xa4\xa4\xa4\xa8',
      0,
      8,
      1,
      835,
    );
    CSuite(enc: eucJpEncoding).x3(
      '\xa4\xa2*(.)',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xf3',
      8,
      10,
      1,
      836,
    );
    CSuite(enc: eucJpEncoding).x3(
      '\xa4\xa2*?(.)',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xf3',
      0,
      2,
      1,
      837,
    );
    CSuite(enc: eucJpEncoding).x3(
      '\xa4\xa2*?(\xa4\xf3)',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xf3',
      8,
      10,
      1,
      838,
    );
    CSuite(enc: eucJpEncoding).x3(
      '[\xa4\xa4\xa4\xa6\xa4\xa8]\xa4\xa2*(.)',
      '\xa4\xa8\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xf3',
      10,
      12,
      1,
      839,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\\A\xa4\xa4\xa4\xa4)\xa4\xa6\xa4\xa6',
      '\xa4\xa4\xa4\xa4\xa4\xa6\xa4\xa6',
      0,
      4,
      1,
      840,
    );
    CSuite(enc: eucJpEncoding).n(
      '(\\A\xa4\xa4\xa4\xa4)\xa4\xa6\xa4\xa6',
      '\xa4\xf3\xa4\xa4\xa4\xa4\xa4\xa6\xa4\xa6',
      841,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(^\xa4\xa4\xa4\xa4)\xa4\xa6\xa4\xa6',
      '\xa4\xa4\xa4\xa4\xa4\xa6\xa4\xa6',
      0,
      4,
      1,
      842,
    );
    CSuite(enc: eucJpEncoding).n(
      '(^\xa4\xa4\xa4\xa4)\xa4\xa6\xa4\xa6',
      '\xa4\xf3\xa4\xa4\xa4\xa4\xa4\xa6\xa4\xa6',
      843,
    );
    CSuite(enc: eucJpEncoding).x3(
      '\xa4\xed\xa4\xed(\xa4\xeb\xa4\xeb\$)',
      '\xa4\xed\xa4\xed\xa4\xeb\xa4\xeb',
      4,
      8,
      1,
      844,
    );
    CSuite(enc: eucJpEncoding).n(
      '\xa4\xed\xa4\xed(\xa4\xeb\xa4\xeb\$)',
      '\xa4\xed\xa4\xed\xa4\xeb\xa4\xeb\xa4\xeb',
      845,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xcc\xb5)\\1', '\xcc\xb5\xcc\xb5', 0, 4, 846);
    CSuite(enc: eucJpEncoding).n('(\xcc\xb5)\\1', '\xcc\xb5\xc9\xf0', 847);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xb6\xf5?)\\1', '\xb6\xf5\xb6\xf5', 0, 4, 848);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\xb6\xf5??)\\1', '\xb6\xf5\xb6\xf5', 0, 0, 849);
    CSuite(enc: eucJpEncoding).x2(
      '(\xb6\xf5*)\\1',
      '\xb6\xf5\xb6\xf5\xb6\xf5\xb6\xf5\xb6\xf5',
      0,
      8,
      850,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xb6\xf5*)\\1',
      '\xb6\xf5\xb6\xf5\xb6\xf5\xb6\xf5\xb6\xf5',
      0,
      4,
      1,
      851,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\xa4\xa2(\xa4\xa4*)\\1',
      '\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      10,
      852,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\xa4\xa2(\xa4\xa4*)\\1', '\xa4\xa2\xa4\xa4', 0, 2, 853);
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2*)(\xa4\xa4*)\\1\\2',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4',
      0,
      20,
      854,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xa2*)(\xa4\xa4*)\\2',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa4',
      0,
      14,
      855,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(\xa4\xa2*)(\xa4\xa4*)\\2',
      '\xa4\xa2\xa4\xa2\xa4\xa2\xa4\xa4\xa4\xa4\xa4\xa4\xa4\xa4',
      6,
      10,
      2,
      856,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(((((((\xa4\xdd*)\xa4\xda))))))\xa4\xd4\\7',
      '\xa4\xdd\xa4\xdd\xa4\xdd\xa4\xda\xa4\xd4\xa4\xdd\xa4\xdd\xa4\xdd',
      0,
      16,
      857,
    );
    CSuite(enc: eucJpEncoding).x3(
      '(((((((\xa4\xdd*)\xa4\xda))))))\xa4\xd4\\7',
      '\xa4\xdd\xa4\xdd\xa4\xdd\xa4\xda\xa4\xd4\xa4\xdd\xa4\xdd\xa4\xdd',
      0,
      6,
      7,
      858,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xa4\xcf)(\xa4\xd2)(\xa4\xd5)\\2\\1\\3',
      '\xa4\xcf\xa4\xd2\xa4\xd5\xa4\xd2\xa4\xcf\xa4\xd5',
      0,
      12,
      859,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('([\xa4\xad-\xa4\xb1])\\1', '\xa4\xaf\xa4\xaf', 0, 4, 860);
    CSuite(
      enc: eucJpEncoding,
    ).x2('(\\w\\d\\s)\\1', '\xa4\xa25 \xa4\xa25 ', 0, 8, 861);
    CSuite(enc: eucJpEncoding).n('(\\w\\d\\s)\\1', '\xa4\xa25 \xa4\xa25', 862);
    CSuite(enc: eucJpEncoding).x2(
      '(\xc3\xaf\xa1\xa9|[\xa4\xa2-\xa4\xa6]{3})\\1',
      '\xc3\xaf\xa1\xa9\xc3\xaf\xa1\xa9',
      0,
      8,
      863,
    );
    CSuite(enc: eucJpEncoding).x2(
      '...(\xc3\xaf\xa1\xa9|[\xa4\xa2-\xa4\xa6]{3})\\1',
      '\xa4\xa2a\xa4\xa2\xc3\xaf\xa1\xa9\xc3\xaf\xa1\xa9',
      0,
      13,
      864,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(\xc3\xaf\xa1\xa9|[\xa4\xa2-\xa4\xa6]{3})\\1',
      '\xa4\xa6\xa4\xa4\xa4\xa6\xa4\xa6\xa4\xa4\xa4\xa6',
      0,
      12,
      865,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('(^\xa4\xb3)\\1', '\xa4\xb3\xa4\xb3', 0, 4, 866);
    CSuite(
      enc: eucJpEncoding,
    ).n('(^\xa4\xe0)\\1', '\xa4\xe1\xa4\xe0\xa4\xe0', 867);
    CSuite(enc: eucJpEncoding).n('(\xa4\xa2\$)\\1', '\xa4\xa2\xa4\xa2', 868);
    CSuite(
      enc: eucJpEncoding,
    ).n('(\xa4\xa2\xa4\xa4\\Z)\\1', '\xa4\xa2\xa4\xa4', 869);
    CSuite(enc: eucJpEncoding).x2('(\xa4\xa2*\\Z)\\1', '\xa4\xa2', 2, 2, 870);
    CSuite(
      enc: eucJpEncoding,
    ).x2('.(\xa4\xa2*\\Z)\\1', '\xa4\xa4\xa4\xa2', 2, 4, 871);
    CSuite(enc: eucJpEncoding).x3(
      '(.(\xa4\xe4\xa4\xa4\xa4\xe6)\\2)',
      'z\xa4\xe4\xa4\xa4\xa4\xe6\xa4\xe4\xa4\xa4\xa4\xe6',
      0,
      13,
      1,
      872,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x3('(.(..\\d.)\\2)', '\xa4\xa212341234', 0, 10, 1, 873);
    CSuite(enc: eucJpEncoding).x2(
      '((?i:\xa4\xa2v\xa4\xba))\\1',
      '\xa4\xa2v\xa4\xba\xa4\xa2v\xa4\xba',
      0,
      10,
      874,
    );
    CSuite(enc: eucJpEncoding).x2(
      '(?<\xb6\xf2\xa4\xab>\xca\xd1|\\(\\g<\xb6\xf2\xa4\xab>\\))',
      '((((((\xca\xd1))))))',
      0,
      14,
      875,
    );
    CSuite(enc: eucJpEncoding).x2(
      '\\A(?:\\g<\xb0\xa4_1>|\\g<\xb1\xbe_2>|\\z\xbd\xaa\xce\xbb  (?<\xb0\xa4_1>\xb4\xd1|\xbc\xab\\g<\xb1\xbe_2>\xbc\xab)(?<\xb1\xbe_2>\xba\xdf|\xca\xee\xbb\xa7\\g<\xb0\xa4_1>\xca\xee\xbb\xa7))\$',
      '\xca\xee\xbb\xa7\xbc\xab\xca\xee\xbb\xa7\xbc\xab\xba\xdf\xbc\xab\xca\xee\xbb\xa7\xbc\xab\xca\xee\xbb\xa7',
      0,
      26,
      876,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('[[\xa4\xd2\xa4\xd5]]', '\xa4\xd5', 0, 2, 877);
    CSuite(
      enc: eucJpEncoding,
    ).x2('[[\xa4\xa4\xa4\xaa\xa4\xa6]\xa4\xab]', '\xa4\xab', 0, 2, 878);
    CSuite(enc: eucJpEncoding).n('[[^\xa4\xa2]]', '\xa4\xa2', 879);
    CSuite(enc: eucJpEncoding).n('[^[\xa4\xa2]]', '\xa4\xa2', 880);
    CSuite(enc: eucJpEncoding).x2('[^[^\xa4\xa2]]', '\xa4\xa2', 0, 2, 881);
    CSuite(enc: eucJpEncoding).x2(
      '[[\xa4\xab\xa4\xad\xa4\xaf]&&\xa4\xad\xa4\xaf]',
      '\xa4\xaf',
      0,
      2,
      882,
    );
    CSuite(
      enc: eucJpEncoding,
    ).n('[[\xa4\xab\xa4\xad\xa4\xaf]&&\xa4\xad\xa4\xaf]', '\xa4\xab', 883);
    CSuite(
      enc: eucJpEncoding,
    ).n('[[\xa4\xab\xa4\xad\xa4\xaf]&&\xa4\xad\xa4\xaf]', '\xa4\xb1', 884);
    CSuite(enc: eucJpEncoding).x2(
      '[\xa4\xa2-\xa4\xf3&&\xa4\xa4-\xa4\xf2&&\xa4\xa6-\xa4\xf1]',
      '\xa4\xf1',
      0,
      2,
      885,
    );
    CSuite(enc: eucJpEncoding).n(
      '[^\xa4\xa2-\xa4\xf3&&\xa4\xa4-\xa4\xf2&&\xa4\xa6-\xa4\xf1]',
      '\xa4\xf1',
      886,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('[[^\xa4\xa2&&\xa4\xa2]&&\xa4\xa2-\xa4\xf3]', '\xa4\xa4', 0, 2, 887);
    CSuite(
      enc: eucJpEncoding,
    ).n('[[^\xa4\xa2&&\xa4\xa2]&&\xa4\xa2-\xa4\xf3]', '\xa4\xa2', 888);
    CSuite(enc: eucJpEncoding).x2(
      '[[^\xa4\xa2-\xa4\xf3&&\xa4\xa4\xa4\xa6\xa4\xa8\xa4\xaa]&&[^\xa4\xa6-\xa4\xab]]',
      '\xa4\xad',
      0,
      2,
      889,
    );
    CSuite(enc: eucJpEncoding).n(
      '[[^\xa4\xa2-\xa4\xf3&&\xa4\xa4\xa4\xa6\xa4\xa8\xa4\xaa]&&[^\xa4\xa6-\xa4\xab]]',
      '\xa4\xa4',
      890,
    );
    CSuite(enc: eucJpEncoding).x2(
      '[^[^\xa4\xa2\xa4\xa4\xa4\xa6]&&[^\xa4\xa6\xa4\xa8\xa4\xaa]]',
      '\xa4\xa6',
      0,
      2,
      891,
    );
    CSuite(enc: eucJpEncoding).x2(
      '[^[^\xa4\xa2\xa4\xa4\xa4\xa6]&&[^\xa4\xa6\xa4\xa8\xa4\xaa]]',
      '\xa4\xa8',
      0,
      2,
      892,
    );
    CSuite(enc: eucJpEncoding).n(
      '[^[^\xa4\xa2\xa4\xa4\xa4\xa6]&&[^\xa4\xa6\xa4\xa8\xa4\xaa]]',
      '\xa4\xab',
      893,
    );
    CSuite(enc: eucJpEncoding).x2('[\xa4\xa2-&&-\xa4\xa2]', '-', 0, 1, 894);
    CSuite(enc: eucJpEncoding).x2(
      '[^[^a-z\xa4\xa2\xa4\xa4\xa4\xa6]&&[^bcdefg\xa4\xa6\xa4\xa8\xa4\xaa]q-w]',
      '\xa4\xa8',
      0,
      2,
      895,
    );
    CSuite(enc: eucJpEncoding).x2(
      '[^[^a-z\xa4\xa2\xa4\xa4\xa4\xa6]&&[^bcdefg\xa4\xa6\xa4\xa8\xa4\xaa]g-w]',
      'f',
      0,
      1,
      896,
    );
    CSuite(enc: eucJpEncoding).x2(
      '[^[^a-z\xa4\xa2\xa4\xa4\xa4\xa6]&&[^bcdefg\xa4\xa6\xa4\xa8\xa4\xaa]g-w]',
      'g',
      0,
      1,
      897,
    );
    CSuite(enc: eucJpEncoding).n(
      '[^[^a-z\xa4\xa2\xa4\xa4\xa4\xa6]&&[^bcdefg\xa4\xa6\xa4\xa8\xa4\xaa]g-w]',
      '2',
      898,
    );
    CSuite(enc: eucJpEncoding).x2(
      'a<b>\xa5\xd0\xa1\xbc\xa5\xb8\xa5\xe7\xa5\xf3\xa4\xce\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9<\\/b>',
      'a<b>\xa5\xd0\xa1\xbc\xa5\xb8\xa5\xe7\xa5\xf3\xa4\xce\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9</b>',
      0,
      32,
      899,
    );
    CSuite(enc: eucJpEncoding).x2(
      '.<b>\xa5\xd0\xa1\xbc\xa5\xb8\xa5\xe7\xa5\xf3\xa4\xce\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9<\\/b>',
      'a<b>\xa5\xd0\xa1\xbc\xa5\xb8\xa5\xe7\xa5\xf3\xa4\xce\xa5\xc0\xa5\xa6\xa5\xf3\xa5\xed\xa1\xbc\xa5\xc9</b>',
      0,
      32,
      900,
    );
    CSuite(
      enc: eucJpEncoding,
    ).x2('\\n?\\z', '\xa4\xb3\xa4\xf3\xa4\xcb\xa4\xc1\xa4\xcf', 10, 10, 901);
    CSuite(enc: eucJpEncoding).x2('\\p{Hiragana}', '\xa4\xd4', 0, 2, 903);
    CSuite(enc: eucJpEncoding).n('\\P{Hiragana}', '\xa4\xd4', 904);
  });
}
