// GENERATED by tool/gen_c_suite.dart from oniguruma-master/test/testp.c.
// 1:1 translation of the Oniguruma C test cases. Do not edit.
import 'package:oniguruma_dart/oniguruma_dart.dart';
import 'c_harness.dart';

void main() {
  group('testp', () {
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('', '', 0, 0, 93);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^', '', 0, 0, 94);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\$', '', 0, 0, 95);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\G', '', 0, 0, 96);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\A', '', 0, 0, 97);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\Z', '', 0, 0, 98);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\z', '', 0, 0, 99);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\$', '', 0, 0, 100);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\ca', '\x01', 0, 1, 101);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\C-b', '\x02', 0, 1, 102);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\c\\\\', '\x1c', 0, 1, 103);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('q[\\c\\\\]', 'q\x1c', 0, 2, 104);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('', 'a', 0, 0, 105);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a', 'a', 0, 1, 106);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\x61', 'a', 0, 1, 107);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('aa', 'aa', 0, 2, 108);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('aaa', 'aaa', 0, 3, 109);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      0,
      35,
      110,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ab', 'ab', 0, 2, 111);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('b', 'ab', 1, 2, 112);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('bc', 'abc', 1, 3, 113);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:#RET#)', '#INS##RET#', 5, 10, 114);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\17', '\x0f', 0, 1, 115);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\x1f', '\x1f', 0, 1, 116);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a(?#....\\\\JJJJ)b', 'ab', 0, 2, 117);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?x)  G (o O(?-x)oO) g L', 'GoOoOgLe', 0, 7, 118);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.', 'a', 0, 1, 119);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('.', '', 120);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('..', 'ab', 0, 2, 121);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w', 'e', 0, 1, 122);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\W', 'e', 123);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\s', ' ', 0, 1, 124);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\S', 'b', 0, 1, 125);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\d', '4', 0, 1, 126);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\D', '4', 127);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\b', 'z ', 0, 0, 128);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\b', ' z', 1, 1, 129);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\B', 'zz ', 1, 1, 130);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\B', 'z ', 2, 2, 131);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\B', ' z', 0, 0, 132);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[ab]', 'b', 0, 1, 133);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[ab]', 'c', 134);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[a-z]', 't', 0, 1, 135);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^a]', 'a', 136);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[^a]', '\x0a', 0, 1, 137);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[]]', ']', 0, 1, 138);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^]]', ']', 139);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\^]+', '0^^1', 1, 3, 140);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[b-]', 'b', 0, 1, 141);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[b-]', '-', 0, 1, 142);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\w]', 'z', 0, 1, 143);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\w]', ' ', 144);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\W]', 'b\$', 1, 2, 145);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\d]', '5', 0, 1, 146);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\d]', 'e', 147);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\D]', 't', 0, 1, 148);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\D]', '3', 149);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\s]', ' ', 0, 1, 150);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\s]', 'a', 151);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\S]', 'b', 0, 1, 152);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\S]', ' ', 153);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\w\\d]', '2', 0, 1, 154);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\w\\d]', ' ', 155);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[:upper:]]', 'B', 0, 1, 156);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[*[:xdigit:]+]', '+', 0, 1, 157);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[*[:xdigit:]+]', 'GHIKK-9+*', 6, 7, 158);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[*[:xdigit:]+]', '-@^+', 3, 4, 159);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[:upper]]', 'A', 160);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[:upper]]', ':', 0, 1, 161);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\044-\\047]', '&', 0, 1, 162);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\x5a-\\x5c]', '[', 0, 1, 163);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\x6A-\\x6D]', 'l', 0, 1, 164);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[\\x6A-\\x6D]', 'n', 165);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n(
      '^[0-9A-F]+ 0+ UNDEF ',
      '75F 00000000 SECT14A notype ()    External    | _rb_apply',
      166,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\[]', '[', 0, 1, 167);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[\\]]', ']', 0, 1, 168);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[&]', '&', 0, 1, 169);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[ab]]', 'b', 0, 1, 170);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[ab]c]', 'c', 0, 1, 171);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[^a]]', 'a', 172);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^[a]]', 'a', 173);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[ab]&&bc]', 'b', 0, 1, 174);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[ab]&&bc]', 'a', 175);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[ab]&&bc]', 'c', 176);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[a-z&&b-y&&c-x]', 'w', 0, 1, 177);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^a-z&&b-y&&c-x]', 'w', 178);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[^a&&a]&&a-z]', 'b', 0, 1, 179);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[^a&&a]&&a-z]', 'a', 180);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[[^a-z&&bcdef]&&[^c-g]]', 'h', 0, 1, 181);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[[^a-z&&bcdef]&&[^c-g]]', 'c', 182);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[^[^abc]&&[^cde]]', 'c', 0, 1, 183);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[^[^abc]&&[^cde]]', 'e', 0, 1, 184);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^[^abc]&&[^cde]]', 'f', 185);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[a-&&-a]', '-', 0, 1, 186);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[a\\-&&\\-a]', '&', 187);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\wabc', ' abc', 188);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a\\Wbc', 'a bc', 0, 4, 189);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a.b.c', 'aabbc', 0, 5, 190);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.\\wb\\W..c', 'abb bcc', 0, 7, 191);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\s\\wzzz', ' zzzz', 0, 5, 192);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('aa.b', 'aabb', 0, 4, 193);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('.a', 'ab', 194);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.a', 'aa', 0, 2, 195);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^a', 'a', 0, 1, 196);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^a\$', 'a', 0, 1, 197);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\w\$', 'a', 0, 1, 198);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('^\\w\$', ' ', 199);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\wab\$', 'zab', 0, 3, 200);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\wabcdef\$', 'zabcdef', 0, 7, 201);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\w...def\$', 'zabcdef', 0, 7, 202);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w\\w\\s\\Waaa\\d', 'aa  aaa4', 0, 8, 203);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\A\\Z', '', 0, 0, 204);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\Axyz', 'xyz', 0, 3, 205);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('xyz\\Z', 'xyz', 0, 3, 206);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('xyz\\z', 'xyz', 0, 3, 207);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a\\Z', 'a', 0, 1, 208);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\Gaz', 'az', 0, 2, 209);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\Gz', 'bza', 210);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('az\\G', 'az', 211);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('az\\A', 'az', 212);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a\\Az', 'az', 213);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\^\\\$', '^\$', 0, 2, 214);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^x?y', 'xy', 0, 2, 215);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^(x?y)', 'xy', 0, 2, 216);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w', '_', 0, 1, 217);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\W', '_', 218);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?=z)z', 'z', 0, 1, 219);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?=z).', 'a', 220);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?!z)a', 'a', 0, 1, 221);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?!z)a', 'z', 222);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:a)', 'a', 0, 1, 223);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:a)', 'A', 0, 1, 224);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:A)', 'a', 0, 1, 225);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i:A)', 'b', 226);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[A-Z])', 'a', 0, 1, 227);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[f-m])', 'H', 0, 1, 228);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[f-m])', 'h', 0, 1, 229);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i:[f-m])', 'e', 230);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[A-c])', 'D', 0, 1, 231);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i:[^a-z])', 'A', 232);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i:[^a-z])', 'a', 233);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[!-k])', 'Z', 0, 1, 234);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[!-k])', '7', 0, 1, 235);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[T-}])', 'b', 0, 1, 236);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:[T-}])', '{', 0, 1, 237);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:\\?a)', '?A', 0, 2, 238);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:\\*A)', '*a', 0, 2, 239);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('.', '\x0a', 240);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:.)', '\x0a', 0, 1, 241);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:a.)', 'a\x0a', 0, 2, 242);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:.b)', 'a\x0ab', 1, 3, 243);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.*abc', 'dddabdd\x0addabc', 8, 13, 244);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:.*abc)', 'dddabddabc', 0, 10, 245);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i)(?-i)a', 'A', 246);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i)(?-i:a)', 'A', 247);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?', '', 0, 0, 248);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?', 'b', 0, 0, 249);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?', 'a', 0, 1, 250);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*', '', 0, 0, 251);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*', 'a', 0, 1, 252);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*', 'aaa', 0, 3, 253);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*', 'baaaa', 0, 0, 254);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a+', '', 255);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+', 'a', 0, 1, 256);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+', 'aaaa', 0, 4, 257);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+', 'aabbb', 0, 2, 258);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+', 'baaaa', 1, 5, 259);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.?', '', 0, 0, 260);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.?', 'f', 0, 1, 261);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.?', '\x0a', 0, 0, 262);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.*', '', 0, 0, 263);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.*', 'abcde', 0, 5, 264);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.+', 'z', 0, 1, 265);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.+', 'zdswer\x0a', 0, 6, 266);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(.*)a\\1f', 'babfbac', 0, 4, 267);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(.*)a\\1f', 'bacbabf', 3, 7, 268);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('((.*)a\\2f)', 'bacbabf', 3, 7, 269);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(.*)a\\1f', 'baczzzzzz\x0abazz\x0azzzzbabf', 19, 23, 270);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b', 'a', 0, 1, 271);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b', 'b', 0, 1, 272);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('|a', 'a', 0, 0, 273);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(|a)', 'a', 0, 0, 274);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ab|bc', 'ab', 0, 2, 275);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ab|bc', 'bc', 0, 2, 276);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('z(?:ab|bc)', 'zbc', 0, 3, 277);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a(?:ab|bc)c', 'aabc', 0, 4, 278);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ab|(?:ac|az)', 'az', 0, 2, 279);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b|c', 'dc', 1, 2, 280);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b|cd|efg|h|ijk|lmn|o|pq|rstuvwx|yz', 'pqr', 0, 2, 281);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a|b|cd|efg|h|ijk|lmn|o|pq|rstuvwx|yz', 'mn', 282);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|^z', 'ba', 1, 2, 283);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|^z', 'za', 0, 1, 284);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|\\Gz', 'bza', 2, 3, 285);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|\\Gz', 'za', 0, 1, 286);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|\\Az', 'bza', 2, 3, 287);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|\\Az', 'za', 0, 1, 288);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b\\Z', 'ba', 1, 2, 289);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b\\Z', 'b', 0, 1, 290);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b\\z', 'ba', 1, 2, 291);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|b\\z', 'b', 0, 1, 292);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w|\\s', ' ', 0, 1, 293);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\w|\\w', ' ', 294);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w|%', '%', 0, 1, 295);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\w|[&\$]', '&', 0, 1, 296);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[b-d]|[^e-z]', 'a', 0, 1, 297);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a|[c-f])|bz', 'dz', 0, 1, 298);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a|[c-f])|bz', 'bz', 0, 2, 299);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('abc|(?=zz)..f', 'zzf', 0, 3, 300);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('abc|(?!zz)..f', 'abf', 0, 3, 301);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?=za)..a|(?=zz)..a', 'zza', 0, 3, 302);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?>a|abd)c', 'abdc', 303);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?>abd|a)c', 'abdc', 0, 4, 304);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?|b', 'a', 0, 1, 305);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?|b', 'b', 0, 0, 306);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a?|b', '', 0, 0, 307);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*|b', 'aa', 0, 2, 308);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*|b*', 'ba', 0, 0, 309);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*|b*', 'ab', 0, 1, 310);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+|b*', '', 0, 0, 311);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+|b*', 'bbb', 0, 3, 312);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+|b*', 'abbb', 0, 1, 313);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a+|b+', '', 314);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|b)?', 'b', 0, 1, 315);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|b)*', 'ba', 0, 2, 316);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|b)+', 'bab', 0, 3, 317);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(ab|ca)+', 'caabbc', 0, 4, 318);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(ab|ca)+', 'aabca', 1, 5, 319);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(ab|ca)+', 'abzca', 0, 2, 320);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|bab)+', 'ababa', 0, 5, 321);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|bab)+', 'ba', 1, 2, 322);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a|bab)+', 'baaaba', 1, 4, 323);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a|b)(?:a|b)', 'ab', 0, 2, 324);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a*|b*)(?:a*|b*)', 'aaabbb', 0, 3, 325);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a*|b*)(?:a+|b+)', 'aaabbb', 0, 6, 326);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a+|b+){2}', 'aaabbb', 0, 6, 327);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('h{0,}', 'hhhh', 0, 4, 328);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a+|b+){1,2}', 'aaabbb', 0, 6, 329);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('ax{2}*a', '0axxxa1', 330);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a.{0,2}a', '0aXXXa0', 331);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a.{0,2}?a', '0aXXXa0', 332);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('a.{0,2}?a', '0aXXXXa0', 333);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^a{2,}?a\$', 'aaa', 0, 3, 334);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^[a-z]{2,}?\$', 'aaa', 0, 3, 335);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a+|\\Ab*)cc', 'cc', 0, 2, 336);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?:a+|\\Ab*)cc', 'abcc', 337);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:^a+|b+)*c', 'aabbbabc', 6, 8, 338);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:^a+|b+)*c', 'aabbbbc', 0, 7, 339);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a|(?i)c', 'C', 0, 1, 340);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i)c|a', 'C', 0, 1, 341);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i)c|a', 'A', 0, 1, 342);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?i:c)|a', 'C', 0, 1, 343);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?i:c)|a', 'A', 344);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[abc]?', 'abc', 0, 1, 345);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[abc]*', 'abc', 0, 3, 346);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[^abc]*', 'abc', 0, 0, 347);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[^abc]+', 'abc', 348);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a??', 'aaa', 0, 0, 349);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ba??b', 'bab', 0, 3, 350);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a*?', 'aaa', 0, 0, 351);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ba*?', 'baa', 0, 1, 352);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ba*?b', 'baab', 0, 4, 353);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a+?', 'aaa', 0, 1, 354);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ba+?', 'baa', 0, 2, 355);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('ba+?b', 'baab', 0, 4, 356);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a?)??', 'a', 0, 0, 357);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a??)?', 'a', 0, 0, 358);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a?)+?', 'aaa', 0, 1, 359);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a+)??', 'aaa', 0, 0, 360);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:a+)??b', 'aaab', 0, 4, 361);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab)?{2}', '', 0, 0, 362);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab)?{2}', 'ababa', 0, 4, 363);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab)*{0}', 'ababa', 0, 0, 364);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab){3,}', 'abababab', 0, 8, 365);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?:ab){3,}', 'abab', 366);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab){2,4}', 'ababab', 0, 6, 367);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab){2,4}', 'ababababab', 0, 8, 368);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab){2,4}?', 'ababababab', 0, 4, 369);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:ab){,}', 'ab{,}', 0, 5, 370);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:abc)+?{2}', 'abcabcabc', 0, 6, 371);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:X*)(?i:xa)', 'XXXa', 0, 4, 372);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(d+)([^abc]z)', 'dddz', 0, 4, 373);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('([^abc]*)([^abc]z)', 'dddz', 0, 4, 374);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(\\w+)(\\wz)', 'dddz', 0, 4, 375);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a)', 'a', 0, 1, 1, 376);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(ab)', 'ab', 0, 2, 1, 377);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('((ab))', 'ab', 0, 2, 378);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((ab))', 'ab', 0, 2, 1, 379);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((ab))', 'ab', 0, 2, 2, 380);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((((((((((((((((((((ab))))))))))))))))))))', 'ab', 0, 2, 20, 381);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(ab)(cd)', 'abcd', 0, 2, 1, 382);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(ab)(cd)', 'abcd', 2, 4, 2, 383);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('()(a)bc(def)ghijk', 'abcdefghijk', 3, 6, 3, 384);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(()(a)bc(def)ghijk)', 'abcdefghijk', 3, 6, 4, 385);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(^a)', 'a', 0, 1, 386);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a)|(a)', 'ba', 1, 2, 1, 387);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(^a)|(a)', 'ba', 1, 2, 2, 388);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a?)', 'aaa', 0, 1, 1, 389);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a*)', 'aaa', 0, 3, 1, 390);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a*)', '', 0, 0, 1, 391);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a+)', 'aaaaaaa', 0, 7, 1, 392);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a+|b*)', 'bbbaa', 0, 3, 1, 393);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a+|b?)', 'bbbaa', 0, 1, 1, 394);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(abc)?', 'abc', 0, 3, 1, 395);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(abc)*', 'abc', 0, 3, 1, 396);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(abc)+', 'abc', 0, 3, 1, 397);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(xyz|abc)+', 'abc', 0, 3, 1, 398);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('([xyz][abc]|abc)+', 'abc', 0, 3, 1, 399);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((?i:abc))', 'AbC', 0, 3, 1, 400);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(abc)(?i:\\1)', 'abcABC', 0, 6, 401);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((?m:a.c))', 'a\x0ac', 0, 3, 1, 402);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('((?=az)a)', 'azb', 0, 1, 1, 403);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('abc|(.abd)', 'zabd', 0, 4, 1, 404);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:abc)|(ABC)', 'abc', 0, 3, 405);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(?i:(abc))|(zzz)', 'ABC', 0, 3, 1, 406);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('a*(.)', 'aaaaz', 4, 5, 1, 407);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('a*?(.)', 'aaaaz', 0, 1, 1, 408);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('a*?(c)', 'aaaac', 4, 5, 1, 409);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('[bcd]a*(.)', 'caaaaz', 5, 6, 1, 410);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(\\Abb)cc', 'bbcc', 0, 2, 1, 411);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(\\Abb)cc', 'zbbcc', 412);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(^bb)cc', 'bbcc', 0, 2, 1, 413);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(^bb)cc', 'zbbcc', 414);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('cc(bb\$)', 'ccbb', 2, 4, 1, 415);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('cc(bb\$)', 'ccbbb', 416);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(\\1)', '', 417);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\1(a)', 'aa', 418);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(a(b)\\1)\\2+', 'ababb', 419);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?:(?:\\1|z)(a))+\$', 'zaa', 420);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:(?:\\1|z)(a))+\$', 'zaaa', 0, 4, 421);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?=\\1)', 'aa', 0, 1, 422);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(a)\$|\\1', 'az', 423);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)\\1', 'aa', 0, 2, 424);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(a)\\1', 'ab', 425);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a?)\\1', 'aa', 0, 2, 426);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a??)\\1', 'aa', 0, 0, 427);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*)\\1', 'aaaaa', 0, 4, 428);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a*)\\1', 'aaaaa', 0, 2, 1, 429);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a(b*)\\1', 'abbbb', 0, 5, 430);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a(b*)\\1', 'ab', 0, 1, 431);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*)(b*)\\1\\2', 'aaabbaaabb', 0, 10, 432);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*)(b*)\\2', 'aaabbbb', 0, 7, 433);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(((((((a*)b))))))c\\7', 'aaabcaaa', 0, 8, 434);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(((((((a*)b))))))c\\7', 'aaabcaaa', 0, 3, 7, 435);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(b)(c)\\2\\1\\3', 'abcbac', 0, 6, 436);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('([a-d])\\1', 'cc', 0, 2, 437);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(\\w\\d\\s)\\1', 'f5 f5 ', 0, 6, 438);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(\\w\\d\\s)\\1', 'f5 f5', 439);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(who|[a-c]{3})\\1', 'whowho', 0, 6, 440);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('...(who|[a-c]{3})\\1', 'abcwhowho', 0, 9, 441);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(who|[a-c]{3})\\1', 'cbccbc', 0, 6, 442);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(^a)\\1', 'aa', 0, 2, 443);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(^a)\\1', 'baa', 444);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(a\$)\\1', 'aa', 445);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(ab\\Z)\\1', 'ab', 446);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*\\Z)\\1', 'a', 1, 1, 447);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.(a*\\Z)\\1', 'ba', 1, 2, 448);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(.(abc)\\2)', 'zabcabc', 0, 7, 1, 449);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(.(..\\d.)\\2)', 'z12341234', 0, 9, 1, 450);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('((?i:az))\\1', 'AzAz', 0, 4, 451);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('((?i:az))\\1', 'Azaz', 452);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=a)b', 'ab', 1, 2, 453);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?<=a)b', 'bb', 454);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=a|b)b', 'bb', 1, 2, 455);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=a|bc)b', 'bcb', 2, 3, 456);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=a|bc)b', 'ab', 1, 2, 457);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=a|bc||defghij|klmnopq|r)z', 'rz', 1, 2, 458);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)\\g<1>', 'aa', 0, 2, 459);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<!a)b', 'cb', 1, 2, 460);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?<!a)b', 'ab', 461);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<!a|bc)b', 'bbb', 0, 1, 462);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?<!a|bc)z', 'bcz', 463);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<name1>a)', 'a', 0, 1, 464);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<name_2>ab)\\g<name_2>', 'abab', 0, 4, 465);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<name_3>.zv.)\\k<name_3>', 'azvbazvb', 0, 8, 466);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<=\\g<ab>)|-\\zEND (?<ab>XyZ)', 'XyZ', 3, 3, 467);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<n>|a\\g<n>)+', '', 0, 0, 468);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<n>|\\(\\g<n>\\))+\$', '()(())', 0, 6, 469);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('\\g<n>(?<n>.){0}', 'X', 0, 1, 1, 470);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\g<n>(abc|df(?<n>.YZ){2,8}){0}', 'XYZ', 0, 3, 471);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\A(?<n>(a\\g<n>)|)\\z', 'aaaa', 0, 4, 472);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      '(?<n>|\\g<m>\\g<n>)\\z|\\zEND (?<m>a|(b)\\g<m>)',
      'bbbbabba',
      0,
      8,
      473,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      '(?<name1240>\\w+\\sx)a+\\k<name1240>',
      '  fg xaaaaaaaafg x',
      2,
      18,
      474,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(z)()()(?<_9>a)\\g<_9>', 'zaa', 2, 3, 1, 475);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(.)(((?<_>a)))\\k<_>', 'zaa', 0, 3, 476);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      '((?<name1>\\d)|(?<name2>\\w))(\\k<name1>|\\k<name2>)',
      'ff',
      0,
      2,
      477,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:(?<x>)|(?<x>efg))\\k<x>', '', 0, 0, 478);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:(?<x>abc)|(?<x>efg))\\k<x>', 'abcefgefg', 3, 9, 479);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?:(?<x>abc)|(?<x>efg))\\k<x>', 'abcefg', 480);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      '(?:(?<n1>.)|(?<n1>..)|(?<n1>...)|(?<n1>....)|(?<n1>.....)|(?<n1>......)|(?<n1>.......)|(?<n1>........)|(?<n1>.........)|(?<n1>..........)|(?<n1>...........)|(?<n1>............)|(?<n1>.............)|(?<n1>..............))\\k<n1>\$',
      'a-pyumpyum',
      2,
      10,
      481,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3(
      '(?:(?<n1>.)|(?<n1>..)|(?<n1>...)|(?<n1>....)|(?<n1>.....)|(?<n1>......)|(?<n1>.......)|(?<n1>........)|(?<n1>.........)|(?<n1>..........)|(?<n1>...........)|(?<n1>............)|(?<n1>.............)|(?<n1>..............))\\k<n1>\$',
      'xxxxabcdefghijklmnabcdefghijklmn',
      4,
      18,
      14,
      482,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3(
      '(?<name1>)(?<name2>)(?<name3>)(?<name4>)(?<name5>)(?<name6>)(?<name7>)(?<name8>)(?<name9>)(?<name10>)(?<name11>)(?<name12>)(?<name13>)(?<name14>)(?<name15>)(?<name16>aaa)(?<name17>)\$',
      'aaa',
      0,
      3,
      16,
      483,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<foo>a|\\(\\g<foo>\\))', 'a', 0, 1, 484);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<foo>a|\\(\\g<foo>\\))', '((((((a))))))', 0, 13, 485);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(?<foo>a|\\(\\g<foo>\\))', '((((((((a))))))))', 0, 17, 1, 486);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\g<bar>|\\zEND(?<bar>.*abc\$)', 'abcxxxabc', 0, 9, 487);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\g<1>|\\zEND(.a.)', 'bac', 0, 3, 488);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('\\g<_A>\\g<_A>|\\zEND(.a.)(?<_A>.b.)', 'xbxyby', 3, 6, 1, 489);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2(
      '\\A(?:\\g<pon>|\\g<pan>|\\zEND  (?<pan>a|c\\g<pon>c)(?<pon>b|d\\g<pan>d))\$',
      'cdcbcdc',
      0,
      7,
      490,
    );
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\A(?<n>|a\\g<m>)\\z|\\zEND (?<m>\\g<n>)', 'aaaa', 0, 4, 491);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<n>(a|b\\g<n>c){3,5})', 'baaaaca', 1, 5, 492);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<n>(a|b\\g<n>c){3,5})', 'baaaacaaaaa', 0, 10, 493);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<pare>\\(([^\\(\\)]++|\\g<pare>)*+\\))', '((a))', 0, 5, 494);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('()*\\1', '', 0, 0, 495);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:()|())*\\1\\2', '', 0, 0, 496);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(?:\\1a|())*', 'a', 0, 0, 1, 497);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('x((.)*)*x', '0x1x2x3', 1, 6, 498);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('x((.)*)*x(?i:\\1)\\Z', '0x1x2x1X2', 1, 9, 499);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:()|()|()|()|()|())*\\2\\5', '', 0, 0, 500);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:()|()|()|(x)|()|())*\\2b\\5', 'b', 0, 1, 501);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('[0-9-a]', '-', 0, 1, 502);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('[0-9-a]', ':', 503);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(\\(((?:[^(]|\\g<1>)*)\\))', '(abc)(abc)', 1, 4, 2, 504);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\o{101}', 'A', 0, 1, 505);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:\\k\'+1\'B|(A)C)*', 'ACAB', 0, 4, 506);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\g<+2>(abc)(ABC){0}', 'ABCabc', 0, 6, 507);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('A\\g\'0\'|B()', 'AAAAB', 0, 5, 508);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(A\\g\'0\')|B', 'AAAAB', 0, 5, 1, 509);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*)(?(1))aa', 'aaaaa', 0, 5, 510);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a*)(?(-1))aa', 'aaaaa', 0, 5, 511);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?<name>aaa)(?(\'name\'))aa', 'aaaaa', 0, 5, 512);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?(1)aa|bb)a', 'aaaaa', 0, 4, 513);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:aa|())(?(<1>)aa|bb)a', 'aabba', 0, 5, 514);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:aa|())(?(\'1\')aa|bb|cc)a', 'aacca', 0, 5, 515);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x3('(a*)(?(1)aa|a)b', 'aaab', 0, 1, 1, 516);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(a)(?(1)a|b)c', 'abc', 517);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?(1)|)c', 'ac', 0, 2, 518);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?()aaa|bbb)', 'bbb', 519);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?(1+0)b|c)d', 'abd', 0, 3, 520);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:(?\'name\'a)|(?\'name\'b))(?(\'name\')c|d)e', 'ace', 0, 3, 521);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?:(?\'name\'a)|(?\'name\'b))(?(\'name\')c|d)e', 'bce', 0, 3, 522);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\R', '\x0d\x0a', 0, 2, 523);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\R', '\x0d', 0, 1, 524);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\R', '\x0a', 0, 1, 525);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\R', '\x0b', 0, 1, 526);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\R\\n', '\x0d\x0a', 527);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\N', 'a', 0, 1, 528);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\N', '\x0a', 529);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?m:\\N)', '\x0a', 530);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?-m:\\N)', '\x0a', 531);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\O', 'a', 0, 1, 532);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\O', '\x0a', 0, 1, 533);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:\\O)', '\x0a', 0, 1, 534);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?-m:\\O)', '\x0a', 0, 1, 535);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('\\K', 'a', 0, 0, 536);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a\\K', 'a', 1, 1, 537);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a\\Kb', 'ab', 1, 2, 538);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a\\Kb|ac\\Kd)', 'acd', 2, 3, 539);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a\\Kb|\\Kac\\K)*', 'acababacab', 9, 10, 540);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~)', '', 0, 0, 542);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~)', 'A', 0, 0, 543);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('aaaaa(?~)', 'aaaaaaaaaa', 0, 5, 544);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~(?:|aaa))', 'aaa', 0, 0, 545);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~aaa|)', 'aaa', 0, 0, 546);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('a(?~(?~)).', 'abcdefghijklmnopqrstuvwxyz', 0, 26, 547);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('/\\*(?~\\*/)\\*/', '/* */ */', 0, 5, 548);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~\\w+)zzzzz', 'zzzzz', 0, 5, 549);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~\\w*)zzzzz', 'zzzzz', 0, 5, 550);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~A.C|B)', 'ABC', 0, 0, 551);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~XYZ|ABC)a', 'ABCa', 1, 4, 552);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~XYZ|ABC)a', 'aABCa', 0, 1, 553);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('<[^>]*>(?~[<>])</[^>]*>', '<a>vvv</a>   <b>  </b>', 0, 10, 554);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~ab)', 'ccc\x0adab', 0, 5, 555);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?m:(?~ab))', 'ccc\x0adab', 0, 5, 556);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?-m:(?~ab))', 'ccc\x0adab', 0, 5, 557);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~abc)xyz', 'xyz012345678901234567890123456789abc', 0, 3, 558);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|78|\\d*)', '123456789', 0, 6, 561);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|def|(?:abc|de|f){0,100})', 'abcdedeabcfdefabc', 0, 11, 562);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|.*)', 'ccc\x0addd', 0, 3, 563);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|\\O*)', 'ccc\x0adab', 0, 5, 564);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|\\O{2,10})', 'ccc\x0adab', 0, 5, 565);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|\\O{1,10})', 'ab', 1, 2, 566);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?~|ab|\\O{2,10})', 'ab', 567);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc|\\O{1,10})', 'abc', 1, 3, 568);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|\\O{5,10})|abc', 'abc', 0, 3, 569);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|ab|\\O{1,10})', 'cccccccccccab', 0, 10, 570);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|aaa|)', 'aaa', 0, 0, 571);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~||a*)', 'aaaaaa', 0, 0, 572);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~||a*?)', 'aaaaaa', 0, 0, 573);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?~|b|\\1)', 'aaaaaa', 0, 2, 574);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(a)(?~|bb|(?:a\\1)*)', 'aaaaaa', 0, 5, 575);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(b|c)(?~|abac|(?:a\\1)*)', 'abababacabab', 1, 4, 576);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?~|c|a*+)a', 'aaaaa', 577);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|aaaaa|a*+)', 'aaaaa', 0, 0, 578);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|aaaaaa|a*+)b', 'aaaaaab', 1, 7, 579);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abcd|(?>))', 'zzzabcd', 0, 0, 580);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc|a*?)', 'aaaabc', 0, 0, 581);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc)a*', 'aaaaaabc', 0, 5, 584);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc)a*z|aaaaaabc', 'aaaaaabc', 0, 8, 585);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|aaaaaa)a*', 'aaaaaa', 0, 0, 586);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc)aaaa|aaaabc', 'aaaabc', 0, 6, 587);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?>(?~|abc))aaaa|aaaabc', 'aaaabc', 0, 6, 588);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|)a', 'a', 0, 1, 589);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('(?~|a)a', 'a', 590);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|a)(?~|)a', 'a', 0, 1, 591);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|a).*(?~|)a', 'bbbbbbbbbbbbbbbbbbbba', 0, 21, 592);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc).*(xyz|pqr)(?~|)abc', 'aaaaxyzaaapqrabc', 0, 16, 593);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|abc).*(xyz|pqr)(?~|)abc', 'aaaaxyzaaaabcpqrabc', 11, 19, 594);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\A(?~|abc).*(xyz|pqrabc)(?~|)abc', 'aaaaxyzaaaabcpqrabcabc', 595);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|a)(?~|)c|ab|a|', 'ab', 0, 2, 596);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|a)((?~|)c|ab|a|)', 'ab', 0, 0, 597);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('(?~|a)((?>(?~|))c|ab|a|)', 'ab', 0, 0, 598);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('.\\y\\O', '\x0d\x0a', 602);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('.\\Y\\O', '\x0d\x0a', 0, 2, 603);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).n('\\X\\X', '\x0d\x0a', 604);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\X\$', '\x0d\x0a', 0, 2, 605);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxOniguruma,
      option: OnigOption.negateSingleLine,
    ).x2('^\\X\\X\\X\$', 'ab\x0d\x0a', 0, 4, 606);
  });
}
