// GENERATED by tool/gen_c_suite.dart from oniguruma-master/test/test_syntax.c.
// 1:1 translation of the Oniguruma C test cases. Do not edit.
import 'package:oniguruma_dart/oniguruma_dart.dart';
import 'c_harness.dart';

void main() {
  group('test_syntax', () {
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{1,3}?', 'aaa', 0, 1, 143);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{3}', 'aaa', 0, 3, 144);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{3}?', 'aaa', 0, 3, 145);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('a{3}?', 'aa', 146);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{3,3}?', 'aaa', 0, 3, 147);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('a{3,3}?', 'aa', 148);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{1,3}+', 'aaaaaa', 0, 3, 155);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{3}+', 'aaaaaa', 0, 3, 156);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('a{3,3}+', 'aaaaaa', 0, 3, 157);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).x2('', '', 0, 0, 164);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).x2('^', '', 0, 0, 165);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('^a', '\x0aa', 166);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('.', '\x0a', 167);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s:.)', '\x0a', 0, 1, 168);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s).', '\x0a', 0, 1, 169);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|.', '\x0a', 0, 1, 170);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?s:a)|.', '\x0a', 171);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('b(?s)a|.', '\x0a', 0, 1, 172);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('((?s)a)|.', '\x0a', 173);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('b(?:(?s)a)|z|.', '\x0a', 174);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('.|b(?s)a', '\x0a', 175);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('.(?s)', '\x0a', 176);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?s)(?-s)a|.', '\x0a', 177);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|.(?-s)', '\x0a', 0, 1, 178);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|((?-s)).', '\x0a', 0, 1, 179);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|(?:(?-s)).', '\x0a', 0, 1, 180);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|(?:).', '\x0a', 0, 1, 181);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|(?:.)', '\x0a', 0, 1, 182);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|(?:a*).', '\x0a', 0, 1, 183);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('a|(?:).', '\x0a', 184);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('a|(?:)(.)', '\x0a', 185);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?s)a|(?:)(.)', '\x0a', 0, 1, 186);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('b(?s)a|(?:)(.)', '\x0a', 0, 1, 187);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('b((?s)a)|(?:)(.)', '\x0a', 188);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?=a).b', 'ab', 0, 2, 195);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?=ab|(.))\\1', 'ab', 1, 2, 196);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?!(.)z)a\\1', 'aa', 197);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=a)b', 'ab', 1, 2, 204);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=a|b)c', 'abc', 2, 3, 205);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=a|(.))\\1', 'abcc', 3, 4, 206);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?<!RMA)X', '123RMAX', 209);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=RMA)X', '123RMAX', 6, 7, 210);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?<!RMA)\$', '123RMA', 211);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=RMA)\$', '123RMA', 6, 6, 212);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?<!RMA)\\Z', '123RMA', 213);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=RMA)\\Z', '123RMA', 6, 6, 214);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).n('(?<!RMA)\\z', '123RMA', 215);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('(?<=RMA)\\z', '123RMA', 6, 6, 216);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPerl).n('(?<!c|c)a', 'ca', 221);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w\\-%]', 'a', 0, 1, 228);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w\\-%]', '%', 0, 1, 229);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w\\-%]', '-', 0, 1, 230);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w-%]', 'a', 0, 1, 233);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w-%]', '%', 0, 1, 234);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPerl,
    ).x2('[\\w-%]', '-', 0, 1, 235);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{1,3}?', 'aaa', 0, 1, 143);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{3}', 'aaa', 0, 3, 144);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{3}?', 'aaa', 0, 3, 145);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('a{3}?', 'aa', 146);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{3,3}?', 'aaa', 0, 3, 147);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('a{3,3}?', 'aa', 148);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{1,3}+', 'aaaaaa', 0, 3, 155);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{3}+', 'aaaaaa', 0, 3, 156);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('a{3,3}+', 'aaaaaa', 0, 3, 157);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).x2('', '', 0, 0, 164);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).x2('^', '', 0, 0, 165);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('^a', '\x0aa', 166);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('.', '\x0a', 167);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s:.)', '\x0a', 0, 1, 168);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s).', '\x0a', 0, 1, 169);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|.', '\x0a', 0, 1, 170);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?s:a)|.', '\x0a', 171);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('b(?s)a|.', '\x0a', 0, 1, 172);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('((?s)a)|.', '\x0a', 173);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('b(?:(?s)a)|z|.', '\x0a', 174);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('.|b(?s)a', '\x0a', 175);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('.(?s)', '\x0a', 176);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?s)(?-s)a|.', '\x0a', 177);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|.(?-s)', '\x0a', 0, 1, 178);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|((?-s)).', '\x0a', 0, 1, 179);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|(?:(?-s)).', '\x0a', 0, 1, 180);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|(?:).', '\x0a', 0, 1, 181);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|(?:.)', '\x0a', 0, 1, 182);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|(?:a*).', '\x0a', 0, 1, 183);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('a|(?:).', '\x0a', 184);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('a|(?:)(.)', '\x0a', 185);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?s)a|(?:)(.)', '\x0a', 0, 1, 186);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('b(?s)a|(?:)(.)', '\x0a', 0, 1, 187);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('b((?s)a)|(?:)(.)', '\x0a', 188);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?=a).b', 'ab', 0, 2, 195);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?=ab|(.))\\1', 'ab', 1, 2, 196);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?!(.)z)a\\1', 'aa', 197);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=a)b', 'ab', 1, 2, 204);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=a|b)c', 'abc', 2, 3, 205);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=a|(.))\\1', 'abcc', 3, 4, 206);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?<!RMA)X', '123RMAX', 209);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=RMA)X', '123RMAX', 6, 7, 210);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?<!RMA)\$', '123RMA', 211);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=RMA)\$', '123RMA', 6, 6, 212);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?<!RMA)\\Z', '123RMA', 213);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=RMA)\\Z', '123RMA', 6, 6, 214);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).n('(?<!RMA)\\z', '123RMA', 215);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('(?<=RMA)\\z', '123RMA', 6, 6, 216);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxJava).n('(?<!c|c)a', 'ca', 221);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w\\-%]', 'a', 0, 1, 228);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w\\-%]', '%', 0, 1, 229);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w\\-%]', '-', 0, 1, 230);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w-%]', 'a', 0, 1, 233);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w-%]', '%', 0, 1, 234);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxJava,
    ).x2('[\\w-%]', '-', 0, 1, 235);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('a{1,3}?', 'aaa', 0, 1, 143);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('a{3}', 'aaa', 0, 3, 144);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('a{3}?', 'aaa', 0, 3, 145);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPython).n('a{3}?', 'aa', 146);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('a{3,3}?', 'aaa', 0, 3, 147);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPython).n('a{3,3}?', 'aa', 148);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?a)\\w', 'a', 0, 1, 242);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('\\w', '\xe3\x81\x82', 0, 3, 243);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('(?a)\\w', '\xe3\x81\x82', 244);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('\\s', '\xe3\x80\x80', 0, 3, 245);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('(?a)\\s', '\xe3\x80\x80', 246);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('\\d', '\xef\xbc\x95', 0, 3, 247);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('(?a)\\d', '\xef\xbc\x95', 248);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('\xe3\x81\x82\\b ', '\xe3\x81\x82 ', 0, 4, 249);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('(?a)\xe3\x81\x82\\b ', '\xe3\x81\x82 ', 250);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('\xe3\x81\x82\\B ', '\xe3\x81\x82 ', 251);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?a)\xe3\x81\x82\\B ', '\xe3\x81\x82 ', 0, 4, 252);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?a)\\W', '\xe3\x81\x82', 0, 3, 253);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('\\W', '\xe3\x81\x82', 254);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?a)\\S', '\xe3\x80\x80', 0, 3, 255);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('\\S', '\xe3\x80\x80', 256);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?a)\\D', '\xef\xbc\x95', 0, 3, 257);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('\\D', '\xef\xbc\x95', 258);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('a\\Z', 'a', 0, 1, 265);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPython).n('a\\Z', 'a\x0a', 266);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).e('\\z', 'a', -213, 267);
    CSuite(enc: utf8Encoding, syntax: onigSyntaxPython).n('.', '\x0a', 274);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?s).', '\x0a', 0, 1, 275);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('^abc', '\x0aabc', 277);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?m)^abc', '\x0aabc', 1, 4, 278);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).n('abc\$', 'abc\x0adef', 279);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('abc\$', 'abc\x0a', 0, 3, 280);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPython,
    ).x2('(?m)abc\$', 'abc\x0adef', 0, 3, 281);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('a\\^b', 'a^b', 0, 3, 288);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('a^b', 'a^b', 0, 3, 289);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('a\\\$b', 'a\$b', 0, 3, 290);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('a\$b', 'a\$b', 0, 3, 291);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('^ab', 'ab', 0, 2, 293);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('(^ab)', '(^ab)', 0, 5, 294);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('\\(^ab\\)', 'ab', 0, 2, 295);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('\\\\(^ab\\\\)', '\\(^ab\\)', 0, 7, 296);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).n('\\\\\\(^ab\\\\\\)', '\\ab\\', 297);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('^\\\\\\(ab\\\\\\)', '\\ab\\', 0, 4, 298);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('ab\$', 'ab', 0, 2, 300);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('(ab\$)', '(ab\$)', 0, 5, 301);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('\\(ab\$\\)', 'ab', 0, 2, 302);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('\\\\(ab\$\\\\)', '\\(ab\$\\)', 0, 7, 303);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).n('\\\\\\(ab\$\\\\\\)', '\\ab\\', 304);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxPosixBasic,
    ).x2('\\\\\\(ab\\\\\\)\$', '\\ab\\', 0, 4, 305);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('a\\^b', 'a^b', 0, 3, 288);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('a^b', 'a^b', 0, 3, 289);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('a\\\$b', 'a\$b', 0, 3, 290);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('a\$b', 'a\$b', 0, 3, 291);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('^ab', 'ab', 0, 2, 293);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('(^ab)', '(^ab)', 0, 5, 294);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('\\(^ab\\)', 'ab', 0, 2, 295);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('\\\\(^ab\\\\)', '\\(^ab\\)', 0, 7, 296);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).n('\\\\\\(^ab\\\\\\)', '\\ab\\', 297);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('^\\\\\\(ab\\\\\\)', '\\ab\\', 0, 4, 298);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('ab\$', 'ab', 0, 2, 300);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('(ab\$)', '(ab\$)', 0, 5, 301);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('\\(ab\$\\)', 'ab', 0, 2, 302);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('\\\\(ab\$\\\\)', '\\(ab\$\\)', 0, 7, 303);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).n('\\\\\\(ab\$\\\\\\)', '\\ab\\', 304);
    CSuite(
      enc: utf8Encoding,
      syntax: onigSyntaxGrep,
    ).x2('\\\\\\(ab\\\\\\)\$', '\\ab\\', 0, 4, 305);
  });
}
