// GENERATED by tool/gen_c_suite.dart from oniguruma-master/test/testu.c.
// 1:1 translation of the Oniguruma C test cases. Do not edit.
import 'package:oniguruma_dart/oniguruma_dart.dart';
import 'c_harness.dart';

void main() {
  group('testu', () {
    CSuite(enc: utf16BeEncoding).x2('', '', 0, 0, 216);
    CSuite(enc: utf16BeEncoding).x2('\x00^', '', 0, 0, 217);
    CSuite(enc: utf16BeEncoding).x2('\x00\$', '', 0, 0, 218);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00G', '', 0, 0, 219);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00A', '', 0, 0, 220);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00Z', '', 0, 0, 221);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00z', '', 0, 0, 222);
    CSuite(enc: utf16BeEncoding).x2('\x00^\x00\$', '', 0, 0, 223);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00c\x00a', '\x00\x01', 0, 2, 224);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00C\x00-\x00b', '\x00\x02', 0, 2, 225);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00c\x00\\\x00\\', '\x00\x1c', 0, 2, 226);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00q\x00[\x00\\\x00c\x00\\\x00\\\x00]', '\x00q\x00\x1c', 0, 4, 227);
    CSuite(enc: utf16BeEncoding).x2('', '\x00a', 0, 0, 228);
    CSuite(enc: utf16BeEncoding).x2('\x00a', '\x00a', 0, 2, 229);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00x\x000\x000\x00\\\x00x\x006\x001', '\x00a', 0, 2, 230);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00a', '\x00a\x00a', 0, 4, 231);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00a\x00a', '\x00a\x00a\x00a', 0, 6, 232);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a',
      '\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a',
      0,
      70,
      233,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00b', '\x00a\x00b', 0, 4, 234);
    CSuite(enc: utf16BeEncoding).x2('\x00b', '\x00a\x00b', 2, 4, 235);
    CSuite(enc: utf16BeEncoding).x2('\x00b\x00c', '\x00a\x00b\x00c', 2, 6, 236);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00#\x00R\x00E\x00T\x00#\x00)',
      '\x00#\x00I\x00N\x00S\x00#\x00#\x00R\x00E\x00T\x00#',
      10,
      20,
      237,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x000\x000\x000\x00\\\x001\x007', '\x00\x0f', 0, 2, 238);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00x\x000\x000\x00\\\x00x\x001\x00f', '\x00\x1f', 0, 2, 239);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00(\x00?\x00#\x00.\x00.\x00.\x00.\x00\\\x00\\\x00J\x00J\x00J\x00J\x00)\x00b',
      '\x00a\x00b',
      0,
      4,
      240,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00x\x00)\x00 \x00 \x00G\x00 \x00(\x00o\x00 \x00O\x00(\x00?\x00-\x00x\x00)\x00o\x00O\x00)\x00 \x00g\x00 \x00L',
      '\x00G\x00o\x00O\x00o\x00O\x00g\x00L\x00e',
      0,
      14,
      241,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00.', '\x00a', 0, 2, 242);
    CSuite(enc: utf16BeEncoding).n('\x00.', '', 243);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00.', '\x00a\x00b', 0, 4, 244);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00w', '\x00e', 0, 2, 245);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00W', '\x00e', 246);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00s', '\x00 ', 0, 2, 247);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00S', '\x00b', 0, 2, 248);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00d', '\x004', 0, 2, 249);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00D', '\x004', 250);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00b', '\x00z\x00 ', 0, 0, 251);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00b', '\x00 \x00z', 2, 2, 252);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00B', '\x00z\x00z\x00 ', 2, 2, 253);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '\x00z\x00 ', 4, 4, 254);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '\x00 \x00z', 0, 0, 255);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00a\x00b\x00]', '\x00b', 0, 2, 256);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00a\x00b\x00]', '\x00c', 257);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00a\x00-\x00z\x00]', '\x00t', 0, 2, 258);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00^\x00a\x00]', '\x00a', 259);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00^\x00a\x00]', '\x00\x0a', 0, 2, 260);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00]\x00]', '\x00]', 0, 2, 261);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00^\x00]\x00]', '\x00]', 262);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00^\x00]\x00+', '\x000\x00^\x00^\x001', 2, 6, 263);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00b\x00-\x00]', '\x00b', 0, 2, 264);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00b\x00-\x00]', '\x00-', 0, 2, 265);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00w\x00]', '\x00z', 0, 2, 266);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00w\x00]', '\x00 ', 267);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00W\x00]', '\x00b\x00\$', 2, 4, 268);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00d\x00]', '\x005', 0, 2, 269);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00d\x00]', '\x00e', 270);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00D\x00]', '\x00t', 0, 2, 271);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00D\x00]', '\x003', 272);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00s\x00]', '\x00 ', 0, 2, 273);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00s\x00]', '\x00a', 274);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00S\x00]', '\x00b', 0, 2, 275);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00S\x00]', '\x00 ', 276);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00w\x00\\\x00d\x00]', '\x002', 0, 2, 277);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00\\\x00w\x00\\\x00d\x00]', '\x00 ', 278);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00:\x00u\x00p\x00p\x00e\x00r\x00:\x00]\x00]',
      '\x00B',
      0,
      2,
      279,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00*\x00[\x00:\x00x\x00d\x00i\x00g\x00i\x00t\x00:\x00]\x00+\x00]',
      '\x00+',
      0,
      2,
      280,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00*\x00[\x00:\x00x\x00d\x00i\x00g\x00i\x00t\x00:\x00]\x00+\x00]',
      '\x00G\x00H\x00I\x00K\x00K\x00-\x009\x00+\x00*',
      12,
      14,
      281,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00*\x00[\x00:\x00x\x00d\x00i\x00g\x00i\x00t\x00:\x00]\x00+\x00]',
      '\x00-\x00@\x00^\x00+',
      6,
      8,
      282,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[\x00:\x00u\x00p\x00p\x00e\x00r\x00]\x00]', '\x00A', 283);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00:\x00u\x00p\x00p\x00e\x00r\x00]\x00]',
      '\x00:',
      0,
      2,
      284,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00\\\x000\x000\x000\x00\\\x000\x004\x004\x00-\x00\\\x000\x000\x000\x00\\\x000\x004\x007\x00]',
      '\x00&',
      0,
      2,
      285,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00\\\x00x\x000\x000\x00\\\x00x\x005\x00a\x00-\x00\\\x00x\x000\x000\x00\\\x00x\x005\x00c\x00]',
      '\x00[',
      0,
      2,
      286,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00\\\x00x\x000\x000\x00\\\x00x\x006\x00A\x00-\x00\\\x00x\x000\x000\x00\\\x00x\x006\x00D\x00]',
      '\x00l',
      0,
      2,
      287,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00\\\x00x\x000\x000\x00\\\x00x\x006\x00A\x00-\x00\\\x00x\x000\x000\x00\\\x00x\x006\x00D\x00]',
      '\x00n',
      288,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00^\x00[\x000\x00-\x009\x00A\x00-\x00F\x00]\x00+\x00 \x000\x00+\x00 \x00U\x00N\x00D\x00E\x00F\x00 ',
      '\x007\x005\x00F\x00 \x000\x000\x000\x000\x000\x000\x000\x000\x00 \x00S\x00E\x00C\x00T\x001\x004\x00A\x00 \x00n\x00o\x00t\x00y\x00p\x00e\x00 \x00(\x00)\x00 \x00 \x00 \x00 \x00E\x00x\x00t\x00e\x00r\x00n\x00a\x00l\x00 \x00 \x00 \x00 \x00|\x00 \x00_\x00r\x00b\x00_\x00a\x00p\x00p\x00l\x00y',
      289,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00[\x00]', '\x00[', 0, 2, 290);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00]\x00]', '\x00]', 0, 2, 291);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00&\x00]', '\x00&', 0, 2, 292);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00[\x00a\x00b\x00]\x00]', '\x00b', 0, 2, 293);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00[\x00a\x00b\x00]\x00c\x00]', '\x00c', 0, 2, 294);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[\x00^\x00a\x00]\x00]', '\x00a', 295);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00^\x00[\x00a\x00]\x00]', '\x00a', 296);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00a\x00b\x00]\x00&\x00&\x00b\x00c\x00]',
      '\x00b',
      0,
      2,
      297,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[\x00a\x00b\x00]\x00&\x00&\x00b\x00c\x00]', '\x00a', 298);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[\x00a\x00b\x00]\x00&\x00&\x00b\x00c\x00]', '\x00c', 299);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00a\x00-\x00z\x00&\x00&\x00b\x00-\x00y\x00&\x00&\x00c\x00-\x00x\x00]',
      '\x00w',
      0,
      2,
      300,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00^\x00a\x00-\x00z\x00&\x00&\x00b\x00-\x00y\x00&\x00&\x00c\x00-\x00x\x00]',
      '\x00w',
      301,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00^\x00a\x00&\x00&\x00a\x00]\x00&\x00&\x00a\x00-\x00z\x00]',
      '\x00b',
      0,
      2,
      302,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00[\x00^\x00a\x00&\x00&\x00a\x00]\x00&\x00&\x00a\x00-\x00z\x00]',
      '\x00a',
      303,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00^\x00a\x00-\x00z\x00&\x00&\x00b\x00c\x00d\x00e\x00f\x00]\x00&\x00&\x00[\x00^\x00c\x00-\x00g\x00]\x00]',
      '\x00h',
      0,
      2,
      304,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00[\x00^\x00a\x00-\x00z\x00&\x00&\x00b\x00c\x00d\x00e\x00f\x00]\x00&\x00&\x00[\x00^\x00c\x00-\x00g\x00]\x00]',
      '\x00c',
      305,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^\x00a\x00b\x00c\x00]\x00&\x00&\x00[\x00^\x00c\x00d\x00e\x00]\x00]',
      '\x00c',
      0,
      2,
      306,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^\x00a\x00b\x00c\x00]\x00&\x00&\x00[\x00^\x00c\x00d\x00e\x00]\x00]',
      '\x00e',
      0,
      2,
      307,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00^\x00[\x00^\x00a\x00b\x00c\x00]\x00&\x00&\x00[\x00^\x00c\x00d\x00e\x00]\x00]',
      '\x00f',
      308,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00a\x00-\x00&\x00&\x00-\x00a\x00]', '\x00-', 0, 2, 309);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00a\x00\\\x00-\x00&\x00&\x00\\\x00-\x00a\x00]', '\x00&', 310);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00w\x00a\x00b\x00c', '\x00 \x00a\x00b\x00c', 311);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00\\\x00W\x00b\x00c', '\x00a\x00 \x00b\x00c', 0, 8, 312);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00.\x00b\x00.\x00c', '\x00a\x00a\x00b\x00b\x00c', 0, 10, 313);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00\\\x00w\x00b\x00\\\x00W\x00.\x00.\x00c',
      '\x00a\x00b\x00b\x00 \x00b\x00c\x00c',
      0,
      14,
      314,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00s\x00\\\x00w\x00z\x00z\x00z',
      '\x00 \x00z\x00z\x00z\x00z',
      0,
      10,
      315,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00a\x00.\x00b', '\x00a\x00a\x00b\x00b', 0, 8, 316);
    CSuite(enc: utf16BeEncoding).n('\x00.\x00a', '\x00a\x00b', 317);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00a', '\x00a\x00a', 0, 4, 318);
    CSuite(enc: utf16BeEncoding).x2('\x00^\x00a', '\x00a', 0, 2, 319);
    CSuite(enc: utf16BeEncoding).x2('\x00^\x00a\x00\$', '\x00a', 0, 2, 320);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00w\x00\$', '\x00a', 0, 2, 321);
    CSuite(enc: utf16BeEncoding).n('\x00^\x00\\\x00w\x00\$', '\x00 ', 322);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00w\x00a\x00b\x00\$', '\x00z\x00a\x00b', 0, 6, 323);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00\\\x00w\x00a\x00b\x00c\x00d\x00e\x00f\x00\$',
      '\x00z\x00a\x00b\x00c\x00d\x00e\x00f',
      0,
      14,
      324,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00\\\x00w\x00.\x00.\x00.\x00d\x00e\x00f\x00\$',
      '\x00z\x00a\x00b\x00c\x00d\x00e\x00f',
      0,
      14,
      325,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00w\x00\\\x00w\x00\\\x00s\x00\\\x00W\x00a\x00a\x00a\x00\\\x00d',
      '\x00a\x00a\x00 \x00 \x00a\x00a\x00a\x004',
      0,
      16,
      326,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00A\x00\\\x00Z', '', 0, 0, 327);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00A\x00x\x00y\x00z', '\x00x\x00y\x00z', 0, 6, 328);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00x\x00y\x00z\x00\\\x00Z', '\x00x\x00y\x00z', 0, 6, 329);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00x\x00y\x00z\x00\\\x00z', '\x00x\x00y\x00z', 0, 6, 330);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00\\\x00Z', '\x00a', 0, 2, 331);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00G\x00a\x00z', '\x00a\x00z', 0, 4, 332);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00G\x00z', '\x00b\x00z\x00a', 333);
    CSuite(enc: utf16BeEncoding).n('\x00a\x00z\x00\\\x00G', '\x00a\x00z', 334);
    CSuite(enc: utf16BeEncoding).n('\x00a\x00z\x00\\\x00A', '\x00a\x00z', 335);
    CSuite(enc: utf16BeEncoding).n('\x00a\x00\\\x00A\x00z', '\x00a\x00z', 336);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00^\x00\\\x00\$', '\x00^\x00\$', 0, 4, 337);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00x\x00?\x00y', '\x00x\x00y', 0, 4, 338);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00(\x00x\x00?\x00y\x00)', '\x00x\x00y', 0, 4, 339);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00w', '\x00_', 0, 2, 340);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00W', '\x00_', 341);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00=\x00z\x00)\x00z', '\x00z', 0, 2, 342);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00=\x00z\x00)\x00.', '\x00a', 343);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00!\x00z\x00)\x00a', '\x00a', 0, 2, 344);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00!\x00z\x00)\x00a', '\x00z', 345);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00a\x00)', '\x00a', 0, 2, 346);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00a\x00)', '\x00A', 0, 2, 347);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00A\x00)', '\x00a', 0, 2, 348);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00i\x00:\x00A\x00)', '\x00b', 349);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00A\x00-\x00Z\x00]\x00)',
      '\x00a',
      0,
      2,
      350,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00f\x00-\x00m\x00]\x00)',
      '\x00H',
      0,
      2,
      351,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00f\x00-\x00m\x00]\x00)',
      '\x00h',
      0,
      2,
      352,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00i\x00:\x00[\x00f\x00-\x00m\x00]\x00)', '\x00e', 353);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00A\x00-\x00c\x00]\x00)',
      '\x00D',
      0,
      2,
      354,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00i\x00:\x00[\x00^\x00a\x00-\x00z\x00]\x00)',
      '\x00A',
      355,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00i\x00:\x00[\x00^\x00a\x00-\x00z\x00]\x00)',
      '\x00a',
      356,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00!\x00-\x00k\x00]\x00)',
      '\x00Z',
      0,
      2,
      357,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00!\x00-\x00k\x00]\x00)',
      '\x007',
      0,
      2,
      358,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00T\x00-\x00}\x00]\x00)',
      '\x00b',
      0,
      2,
      359,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00i\x00:\x00[\x00T\x00-\x00}\x00]\x00)',
      '\x00{',
      0,
      2,
      360,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00\\\x00?\x00a\x00)', '\x00?\x00A', 0, 4, 361);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00\\\x00*\x00A\x00)', '\x00*\x00a', 0, 4, 362);
    CSuite(enc: utf16BeEncoding).n('\x00.', '\x00\x0a', 363);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00m\x00:\x00.\x00)', '\x00\x0a', 0, 2, 364);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00m\x00:\x00a\x00.\x00)', '\x00a\x00\x0a', 0, 4, 365);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00m\x00:\x00.\x00b\x00)',
      '\x00a\x00\x0a\x00b',
      2,
      6,
      366,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00*\x00a\x00b\x00c',
      '\x00d\x00d\x00d\x00a\x00b\x00d\x00d\x00\x0a\x00d\x00d\x00a\x00b\x00c',
      16,
      26,
      367,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00m\x00:\x00.\x00*\x00a\x00b\x00c\x00)',
      '\x00d\x00d\x00d\x00a\x00b\x00d\x00d\x00a\x00b\x00c',
      0,
      20,
      368,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00i\x00)\x00(\x00?\x00-\x00i\x00)\x00a', '\x00A', 369);
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00i\x00)\x00(\x00?\x00-\x00i\x00:\x00a\x00)',
      '\x00A',
      370,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?', '', 0, 0, 371);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?', '\x00b', 0, 0, 372);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?', '\x00a', 0, 2, 373);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00*', '', 0, 0, 374);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00*', '\x00a', 0, 2, 375);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00*', '\x00a\x00a\x00a', 0, 6, 376);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00*', '\x00b\x00a\x00a\x00a\x00a', 0, 0, 377);
    CSuite(enc: utf16BeEncoding).n('\x00a\x00+', '', 378);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00+', '\x00a', 0, 2, 379);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+', '\x00a\x00a\x00a\x00a', 0, 8, 380);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+', '\x00a\x00a\x00b\x00b\x00b', 0, 4, 381);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+', '\x00b\x00a\x00a\x00a\x00a', 2, 10, 382);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00?', '', 0, 0, 383);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00?', '\x00f', 0, 2, 384);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00?', '\x00\x0a', 0, 0, 385);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00*', '', 0, 0, 386);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00*', '\x00a\x00b\x00c\x00d\x00e', 0, 10, 387);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00+', '\x00z', 0, 2, 388);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00+', '\x00z\x00d\x00s\x00w\x00e\x00r\x00\x0a', 0, 12, 389);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00.\x00*\x00)\x00a\x00\\\x001\x00f',
      '\x00b\x00a\x00b\x00f\x00b\x00a\x00c',
      0,
      8,
      390,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00.\x00*\x00)\x00a\x00\\\x001\x00f',
      '\x00b\x00a\x00c\x00b\x00a\x00b\x00f',
      6,
      14,
      391,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00.\x00*\x00)\x00a\x00\\\x002\x00f\x00)',
      '\x00b\x00a\x00c\x00b\x00a\x00b\x00f',
      6,
      14,
      392,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00.\x00*\x00)\x00a\x00\\\x001\x00f',
      '\x00b\x00a\x00c\x00z\x00z\x00z\x00z\x00z\x00z\x00\x0a\x00b\x00a\x00z\x00z\x00\x0a\x00z\x00z\x00z\x00z\x00b\x00a\x00b\x00f',
      38,
      46,
      393,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00|\x00b', '\x00a', 0, 2, 394);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00|\x00b', '\x00b', 0, 2, 395);
    CSuite(enc: utf16BeEncoding).x2('\x00|\x00a', '\x00a', 0, 0, 396);
    CSuite(enc: utf16BeEncoding).x2('\x00(\x00|\x00a\x00)', '\x00a', 0, 0, 397);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00b\x00|\x00b\x00c', '\x00a\x00b', 0, 4, 398);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00b\x00|\x00b\x00c', '\x00b\x00c', 0, 4, 399);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00z\x00(\x00?\x00:\x00a\x00b\x00|\x00b\x00c\x00)',
      '\x00z\x00b\x00c',
      0,
      6,
      400,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00(\x00?\x00:\x00a\x00b\x00|\x00b\x00c\x00)\x00c',
      '\x00a\x00a\x00b\x00c',
      0,
      8,
      401,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00b\x00|\x00(\x00?\x00:\x00a\x00c\x00|\x00a\x00z\x00)',
      '\x00a\x00z',
      0,
      4,
      402,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00b\x00|\x00c', '\x00d\x00c', 2, 4, 403);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00|\x00b\x00|\x00c\x00d\x00|\x00e\x00f\x00g\x00|\x00h\x00|\x00i\x00j\x00k\x00|\x00l\x00m\x00n\x00|\x00o\x00|\x00p\x00q\x00|\x00r\x00s\x00t\x00u\x00v\x00w\x00x\x00|\x00y\x00z',
      '\x00p\x00q\x00r',
      0,
      4,
      404,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00a\x00|\x00b\x00|\x00c\x00d\x00|\x00e\x00f\x00g\x00|\x00h\x00|\x00i\x00j\x00k\x00|\x00l\x00m\x00n\x00|\x00o\x00|\x00p\x00q\x00|\x00r\x00s\x00t\x00u\x00v\x00w\x00x\x00|\x00y\x00z',
      '\x00m\x00n',
      405,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00^\x00z', '\x00b\x00a', 2, 4, 406);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00^\x00z', '\x00z\x00a', 0, 2, 407);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00\\\x00G\x00z', '\x00b\x00z\x00a', 4, 6, 408);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00\\\x00G\x00z', '\x00z\x00a', 0, 2, 409);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00\\\x00A\x00z', '\x00b\x00z\x00a', 4, 6, 410);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00\\\x00A\x00z', '\x00z\x00a', 0, 2, 411);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00b\x00\\\x00Z', '\x00b\x00a', 2, 4, 412);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00b\x00\\\x00Z', '\x00b', 0, 2, 413);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00b\x00\\\x00z', '\x00b\x00a', 2, 4, 414);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00b\x00\\\x00z', '\x00b', 0, 2, 415);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00\\\x00s', '\x00 ', 0, 2, 416);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00w\x00|\x00\\\x00w', '\x00 ', 417);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00%', '\x00%', 0, 2, 418);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00[\x00&\x00\$\x00]', '\x00&', 0, 2, 419);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00b\x00-\x00d\x00]\x00|\x00[\x00^\x00e\x00-\x00z\x00]',
      '\x00a',
      0,
      2,
      420,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00|\x00[\x00c\x00-\x00f\x00]\x00)\x00|\x00b\x00z',
      '\x00d\x00z',
      0,
      2,
      421,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00|\x00[\x00c\x00-\x00f\x00]\x00)\x00|\x00b\x00z',
      '\x00b\x00z',
      0,
      4,
      422,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00b\x00c\x00|\x00(\x00?\x00=\x00z\x00z\x00)\x00.\x00.\x00f',
      '\x00z\x00z\x00f',
      0,
      6,
      423,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00b\x00c\x00|\x00(\x00?\x00!\x00z\x00z\x00)\x00.\x00.\x00f',
      '\x00a\x00b\x00f',
      0,
      6,
      424,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00=\x00z\x00a\x00)\x00.\x00.\x00a\x00|\x00(\x00?\x00=\x00z\x00z\x00)\x00.\x00.\x00a',
      '\x00z\x00z\x00a',
      0,
      6,
      425,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00>\x00a\x00|\x00a\x00b\x00d\x00)\x00c',
      '\x00a\x00b\x00d\x00c',
      426,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00>\x00a\x00b\x00d\x00|\x00a\x00)\x00c',
      '\x00a\x00b\x00d\x00c',
      0,
      8,
      427,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?\x00|\x00b', '\x00a', 0, 2, 428);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?\x00|\x00b', '\x00b', 0, 0, 429);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00?\x00|\x00b', '', 0, 0, 430);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00*\x00|\x00b', '\x00a\x00a', 0, 4, 431);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00*\x00|\x00b\x00*', '\x00b\x00a', 0, 0, 432);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00*\x00|\x00b\x00*', '\x00a\x00b', 0, 2, 433);
    CSuite(enc: utf16BeEncoding).x2('\x00a\x00+\x00|\x00b\x00*', '', 0, 0, 434);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+\x00|\x00b\x00*', '\x00b\x00b\x00b', 0, 6, 435);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+\x00|\x00b\x00*', '\x00a\x00b\x00b\x00b', 0, 2, 436);
    CSuite(enc: utf16BeEncoding).n('\x00a\x00+\x00|\x00b\x00+', '', 437);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00|\x00b\x00)\x00?', '\x00b', 0, 2, 438);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00|\x00b\x00)\x00*', '\x00b\x00a', 0, 4, 439);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00|\x00b\x00)\x00+', '\x00b\x00a\x00b', 0, 6, 440);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00b\x00|\x00c\x00a\x00)\x00+',
      '\x00c\x00a\x00a\x00b\x00b\x00c',
      0,
      8,
      441,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00b\x00|\x00c\x00a\x00)\x00+',
      '\x00a\x00a\x00b\x00c\x00a',
      2,
      10,
      442,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00b\x00|\x00c\x00a\x00)\x00+',
      '\x00a\x00b\x00z\x00c\x00a',
      0,
      4,
      443,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00|\x00b\x00a\x00b\x00)\x00+',
      '\x00a\x00b\x00a\x00b\x00a',
      0,
      10,
      444,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00|\x00b\x00a\x00b\x00)\x00+', '\x00b\x00a', 2, 4, 445);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00|\x00b\x00a\x00b\x00)\x00+',
      '\x00b\x00a\x00a\x00a\x00b\x00a',
      2,
      8,
      446,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00|\x00b\x00)\x00(\x00?\x00:\x00a\x00|\x00b\x00)',
      '\x00a\x00b',
      0,
      4,
      447,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00*\x00|\x00b\x00*\x00)\x00(\x00?\x00:\x00a\x00*\x00|\x00b\x00*\x00)',
      '\x00a\x00a\x00a\x00b\x00b\x00b',
      0,
      6,
      448,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00*\x00|\x00b\x00*\x00)\x00(\x00?\x00:\x00a\x00+\x00|\x00b\x00+\x00)',
      '\x00a\x00a\x00a\x00b\x00b\x00b',
      0,
      12,
      449,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00+\x00|\x00b\x00+\x00)\x00{\x002\x00}',
      '\x00a\x00a\x00a\x00b\x00b\x00b',
      0,
      12,
      450,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00h\x00{\x000\x00,\x00}', '\x00h\x00h\x00h\x00h', 0, 8, 451);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00+\x00|\x00b\x00+\x00)\x00{\x001\x00,\x002\x00}',
      '\x00a\x00a\x00a\x00b\x00b\x00b',
      0,
      12,
      452,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00a\x00x\x00{\x002\x00}\x00*\x00a',
      '\x000\x00a\x00x\x00x\x00x\x00a\x001',
      453,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00a\x00.\x00{\x000\x00,\x002\x00}\x00a',
      '\x000\x00a\x00X\x00X\x00X\x00a\x000',
      454,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00a\x00.\x00{\x000\x00,\x002\x00}\x00?\x00a',
      '\x000\x00a\x00X\x00X\x00X\x00a\x000',
      455,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00a\x00.\x00{\x000\x00,\x002\x00}\x00?\x00a',
      '\x000\x00a\x00X\x00X\x00X\x00X\x00a\x000',
      456,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00a\x00{\x002\x00,\x00}\x00?\x00a\x00\$',
      '\x00a\x00a\x00a',
      0,
      6,
      457,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00[\x00a\x00-\x00z\x00]\x00{\x002\x00,\x00}\x00?\x00\$',
      '\x00a\x00a\x00a',
      0,
      6,
      458,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00+\x00|\x00\\\x00A\x00b\x00*\x00)\x00c\x00c',
      '\x00c\x00c',
      0,
      4,
      459,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:\x00a\x00+\x00|\x00\\\x00A\x00b\x00*\x00)\x00c\x00c',
      '\x00a\x00b\x00c\x00c',
      460,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00^\x00a\x00+\x00|\x00b\x00+\x00)\x00*\x00c',
      '\x00a\x00a\x00b\x00b\x00b\x00a\x00b\x00c',
      12,
      16,
      461,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00^\x00a\x00+\x00|\x00b\x00+\x00)\x00*\x00c',
      '\x00a\x00a\x00b\x00b\x00b\x00b\x00c',
      0,
      14,
      462,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00|\x00(\x00?\x00i\x00)\x00c', '\x00C', 0, 2, 463);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00)\x00c\x00|\x00a', '\x00C', 0, 2, 464);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00)\x00c\x00|\x00a', '\x00A', 0, 2, 465);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:\x00c\x00)\x00|\x00a', '\x00C', 0, 2, 466);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00i\x00:\x00c\x00)\x00|\x00a', '\x00A', 467);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00a\x00b\x00c\x00]\x00?', '\x00a\x00b\x00c', 0, 2, 468);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00a\x00b\x00c\x00]\x00*', '\x00a\x00b\x00c', 0, 6, 469);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00^\x00a\x00b\x00c\x00]\x00*', '\x00a\x00b\x00c', 0, 0, 470);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00^\x00a\x00b\x00c\x00]\x00+', '\x00a\x00b\x00c', 471);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00?\x00?', '\x00a\x00a\x00a', 0, 0, 472);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00b\x00a\x00?\x00?\x00b', '\x00b\x00a\x00b', 0, 6, 473);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00*\x00?', '\x00a\x00a\x00a', 0, 0, 474);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00b\x00a\x00*\x00?', '\x00b\x00a\x00a', 0, 2, 475);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00b\x00a\x00*\x00?\x00b', '\x00b\x00a\x00a\x00b', 0, 8, 476);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00+\x00?', '\x00a\x00a\x00a', 0, 2, 477);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00b\x00a\x00+\x00?', '\x00b\x00a\x00a', 0, 4, 478);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00b\x00a\x00+\x00?\x00b', '\x00b\x00a\x00a\x00b', 0, 8, 479);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:\x00a\x00?\x00)\x00?\x00?', '\x00a', 0, 0, 480);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:\x00a\x00?\x00?\x00)\x00?', '\x00a', 0, 0, 481);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00?\x00)\x00+\x00?',
      '\x00a\x00a\x00a',
      0,
      2,
      482,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00+\x00)\x00?\x00?',
      '\x00a\x00a\x00a',
      0,
      0,
      483,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00+\x00)\x00?\x00?\x00b',
      '\x00a\x00a\x00a\x00b',
      0,
      8,
      484,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:\x00a\x00b\x00)\x00?\x00{\x002\x00}', '', 0, 0, 485);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00?\x00{\x002\x00}',
      '\x00a\x00b\x00a\x00b\x00a',
      0,
      8,
      486,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00*\x00{\x000\x00}',
      '\x00a\x00b\x00a\x00b\x00a',
      0,
      0,
      487,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x003\x00,\x00}',
      '\x00a\x00b\x00a\x00b\x00a\x00b\x00a\x00b',
      0,
      16,
      488,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x003\x00,\x00}',
      '\x00a\x00b\x00a\x00b',
      489,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x002\x00,\x004\x00}',
      '\x00a\x00b\x00a\x00b\x00a\x00b',
      0,
      12,
      490,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x002\x00,\x004\x00}',
      '\x00a\x00b\x00a\x00b\x00a\x00b\x00a\x00b\x00a\x00b',
      0,
      16,
      491,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x002\x00,\x004\x00}\x00?',
      '\x00a\x00b\x00a\x00b\x00a\x00b\x00a\x00b\x00a\x00b',
      0,
      8,
      492,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00)\x00{\x00,\x00}',
      '\x00a\x00b\x00{\x00,\x00}',
      0,
      10,
      493,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00c\x00)\x00+\x00?\x00{\x002\x00}',
      '\x00a\x00b\x00c\x00a\x00b\x00c\x00a\x00b\x00c',
      0,
      12,
      494,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00X\x00*\x00)\x00(\x00?\x00i\x00:\x00x\x00a\x00)',
      '\x00X\x00X\x00X\x00a',
      0,
      8,
      495,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00d\x00+\x00)\x00(\x00[\x00^\x00a\x00b\x00c\x00]\x00z\x00)',
      '\x00d\x00d\x00d\x00z',
      0,
      8,
      496,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00[\x00^\x00a\x00b\x00c\x00]\x00*\x00)\x00(\x00[\x00^\x00a\x00b\x00c\x00]\x00z\x00)',
      '\x00d\x00d\x00d\x00z',
      0,
      8,
      497,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00\\\x00w\x00+\x00)\x00(\x00\\\x00w\x00z\x00)',
      '\x00d\x00d\x00d\x00z',
      0,
      8,
      498,
    );
    CSuite(enc: utf16BeEncoding).x3('\x00(\x00a\x00)', '\x00a', 0, 2, 1, 499);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00b\x00)', '\x00a\x00b', 0, 4, 1, 500);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00(\x00a\x00b\x00)\x00)', '\x00a\x00b', 0, 4, 501);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(\x00a\x00b\x00)\x00)', '\x00a\x00b', 0, 4, 1, 502);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(\x00a\x00b\x00)\x00)', '\x00a\x00b', 0, 4, 2, 503);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00a\x00b\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)',
      '\x00a\x00b',
      0,
      4,
      20,
      504,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00b\x00)\x00(\x00c\x00d\x00)',
      '\x00a\x00b\x00c\x00d',
      0,
      4,
      1,
      505,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00b\x00)\x00(\x00c\x00d\x00)',
      '\x00a\x00b\x00c\x00d',
      4,
      8,
      2,
      506,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00)\x00(\x00a\x00)\x00b\x00c\x00(\x00d\x00e\x00f\x00)\x00g\x00h\x00i\x00j\x00k',
      '\x00a\x00b\x00c\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00k',
      6,
      12,
      3,
      507,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00)\x00(\x00a\x00)\x00b\x00c\x00(\x00d\x00e\x00f\x00)\x00g\x00h\x00i\x00j\x00k\x00)',
      '\x00a\x00b\x00c\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00k',
      6,
      12,
      4,
      508,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00(\x00^\x00a\x00)', '\x00a', 0, 2, 509);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00)\x00|\x00(\x00a\x00)', '\x00b\x00a', 2, 4, 1, 510);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00^\x00a\x00)\x00|\x00(\x00a\x00)',
      '\x00b\x00a',
      2,
      4,
      2,
      511,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00?\x00)', '\x00a\x00a\x00a', 0, 2, 1, 512);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00*\x00)', '\x00a\x00a\x00a', 0, 6, 1, 513);
    CSuite(enc: utf16BeEncoding).x3('\x00(\x00a\x00*\x00)', '', 0, 0, 1, 514);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00+\x00)',
      '\x00a\x00a\x00a\x00a\x00a\x00a\x00a',
      0,
      14,
      1,
      515,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00+\x00|\x00b\x00*\x00)',
      '\x00b\x00b\x00b\x00a\x00a',
      0,
      6,
      1,
      516,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00+\x00|\x00b\x00?\x00)',
      '\x00b\x00b\x00b\x00a\x00a',
      0,
      2,
      1,
      517,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00b\x00c\x00)\x00?', '\x00a\x00b\x00c', 0, 6, 1, 518);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00b\x00c\x00)\x00*', '\x00a\x00b\x00c', 0, 6, 1, 519);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00a\x00b\x00c\x00)\x00+', '\x00a\x00b\x00c', 0, 6, 1, 520);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00x\x00y\x00z\x00|\x00a\x00b\x00c\x00)\x00+',
      '\x00a\x00b\x00c',
      0,
      6,
      1,
      521,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00[\x00x\x00y\x00z\x00]\x00[\x00a\x00b\x00c\x00]\x00|\x00a\x00b\x00c\x00)\x00+',
      '\x00a\x00b\x00c',
      0,
      6,
      1,
      522,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00?\x00i\x00:\x00a\x00b\x00c\x00)\x00)',
      '\x00A\x00b\x00C',
      0,
      6,
      1,
      523,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00b\x00c\x00)\x00(\x00?\x00i\x00:\x00\\\x001\x00)',
      '\x00a\x00b\x00c\x00A\x00B\x00C',
      0,
      12,
      524,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00?\x00m\x00:\x00a\x00.\x00c\x00)\x00)',
      '\x00a\x00\x0a\x00c',
      0,
      6,
      1,
      525,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00?\x00=\x00a\x00z\x00)\x00a\x00)',
      '\x00a\x00z\x00b',
      0,
      2,
      1,
      526,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00a\x00b\x00c\x00|\x00(\x00.\x00a\x00b\x00d\x00)',
      '\x00z\x00a\x00b\x00d',
      0,
      8,
      1,
      527,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00a\x00b\x00c\x00)\x00|\x00(\x00A\x00B\x00C\x00)',
      '\x00a\x00b\x00c',
      0,
      6,
      528,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00?\x00i\x00:\x00(\x00a\x00b\x00c\x00)\x00)\x00|\x00(\x00z\x00z\x00z\x00)',
      '\x00A\x00B\x00C',
      0,
      6,
      1,
      529,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00a\x00*\x00(\x00.\x00)',
      '\x00a\x00a\x00a\x00a\x00z',
      8,
      10,
      1,
      530,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00a\x00*\x00?\x00(\x00.\x00)',
      '\x00a\x00a\x00a\x00a\x00z',
      0,
      2,
      1,
      531,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00a\x00*\x00?\x00(\x00c\x00)',
      '\x00a\x00a\x00a\x00a\x00c',
      8,
      10,
      1,
      532,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00[\x00b\x00c\x00d\x00]\x00a\x00*\x00(\x00.\x00)',
      '\x00c\x00a\x00a\x00a\x00a\x00z',
      10,
      12,
      1,
      533,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00\\\x00A\x00b\x00b\x00)\x00c\x00c',
      '\x00b\x00b\x00c\x00c',
      0,
      4,
      1,
      534,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00\\\x00A\x00b\x00b\x00)\x00c\x00c',
      '\x00z\x00b\x00b\x00c\x00c',
      535,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00^\x00b\x00b\x00)\x00c\x00c',
      '\x00b\x00b\x00c\x00c',
      0,
      4,
      1,
      536,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00^\x00b\x00b\x00)\x00c\x00c',
      '\x00z\x00b\x00b\x00c\x00c',
      537,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00c\x00c\x00(\x00b\x00b\x00\$\x00)',
      '\x00c\x00c\x00b\x00b',
      4,
      8,
      1,
      538,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00c\x00c\x00(\x00b\x00b\x00\$\x00)',
      '\x00c\x00c\x00b\x00b\x00b',
      539,
    );
    CSuite(enc: utf16BeEncoding).n('\x00(\x00\\\x001\x00)', '', 540);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x001\x00(\x00a\x00)', '\x00a\x00a', 541);
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00a\x00(\x00b\x00)\x00\\\x001\x00)\x00\\\x002\x00+',
      '\x00a\x00b\x00a\x00b\x00b',
      542,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:\x00(\x00?\x00:\x00\\\x001\x00|\x00z\x00)\x00(\x00a\x00)\x00)\x00+\x00\$',
      '\x00z\x00a\x00a',
      543,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00?\x00:\x00\\\x001\x00|\x00z\x00)\x00(\x00a\x00)\x00)\x00+\x00\$',
      '\x00z\x00a\x00a\x00a',
      0,
      8,
      544,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00)\x00(\x00?\x00=\x00\\\x001\x00)',
      '\x00a\x00a',
      0,
      2,
      545,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00a\x00)\x00\$\x00|\x00\\\x001', '\x00a\x00z', 546);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00)\x00\\\x001', '\x00a\x00a', 0, 4, 547);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00a\x00)\x00\\\x001', '\x00a\x00b', 548);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00?\x00)\x00\\\x001', '\x00a\x00a', 0, 4, 549);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00?\x00?\x00)\x00\\\x001', '\x00a\x00a', 0, 0, 550);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00*\x00)\x00\\\x001',
      '\x00a\x00a\x00a\x00a\x00a',
      0,
      8,
      551,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00a\x00*\x00)\x00\\\x001',
      '\x00a\x00a\x00a\x00a\x00a',
      0,
      4,
      1,
      552,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00(\x00b\x00*\x00)\x00\\\x001',
      '\x00a\x00b\x00b\x00b\x00b',
      0,
      10,
      553,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00a\x00(\x00b\x00*\x00)\x00\\\x001', '\x00a\x00b', 0, 2, 554);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00*\x00)\x00(\x00b\x00*\x00)\x00\\\x001\x00\\\x002',
      '\x00a\x00a\x00a\x00b\x00b\x00a\x00a\x00a\x00b\x00b',
      0,
      20,
      555,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00*\x00)\x00(\x00b\x00*\x00)\x00\\\x002',
      '\x00a\x00a\x00a\x00b\x00b\x00b\x00b',
      0,
      14,
      556,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00a\x00*\x00)\x00b\x00)\x00)\x00)\x00)\x00)\x00)\x00c\x00\\\x007',
      '\x00a\x00a\x00a\x00b\x00c\x00a\x00a\x00a',
      0,
      16,
      557,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00a\x00*\x00)\x00b\x00)\x00)\x00)\x00)\x00)\x00)\x00c\x00\\\x007',
      '\x00a\x00a\x00a\x00b\x00c\x00a\x00a\x00a',
      0,
      6,
      7,
      558,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00a\x00)\x00(\x00b\x00)\x00(\x00c\x00)\x00\\\x002\x00\\\x001\x00\\\x003',
      '\x00a\x00b\x00c\x00b\x00a\x00c',
      0,
      12,
      559,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00[\x00a\x00-\x00d\x00]\x00)\x00\\\x001',
      '\x00c\x00c',
      0,
      4,
      560,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00\\\x00w\x00\\\x00d\x00\\\x00s\x00)\x00\\\x001',
      '\x00f\x005\x00 \x00f\x005\x00 ',
      0,
      12,
      561,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00\\\x00w\x00\\\x00d\x00\\\x00s\x00)\x00\\\x001',
      '\x00f\x005\x00 \x00f\x005',
      562,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00w\x00h\x00o\x00|\x00[\x00a\x00-\x00c\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '\x00w\x00h\x00o\x00w\x00h\x00o',
      0,
      12,
      563,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00.\x00.\x00(\x00w\x00h\x00o\x00|\x00[\x00a\x00-\x00c\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '\x00a\x00b\x00c\x00w\x00h\x00o\x00w\x00h\x00o',
      0,
      18,
      564,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00w\x00h\x00o\x00|\x00[\x00a\x00-\x00c\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '\x00c\x00b\x00c\x00c\x00b\x00c',
      0,
      12,
      565,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00^\x00a\x00)\x00\\\x001', '\x00a\x00a', 0, 4, 566);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00^\x00a\x00)\x00\\\x001', '\x00b\x00a\x00a', 567);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00a\x00\$\x00)\x00\\\x001', '\x00a\x00a', 568);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00a\x00b\x00\\\x00Z\x00)\x00\\\x001', '\x00a\x00b', 569);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00*\x00\\\x00Z\x00)\x00\\\x001', '\x00a', 2, 2, 570);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00(\x00a\x00*\x00\\\x00Z\x00)\x00\\\x001',
      '\x00b\x00a',
      2,
      4,
      571,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00.\x00(\x00a\x00b\x00c\x00)\x00\\\x002\x00)',
      '\x00z\x00a\x00b\x00c\x00a\x00b\x00c',
      0,
      14,
      1,
      572,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00.\x00(\x00.\x00.\x00\\\x00d\x00.\x00)\x00\\\x002\x00)',
      '\x00z\x001\x002\x003\x004\x001\x002\x003\x004',
      0,
      18,
      1,
      573,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00?\x00i\x00:\x00a\x00z\x00)\x00)\x00\\\x001',
      '\x00A\x00z\x00A\x00z',
      0,
      8,
      574,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00(\x00?\x00i\x00:\x00a\x00z\x00)\x00)\x00\\\x001',
      '\x00A\x00z\x00a\x00z',
      575,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00<\x00=\x00a\x00)\x00b', '\x00a\x00b', 2, 4, 576);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00<\x00=\x00a\x00)\x00b', '\x00b\x00b', 577);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00=\x00a\x00|\x00b\x00)\x00b',
      '\x00b\x00b',
      2,
      4,
      578,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00=\x00a\x00|\x00b\x00c\x00)\x00b',
      '\x00b\x00c\x00b',
      4,
      6,
      579,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00=\x00a\x00|\x00b\x00c\x00)\x00b',
      '\x00a\x00b',
      2,
      4,
      580,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00=\x00a\x00|\x00b\x00c\x00|\x00|\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00|\x00k\x00l\x00m\x00n\x00o\x00p\x00q\x00|\x00r\x00)\x00z',
      '\x00r\x00z',
      2,
      4,
      581,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00a\x00)\x00\\\x00g\x00<\x001\x00>', '\x00a\x00a', 0, 4, 582);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00<\x00!\x00a\x00)\x00b', '\x00c\x00b', 2, 4, 583);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00<\x00!\x00a\x00)\x00b', '\x00a\x00b', 584);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00!\x00a\x00|\x00b\x00c\x00)\x00b',
      '\x00b\x00b\x00b',
      0,
      2,
      585,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00<\x00!\x00a\x00|\x00b\x00c\x00)\x00z',
      '\x00b\x00c\x00z',
      586,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x00>\x00a\x00)',
      '\x00a',
      0,
      2,
      587,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x00_\x002\x00>\x00a\x00b\x00)\x00\\\x00g\x00<\x00n\x00a\x00m\x00e\x00_\x002\x00>',
      '\x00a\x00b\x00a\x00b',
      0,
      8,
      588,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x00_\x003\x00>\x00.\x00z\x00v\x00.\x00)\x00\\\x00k\x00<\x00n\x00a\x00m\x00e\x00_\x003\x00>',
      '\x00a\x00z\x00v\x00b\x00a\x00z\x00v\x00b',
      0,
      16,
      589,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00=\x00\\\x00g\x00<\x00a\x00b\x00>\x00)\x00|\x00-\x00\\\x00z\x00E\x00N\x00D\x00 \x00(\x00?\x00<\x00a\x00b\x00>\x00X\x00y\x00Z\x00)',
      '\x00X\x00y\x00Z',
      6,
      6,
      590,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00>\x00|\x00a\x00\\\x00g\x00<\x00n\x00>\x00)\x00+',
      '',
      0,
      0,
      591,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00>\x00|\x00\\\x00(\x00\\\x00g\x00<\x00n\x00>\x00\\\x00)\x00)\x00+\x00\$',
      '\x00(\x00)\x00(\x00(\x00)\x00)',
      0,
      12,
      592,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00\\\x00g\x00<\x00n\x00>\x00(\x00?\x00<\x00n\x00>\x00.\x00)\x00{\x000\x00}',
      '\x00X',
      0,
      2,
      1,
      593,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00g\x00<\x00n\x00>\x00(\x00a\x00b\x00c\x00|\x00d\x00f\x00(\x00?\x00<\x00n\x00>\x00.\x00Y\x00Z\x00)\x00{\x002\x00,\x008\x00}\x00)\x00{\x000\x00}',
      '\x00X\x00Y\x00Z',
      0,
      6,
      594,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00A\x00(\x00?\x00<\x00n\x00>\x00(\x00a\x00\\\x00g\x00<\x00n\x00>\x00)\x00|\x00)\x00\\\x00z',
      '\x00a\x00a\x00a\x00a',
      0,
      8,
      595,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00>\x00|\x00\\\x00g\x00<\x00m\x00>\x00\\\x00g\x00<\x00n\x00>\x00)\x00\\\x00z\x00|\x00\\\x00z\x00E\x00N\x00D\x00 \x00(\x00?\x00<\x00m\x00>\x00a\x00|\x00(\x00b\x00)\x00\\\x00g\x00<\x00m\x00>\x00)',
      '\x00b\x00b\x00b\x00b\x00a\x00b\x00b\x00a',
      0,
      16,
      596,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x002\x004\x000\x00>\x00\\\x00w\x00+\x00\\\x00s\x00x\x00)\x00a\x00+\x00\\\x00k\x00<\x00n\x00a\x00m\x00e\x001\x002\x004\x000\x00>',
      '\x00 \x00 \x00f\x00g\x00 \x00x\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00a\x00f\x00g\x00 \x00x',
      4,
      36,
      597,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00z\x00)\x00(\x00)\x00(\x00)\x00(\x00?\x00<\x00_\x009\x00>\x00a\x00)\x00\\\x00g\x00<\x00_\x009\x00>',
      '\x00z\x00a\x00a',
      4,
      6,
      1,
      598,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00.\x00)\x00(\x00(\x00(\x00?\x00<\x00_\x00>\x00a\x00)\x00)\x00)\x00\\\x00k\x00<\x00_\x00>',
      '\x00z\x00a\x00a',
      0,
      6,
      599,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x00>\x00\\\x00d\x00)\x00|\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x002\x00>\x00\\\x00w\x00)\x00)\x00(\x00\\\x00k\x00<\x00n\x00a\x00m\x00e\x001\x00>\x00|\x00\\\x00k\x00<\x00n\x00a\x00m\x00e\x002\x00>\x00)',
      '\x00f\x00f',
      0,
      4,
      600,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00?\x00<\x00x\x00>\x00)\x00|\x00(\x00?\x00<\x00x\x00>\x00e\x00f\x00g\x00)\x00)\x00\\\x00k\x00<\x00x\x00>',
      '',
      0,
      0,
      601,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00?\x00<\x00x\x00>\x00a\x00b\x00c\x00)\x00|\x00(\x00?\x00<\x00x\x00>\x00e\x00f\x00g\x00)\x00)\x00\\\x00k\x00<\x00x\x00>',
      '\x00a\x00b\x00c\x00e\x00f\x00g\x00e\x00f\x00g',
      6,
      18,
      602,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:\x00(\x00?\x00<\x00x\x00>\x00a\x00b\x00c\x00)\x00|\x00(\x00?\x00<\x00x\x00>\x00e\x00f\x00g\x00)\x00)\x00\\\x00k\x00<\x00x\x00>',
      '\x00a\x00b\x00c\x00e\x00f\x00g',
      603,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00)\x00\\\x00k\x00<\x00n\x001\x00>\x00\$',
      '\x00a\x00-\x00p\x00y\x00u\x00m\x00p\x00y\x00u\x00m',
      4,
      20,
      604,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00?\x00:\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00|\x00(\x00?\x00<\x00n\x001\x00>\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00.\x00)\x00)\x00\\\x00k\x00<\x00n\x001\x00>\x00\$',
      '\x00x\x00x\x00x\x00x\x00a\x00b\x00c\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00n\x00a\x00b\x00c\x00d\x00e\x00f\x00g\x00h\x00i\x00j\x00k\x00l\x00m\x00n',
      8,
      36,
      14,
      605,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x002\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x003\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x004\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x005\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x006\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x007\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x008\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x009\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x000\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x001\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x002\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x003\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x004\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x005\x00>\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x006\x00>\x00a\x00a\x00a\x00)\x00(\x00?\x00<\x00n\x00a\x00m\x00e\x001\x007\x00>\x00)\x00\$',
      '\x00a\x00a\x00a',
      0,
      6,
      16,
      606,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00f\x00o\x00o\x00>\x00a\x00|\x00\\\x00(\x00\\\x00g\x00<\x00f\x00o\x00o\x00>\x00\\\x00)\x00)',
      '\x00a',
      0,
      2,
      607,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00f\x00o\x00o\x00>\x00a\x00|\x00\\\x00(\x00\\\x00g\x00<\x00f\x00o\x00o\x00>\x00\\\x00)\x00)',
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00a\x00)\x00)\x00)\x00)\x00)\x00)',
      0,
      26,
      608,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00?\x00<\x00f\x00o\x00o\x00>\x00a\x00|\x00\\\x00(\x00\\\x00g\x00<\x00f\x00o\x00o\x00>\x00\\\x00)\x00)',
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00a\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)',
      0,
      34,
      1,
      609,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00g\x00<\x00b\x00a\x00r\x00>\x00|\x00\\\x00z\x00E\x00N\x00D\x00(\x00?\x00<\x00b\x00a\x00r\x00>\x00.\x00*\x00a\x00b\x00c\x00\$\x00)',
      '\x00a\x00b\x00c\x00x\x00x\x00x\x00a\x00b\x00c',
      0,
      18,
      610,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00g\x00<\x001\x00>\x00|\x00\\\x00z\x00E\x00N\x00D\x00(\x00.\x00a\x00.\x00)',
      '\x00b\x00a\x00c',
      0,
      6,
      611,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00\\\x00g\x00<\x00_\x00A\x00>\x00\\\x00g\x00<\x00_\x00A\x00>\x00|\x00\\\x00z\x00E\x00N\x00D\x00(\x00.\x00a\x00.\x00)\x00(\x00?\x00<\x00_\x00A\x00>\x00.\x00b\x00.\x00)',
      '\x00x\x00b\x00x\x00y\x00b\x00y',
      6,
      12,
      1,
      612,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00A\x00(\x00?\x00:\x00\\\x00g\x00<\x00p\x00o\x00n\x00>\x00|\x00\\\x00g\x00<\x00p\x00a\x00n\x00>\x00|\x00\\\x00z\x00E\x00N\x00D\x00 \x00 \x00(\x00?\x00<\x00p\x00a\x00n\x00>\x00a\x00|\x00c\x00\\\x00g\x00<\x00p\x00o\x00n\x00>\x00c\x00)\x00(\x00?\x00<\x00p\x00o\x00n\x00>\x00b\x00|\x00d\x00\\\x00g\x00<\x00p\x00a\x00n\x00>\x00d\x00)\x00)\x00\$',
      '\x00c\x00d\x00c\x00b\x00c\x00d\x00c',
      0,
      14,
      613,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00A\x00(\x00?\x00<\x00n\x00>\x00|\x00a\x00\\\x00g\x00<\x00m\x00>\x00)\x00\\\x00z\x00|\x00\\\x00z\x00E\x00N\x00D\x00 \x00(\x00?\x00<\x00m\x00>\x00\\\x00g\x00<\x00n\x00>\x00)',
      '\x00a\x00a\x00a\x00a',
      0,
      8,
      614,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00>\x00(\x00a\x00|\x00b\x00\\\x00g\x00<\x00n\x00>\x00c\x00)\x00{\x003\x00,\x005\x00}\x00)',
      '\x00b\x00a\x00a\x00a\x00a\x00c\x00a',
      2,
      10,
      615,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00n\x00>\x00(\x00a\x00|\x00b\x00\\\x00g\x00<\x00n\x00>\x00c\x00)\x00{\x003\x00,\x005\x00}\x00)',
      '\x00b\x00a\x00a\x00a\x00a\x00c\x00a\x00a\x00a\x00a\x00a',
      0,
      20,
      616,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<\x00p\x00a\x00r\x00e\x00>\x00\\\x00(\x00(\x00[\x00^\x00\\\x00(\x00\\\x00)\x00]\x00+\x00+\x00|\x00\\\x00g\x00<\x00p\x00a\x00r\x00e\x00>\x00)\x00*\x00+\x00\\\x00)\x00)',
      '\x00(\x00(\x00a\x00)\x00)',
      0,
      10,
      617,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00)\x00*\x00\\\x001', '', 0, 0, 618);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00)\x00|\x00(\x00)\x00)\x00*\x00\\\x001\x00\\\x002',
      '',
      0,
      0,
      619,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00?\x00:\x00\\\x001\x00a\x00|\x00(\x00)\x00)\x00*',
      '\x00a',
      0,
      0,
      1,
      620,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00x\x00(\x00(\x00.\x00)\x00*\x00)\x00*\x00x',
      '\x000\x00x\x001\x00x\x002\x00x\x003',
      2,
      12,
      621,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00x\x00(\x00(\x00.\x00)\x00*\x00)\x00*\x00x\x00(\x00?\x00i\x00:\x00\\\x001\x00)\x00\\\x00Z',
      '\x000\x00x\x001\x00x\x002\x00x\x001\x00X\x002',
      2,
      18,
      622,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00)\x00*\x00\\\x002\x00\\\x005',
      '',
      0,
      0,
      623,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00|\x00(\x00x\x00)\x00|\x00(\x00)\x00|\x00(\x00)\x00)\x00*\x00\\\x002\x00b\x00\\\x005',
      '\x00b',
      0,
      2,
      624,
    );
    CSuite(enc: utf16BeEncoding).x2('\x8f\xfa', '\x8f\xfa', 0, 2, 625);
    CSuite(enc: utf16BeEncoding).x2('', '0B', 0, 0, 626);
    CSuite(enc: utf16BeEncoding).x2('0B', '0B', 0, 2, 627);
    CSuite(enc: utf16BeEncoding).n('0D', '0B', 628);
    CSuite(enc: utf16BeEncoding).x2('0F0F', '0F0F', 0, 4, 629);
    CSuite(enc: utf16BeEncoding).x2('0B0D0F', '0B0D0F', 0, 6, 630);
    CSuite(enc: utf16BeEncoding).x2(
      '0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S',
      '0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S0S',
      0,
      70,
      631,
    );
    CSuite(enc: utf16BeEncoding).x2('0B', '0D0B', 2, 4, 632);
    CSuite(enc: utf16BeEncoding).x2('0D0F', '0B0D0F', 2, 6, 633);
    CSuite(enc: utf16BeEncoding).x2('e\x87', 'e\x87', 0, 2, 634);
    CSuite(enc: utf16BeEncoding).x2('\x00.', '0B', 0, 2, 635);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00.', '0K0M', 0, 4, 636);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00w', '0J', 0, 2, 637);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00W', '0B', 638);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00W\x00]', '0F\x00\$', 2, 4, 639);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00S', '0]', 0, 2, 640);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00S', 'o"', 0, 2, 641);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00b', 'l\x17\x00 ', 0, 0, 642);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00b', '\x00 0{', 2, 2, 643);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '0[0]\x00 ', 2, 2, 644);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '0F\x00 ', 4, 4, 645);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '\x00 0D', 0, 0, 646);
    CSuite(enc: utf16BeEncoding).x2('\x00[0_0a\x00]', '0a', 0, 2, 647);
    CSuite(enc: utf16BeEncoding).n('\x00[0j0k\x00]', '0l', 648);
    CSuite(enc: utf16BeEncoding).x2('\x00[0F\x00-0J\x00]', '0H', 0, 2, 649);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00^0Q\x00]', '0Q', 650);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00\\\x00w\x00]', '0m', 0, 2, 651);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00d\x00]', '0u', 652);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00\\\x00D\x00]', '0o', 0, 2, 653);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00\\\x00s\x00]', '0O', 654);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00\\\x00S\x00]', '0x', 0, 2, 655);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00w\x00\\\x00d\x00]', '0\x88', 0, 2, 656);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00\\\x00w\x00\\\x00d\x00]', '\x00 \x00 \x00 0\x88', 6, 8, 657);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00w\x9b<\x8e\xca', '\x00 \x9b<\x8e\xca', 658);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00\\\x00W\x8e\xca', '\x9b<\x00 \x8e\xca', 0, 6, 659);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00.0D\x00.0F', '0B0B0D0D0F', 0, 10, 660);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00\\\x00w0F\x00\\\x00W\x00.\x00.0^',
      '0H0F0F\x00 0F0^0^',
      0,
      14,
      661,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00s\x00\\\x00w0S0S0S', '\x00 0S0S0S0S', 0, 10, 662);
    CSuite(enc: utf16BeEncoding).x2('0B0B\x00.0Q', '0B0B0Q0Q', 0, 8, 663);
    CSuite(enc: utf16BeEncoding).n('\x00.0D', '0D0H', 664);
    CSuite(enc: utf16BeEncoding).x2('\x00.0J', '0J0J', 0, 4, 665);
    CSuite(enc: utf16BeEncoding).x2('\x00^0B', '0B', 0, 2, 666);
    CSuite(enc: utf16BeEncoding).x2('\x00^0\x80\x00\$', '0\x80', 0, 2, 667);
    CSuite(enc: utf16BeEncoding).x2('\x00^\x00\\\x00w\x00\$', '0k', 0, 2, 668);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00w0K0M0O0Q0S\x00\$', '\x00z0K0M0O0Q0S', 0, 12, 669);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00\\\x00w\x00.\x00.\x00.0F0H0J\x00\$',
      '\x00z0B0D0F0F0H0J',
      0,
      14,
      670,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00w\x00\\\x00w\x00\\\x00s\x00\\\x00W0J0J0J\x00\\\x00d',
      '\x00a0J\x00 \x00 0J0J0J\x004',
      0,
      16,
      671,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00A0_0a0d', '0_0a0d', 0, 6, 672);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0\x800\x810\x82\x00\\\x00Z', '0\x800\x810\x82', 0, 6, 673);
    CSuite(enc: utf16BeEncoding).x2('0K0M0O\x00\\\x00z', '0K0M0O', 0, 6, 674);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0K0M0O\x00\\\x00Z', '0K0M0O\x00\x0a', 0, 6, 675);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00G0}0t', '0}0t', 0, 4, 676);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00G0H', '0F0H0J', 677);
    CSuite(enc: utf16BeEncoding).n('0h0f\x00\\\x00G', '0h0f', 678);
    CSuite(enc: utf16BeEncoding).n('0~0\x7f\x00\\\x00A', '0~0\x7f', 679);
    CSuite(enc: utf16BeEncoding).n('0~\x00\\\x00A0\x7f', '0~0\x7f', 680);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00=0[\x00)0[', '0[', 0, 2, 681);
    CSuite(enc: utf16BeEncoding).n('\x00(\x00?\x00=0F\x00)\x00.', '0D', 682);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00!0F\x00)0K', '0K', 0, 2, 683);
    CSuite(enc: utf16BeEncoding).n('\x00(\x00?\x00!0h\x00)0B', '0h', 684);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:0B\x00)', '0B', 0, 2, 685);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:0v0y\x00)', '0v0y', 0, 4, 686);
    CSuite(enc: utf16BeEncoding).n('\x00(\x00?\x00i\x00:0D\x00)', '0F', 687);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00m\x00:0\x88\x00.\x00)', '0\x88\x00\x0a', 0, 4, 688);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00m\x00:\x00.0\x81\x00)', '0~\x00\x0a0\x81', 2, 6, 689);
    CSuite(enc: utf16BeEncoding).x2('0B\x00?', '', 0, 0, 690);
    CSuite(enc: utf16BeEncoding).x2('Y\x09\x00?', 'S\x16', 0, 0, 691);
    CSuite(enc: utf16BeEncoding).x2('Y\x09\x00?', 'Y\x09', 0, 2, 692);
    CSuite(enc: utf16BeEncoding).x2('\x91\xcf\x00*', '', 0, 0, 693);
    CSuite(enc: utf16BeEncoding).x2('\x91\xcf\x00*', '\x91\xcf', 0, 2, 694);
    CSuite(enc: utf16BeEncoding).x2('[P\x00*', '[P[P[P', 0, 6, 695);
    CSuite(enc: utf16BeEncoding).x2(
      '\x99\xac\x00*',
      '\x9e\x7f\x99\xac\x99\xac\x99\xac\x99\xac',
      0,
      0,
      696,
    );
    CSuite(enc: utf16BeEncoding).n('\\q\x00+', '', 697);
    CSuite(enc: utf16BeEncoding).x2('l\xb3\x00+', 'l\xb3', 0, 2, 698);
    CSuite(enc: utf16BeEncoding).x2('fB\x00+', 'fBfBfBfB', 0, 8, 699);
    CSuite(enc: utf16BeEncoding).x2('0H\x00+', '0H0H0F0F0F', 0, 4, 700);
    CSuite(enc: utf16BeEncoding).x2('0F\x00+', '0J0F0F0F0F', 2, 10, 701);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00?', '0_', 0, 2, 702);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00*', '0q0t0w0z', 0, 8, 703);
    CSuite(enc: utf16BeEncoding).x2('\x00.\x00+', '0\x8d', 0, 2, 704);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00+', '0D0F0H0K\x00\x0a', 0, 8, 705);
    CSuite(enc: utf16BeEncoding).x2('0B\x00|0D', '0B', 0, 2, 706);
    CSuite(enc: utf16BeEncoding).x2('0B\x00|0D', '0D', 0, 2, 707);
    CSuite(enc: utf16BeEncoding).x2('0B0D\x00|0D0F', '0B0D', 0, 4, 708);
    CSuite(enc: utf16BeEncoding).x2('0B0D\x00|0D0F', '0D0F', 0, 4, 709);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0\x92\x00(\x00?\x00:0K0M\x00|0M0O\x00)', '0\x920K0M', 0, 6, 710);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0\x92\x00(\x00?\x00:0K0M\x00|0M0O\x00)0Q', '0\x920M0O0Q', 0, 8, 711);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B0D\x00|\x00(\x00?\x00:0B0F\x00|0B0\x92\x00)', '0B0\x92', 0, 4, 712);
    CSuite(enc: utf16BeEncoding).x2('0B\x00|0D\x00|0F', '0H0F', 2, 4, 713);
    CSuite(enc: utf16BeEncoding).x2(
      '0B\x00|0D\x00|0F0H\x00|0J0K0M\x00|0O\x00|0Q0S0U\x00|0W0Y0[\x00|0]\x00|0_0a\x00|0d0f0h0j0k\x00|0l0m',
      '0W0Y0[',
      0,
      6,
      714,
    );
    CSuite(enc: utf16BeEncoding).n(
      '0B\x00|0D\x00|0F0H\x00|0J0K0M\x00|0O\x00|0Q0S0U\x00|0W0Y0[\x00|0]\x00|0_0a\x00|0d0f0h0j0k\x00|0l0m',
      '0Y0[',
      715,
    );
    CSuite(enc: utf16BeEncoding).x2('0B\x00|\x00^0\x8f', '0v0B', 2, 4, 716);
    CSuite(enc: utf16BeEncoding).x2('0B\x00|\x00^0\x92', '0\x920B', 0, 2, 717);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x00\\\x00G\x8e\xca', '0Q\x8e\xca\x9b<', 4, 6, 718);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x00\\\x00G\x8e\xca', '\x8e\xca\x9b<', 0, 2, 719);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x00\\\x00A\x8e\xca', '\x00b\x8e\xca\x9b<', 4, 6, 720);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x00\\\x00A\x8e\xca', '\x8e\xca', 0, 2, 721);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x8e\xca\x00\\\x00Z', '\x8e\xca\x9b<', 2, 4, 722);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x8e\xca\x00\\\x00Z', '\x8e\xca', 0, 2, 723);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x8e\xca\x00\\\x00Z', '\x8e\xca\x00\x0a', 0, 2, 724);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x8e\xca\x00\\\x00z', '\x8e\xca\x9b<', 2, 4, 725);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x9b<\x00|\x8e\xca\x00\\\x00z', '\x8e\xca', 0, 2, 726);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00\\\x00s', '0J', 0, 2, 727);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00%', '\x00%0J', 0, 2, 728);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00w\x00|\x00[\x00&\x00\$\x00]', '0F\x00&', 0, 2, 729);
    CSuite(enc: utf16BeEncoding).x2('\x00[0D\x00-0Q\x00]', '0F', 0, 2, 730);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[0D\x00-0Q\x00]\x00|\x00[\x00^0K\x00-0S\x00]', '0B', 0, 2, 731);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[0D\x00-0Q\x00]\x00|\x00[\x00^0K\x00-0S\x00]', '0K', 0, 2, 732);
    CSuite(enc: utf16BeEncoding).x2('\x00[\x00^0B\x00]', '\x00\x0a', 0, 2, 733);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00|\x00[0F\x00-0M\x00]\x00)\x00|0D0\x92',
      '0F0\x92',
      0,
      2,
      734,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00|\x00[0F\x00-0M\x00]\x00)\x00|0D0\x92',
      '0D0\x92',
      0,
      4,
      735,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '0B0D0F\x00|\x00(\x00?\x00=0Q0Q\x00)\x00.\x00.0{',
      '0Q0Q0{',
      0,
      6,
      736,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '0B0D0F\x00|\x00(\x00?\x00!0Q0Q\x00)\x00.\x00.0{',
      '0B0D0{',
      0,
      6,
      737,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00=0\x920B\x00)\x00.\x00.0B\x00|\x00(\x00?\x00=0\x920\x92\x00)\x00.\x00.0B',
      '0\x920\x920B',
      0,
      6,
      738,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00<\x00=0B\x00|0D0F\x00)0D', '0D0F0D', 4, 6, 739);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00>0B\x00|0B0D0H\x00)0F', '0B0D0H0F', 740);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00>0B0D0H\x00|0B\x00)0F', '0B0D0H0F', 0, 8, 741);
    CSuite(enc: utf16BeEncoding).x2('0B\x00?\x00|0D', '0B', 0, 2, 742);
    CSuite(enc: utf16BeEncoding).x2('0B\x00?\x00|0D', '0D', 0, 0, 743);
    CSuite(enc: utf16BeEncoding).x2('0B\x00?\x00|0D', '', 0, 0, 744);
    CSuite(enc: utf16BeEncoding).x2('0B\x00*\x00|0D', '0B0B', 0, 4, 745);
    CSuite(enc: utf16BeEncoding).x2('0B\x00*\x00|0D\x00*', '0D0B', 0, 0, 746);
    CSuite(enc: utf16BeEncoding).x2('0B\x00*\x00|0D\x00*', '0B0D', 0, 2, 747);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00a0B\x00]\x00*\x00|0D\x00*', '\x00a0B0D0D0D', 0, 4, 748);
    CSuite(enc: utf16BeEncoding).x2('0B\x00+\x00|0D\x00*', '', 0, 0, 749);
    CSuite(enc: utf16BeEncoding).x2('0B\x00+\x00|0D\x00*', '0D0D0D', 0, 6, 750);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00+\x00|0D\x00*', '0B0D0D0D', 0, 2, 751);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00+\x00|0D\x00*', '\x00a0B0D0D0D', 0, 0, 752);
    CSuite(enc: utf16BeEncoding).n('0B\x00+\x00|0D\x00+', '', 753);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D\x00)\x00?', '0D', 0, 2, 754);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D\x00)\x00*', '0D0B', 0, 4, 755);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D\x00)\x00+', '0D0B0D', 0, 6, 756);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B0D\x00|0F0B\x00)\x00+', '0F0B0B0D0F0H', 0, 8, 757);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B0D\x00|0F0H\x00)\x00+', '0F0B0B0D0F0H', 4, 12, 758);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B0D\x00|0F0B\x00)\x00+', '0B0B0D0F0B', 2, 10, 759);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B0D\x00|0F0B\x00)\x00+', '0B0D0\x920F0B', 0, 4, 760);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(0B0D\x00|0F0B\x00)\x00+',
      '\x00\$\x00\$\x00z\x00z\x00z\x00z0B0D0\x920F0B',
      12,
      16,
      761,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D0B0D\x00)\x00+', '0B0D0B0D0B', 0, 10, 762);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D0B0D\x00)\x00+', '0D0B', 2, 4, 763);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00|0D0B0D\x00)\x00+', '0D0B0B0B0D0B', 2, 8, 764);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00|0D\x00)\x00(\x00?\x00:0B\x00|0D\x00)',
      '0B0D',
      0,
      4,
      765,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00*\x00|0D\x00*\x00)\x00(\x00?\x00:0B\x00*\x00|0D\x00*\x00)',
      '0B0B0B0D0D0D',
      0,
      6,
      766,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00*\x00|0D\x00*\x00)\x00(\x00?\x00:0B\x00+\x00|0D\x00+\x00)',
      '0B0B0B0D0D0D',
      0,
      12,
      767,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00+\x00|0D\x00+\x00)\x00{\x002\x00}',
      '0B0B0B0D0D0D',
      0,
      12,
      768,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00+\x00|0D\x00+\x00)\x00{\x001\x00,\x002\x00}',
      '0B0B0B0D0D0D',
      0,
      12,
      769,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0B\x00+\x00|\x00\\\x00A0D\x00*\x00)0F0F',
      '0F0F',
      0,
      4,
      770,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:0B\x00+\x00|\x00\\\x00A0D\x00*\x00)0F0F',
      '0B0D0F0F',
      771,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00^0B\x00+\x00|0D\x00+\x00)\x00*0F',
      '0B0B0D0D0D0B0D0F',
      12,
      16,
      772,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x00^0B\x00+\x00|0D\x00+\x00)\x00*0F',
      '0B0B0D0D0D0D0F',
      0,
      14,
      773,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0F\x00{\x000\x00,\x00}', '0F0F0F0F', 0, 8, 774);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00|\x00(\x00?\x00i\x00)\x00c', '\x00C', 0, 2, 775);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00)\x00c\x00|0B', '\x00C', 0, 2, 776);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00i\x00:0B\x00)\x00|\x00a', '\x00a', 0, 2, 777);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00?\x00i\x00:0B\x00)\x00|\x00a', '\x00A', 778);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[0B0D0F\x00]\x00?', '0B0D0F', 0, 2, 779);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[0B0D0F\x00]\x00*', '0B0D0F', 0, 6, 780);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00^0B0D0F\x00]\x00*', '0B0D0F', 0, 0, 781);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00^0B0D0F\x00]\x00+', '0B0D0F', 782);
    CSuite(enc: utf16BeEncoding).x2('0B\x00?\x00?', '0B0B0B', 0, 0, 783);
    CSuite(enc: utf16BeEncoding).x2('0D0B\x00?\x00?0D', '0D0B0D', 0, 6, 784);
    CSuite(enc: utf16BeEncoding).x2('0B\x00*\x00?', '0B0B0B', 0, 0, 785);
    CSuite(enc: utf16BeEncoding).x2('0D0B\x00*\x00?', '0D0B0B', 0, 2, 786);
    CSuite(enc: utf16BeEncoding).x2('0D0B\x00*\x00?0D', '0D0B0B0D', 0, 8, 787);
    CSuite(enc: utf16BeEncoding).x2('0B\x00+\x00?', '0B0B0B', 0, 2, 788);
    CSuite(enc: utf16BeEncoding).x2('0D0B\x00+\x00?', '0D0B0B', 0, 4, 789);
    CSuite(enc: utf16BeEncoding).x2('0D0B\x00+\x00?0D', '0D0B0B0D', 0, 8, 790);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:Y)\x00?\x00)\x00?\x00?', 'Y)', 0, 0, 791);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:Y)\x00?\x00?\x00)\x00?', 'Y)', 0, 0, 792);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:Y"\x00?\x00)\x00+\x00?', 'Y"Y"Y"', 0, 2, 793);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x98\xa8\x00+\x00)\x00?\x00?',
      '\x98\xa8\x98\xa8\x98\xa8',
      0,
      0,
      794,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x96\xea\x00+\x00)\x00?\x00?\x97\x1c',
      '\x96\xea\x96\xea\x96\xea\x97\x1c',
      0,
      8,
      795,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00?\x00:0B0D\x00)\x00?\x00{\x002\x00}', '', 0, 0, 796);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00?\x00{\x002\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<',
      0,
      8,
      797,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00*\x00{\x000\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<',
      0,
      0,
      798,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x003\x00,\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca',
      0,
      16,
      799,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x003\x00,\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca',
      800,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x002\x00,\x004\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca',
      0,
      12,
      801,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x002\x00,\x004\x00}',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca',
      0,
      16,
      802,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x002\x00,\x004\x00}\x00?',
      '\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca\x9b<\x8e\xca',
      0,
      8,
      803,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:\x9b<\x8e\xca\x00)\x00{\x00,\x00}',
      '\x9b<\x8e\xca\x00{\x00,\x00}',
      0,
      10,
      804,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00:0K0M0O\x00)\x00+\x00?\x00{\x002\x00}',
      '0K0M0O0K0M0O0K0M0O',
      0,
      12,
      805,
    );
    CSuite(enc: utf16BeEncoding).x3('\x00(pk\x00)', 'pk', 0, 2, 1, 806);
    CSuite(enc: utf16BeEncoding).x3('\x00(pkl4\x00)', 'pkl4', 0, 4, 1, 807);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00(fB\x95\x93\x00)\x00)', 'fB\x95\x93', 0, 4, 808);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(\x98\xa8l4\x00)\x00)', '\x98\xa8l4', 0, 4, 1, 809);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(f(e\xe5\x00)\x00)', 'f(e\xe5', 0, 4, 2, 810);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x00(\x91\xcf[P\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)\x00)',
      '\x91\xcf[P',
      0,
      4,
      20,
      811,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B0D\x00)\x00(0F0H\x00)', '0B0D0F0H', 0, 4, 1, 812);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B0D\x00)\x00(0F0H\x00)', '0B0D0F0H', 4, 8, 2, 813);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00)\x00(0B\x00)0D0F\x00(0H0J0K\x00)0M0O0Q0S',
      '0B0D0F0H0J0K0M0O0Q0S',
      6,
      12,
      3,
      814,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00)\x00(0B\x00)0D0F\x00(0H0J0K\x00)0M0O0Q0S\x00)',
      '0B0D0F0H0J0K0M0O0Q0S',
      6,
      12,
      4,
      815,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00.\x00*\x00(0\xd50\xa9\x00)0\xf30\xfb0\xde\x00(0\xf3\x00(\x00)0\xb70\xe50\xbf\x00)0\xa40\xf3',
      '0\xd50\xa90\xf30\xfb0\xde0\xf30\xb70\xe50\xbf0\xa40\xf3',
      10,
      18,
      2,
      816,
    );
    CSuite(enc: utf16BeEncoding).x2('\x00(\x00^0B\x00)', '0B', 0, 2, 817);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B\x00)\x00|\x00(0B\x00)', '0D0B', 2, 4, 1, 818);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00^0B\x00)\x00|\x00(0B\x00)', '0D0B', 2, 4, 2, 819);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B\x00?\x00)', '0B0B0B', 0, 2, 1, 820);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0~\x00*\x00)', '0~0~0~', 0, 6, 1, 821);
    CSuite(enc: utf16BeEncoding).x3('\x00(0h\x00*\x00)', '', 0, 0, 1, 822);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(0\x8b\x00+\x00)',
      '0\x8b0\x8b0\x8b0\x8b0\x8b0\x8b0\x8b',
      0,
      14,
      1,
      823,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0u\x00+\x00|0x\x00*\x00)', '0u0u0u0x0x', 0, 6, 1, 824);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B\x00+\x00|0D\x00?\x00)', '0D0D0D0B0B', 0, 2, 1, 825);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B0D0F\x00)\x00?', '0B0D0F', 0, 6, 1, 826);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B0D0F\x00)\x00*', '0B0D0F', 0, 6, 1, 827);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0B0D0F\x00)\x00+', '0B0D0F', 0, 6, 1, 828);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(0U0W0Y\x00|0B0D0F\x00)\x00+', '0B0D0F', 0, 6, 1, 829);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00[0j0k0l\x00]\x00[0K0M0O\x00]\x00|0K0M0O\x00)\x00+',
      '0K0M0O',
      0,
      6,
      1,
      830,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(\x00?\x00i\x00:0B0D0F\x00)\x00)', '0B0D0F', 0, 6, 1, 831);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00?\x00m\x00:0B\x00.0F\x00)\x00)',
      '0B\x00\x0a0F',
      0,
      6,
      1,
      832,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00(\x00?\x00=0B0\x93\x00)0B\x00)', '0B0\x930D', 0, 2, 1, 833);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('0B0D0F\x00|\x00(\x00.0B0D0H\x00)', '0\x930B0D0H', 0, 8, 1, 834);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('0B\x00*\x00(\x00.\x00)', '0B0B0B0B0\x93', 8, 10, 1, 835);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('0B\x00*\x00?\x00(\x00.\x00)', '0B0B0B0B0\x93', 0, 2, 1, 836);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('0B\x00*\x00?\x00(0\x93\x00)', '0B0B0B0B0\x93', 8, 10, 1, 837);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00[0D0F0H\x00]0B\x00*\x00(\x00.\x00)',
      '0H0B0B0B0B0\x93',
      10,
      12,
      1,
      838,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00\\\x00A0D0D\x00)0F0F', '0D0D0F0F', 0, 4, 1, 839);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00\\\x00A0D0D\x00)0F0F', '0\x930D0D0F0F', 840);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(\x00^0D0D\x00)0F0F', '0D0D0F0F', 0, 4, 1, 841);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00^0D0D\x00)0F0F', '0\x930D0D0F0F', 842);
    CSuite(enc: utf16BeEncoding).x3(
      '0\x8d0\x8d\x00(0\x8b0\x8b\x00\$\x00)',
      '0\x8d0\x8d0\x8b0\x8b',
      4,
      8,
      1,
      843,
    );
    CSuite(enc: utf16BeEncoding).n(
      '0\x8d0\x8d\x00(0\x8b0\x8b\x00\$\x00)',
      '0\x8d0\x8d0\x8b0\x8b0\x8b',
      844,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(q!\x00)\x00\\\x001', 'q!q!', 0, 4, 845);
    CSuite(enc: utf16BeEncoding).n('\x00(q!\x00)\x00\\\x001', 'q!kf', 846);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(zz\x00?\x00)\x00\\\x001', 'zzzz', 0, 4, 847);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(zz\x00?\x00?\x00)\x00\\\x001', 'zzzz', 0, 0, 848);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(zz\x00*\x00)\x00\\\x001', 'zzzzzzzzzz', 0, 8, 849);
    CSuite(
      enc: utf16BeEncoding,
    ).x3('\x00(zz\x00*\x00)\x00\\\x001', 'zzzzzzzzzz', 0, 4, 1, 850);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00(0D\x00*\x00)\x00\\\x001', '0B0D0D0D0D', 0, 10, 851);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('0B\x00(0D\x00*\x00)\x00\\\x001', '0B0D', 0, 2, 852);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(0B\x00*\x00)\x00(0D\x00*\x00)\x00\\\x001\x00\\\x002',
      '0B0B0B0D0D0B0B0B0D0D',
      0,
      20,
      853,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(0B\x00*\x00)\x00(0D\x00*\x00)\x00\\\x002',
      '0B0B0B0D0D0D0D',
      0,
      14,
      854,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(0B\x00*\x00)\x00(0D\x00*\x00)\x00\\\x002',
      '0B0B0B0D0D0D0D',
      6,
      10,
      2,
      855,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(0}\x00*\x00)0z\x00)\x00)\x00)\x00)\x00)\x00)0t\x00\\\x007',
      '0}0}0}0z0t0}0}0}',
      0,
      16,
      856,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00(\x00(\x00(\x00(\x00(\x00(0}\x00*\x00)0z\x00)\x00)\x00)\x00)\x00)\x00)0t\x00\\\x007',
      '0}0}0}0z0t0}0}0}',
      0,
      6,
      7,
      857,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(0o\x00)\x00(0r\x00)\x00(0u\x00)\x00\\\x002\x00\\\x001\x00\\\x003',
      '0o0r0u0r0o0u',
      0,
      12,
      858,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00[0M\x00-0Q\x00]\x00)\x00\\\x001', '0O0O', 0, 4, 859);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00\\\x00w\x00\\\x00d\x00\\\x00s\x00)\x00\\\x001',
      '0B\x005\x00 0B\x005\x00 ',
      0,
      12,
      860,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00(\x00\\\x00w\x00\\\x00d\x00\\\x00s\x00)\x00\\\x001',
      '0B\x005\x00 0B\x005',
      861,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x8a\xb0\xff\x1f\x00|\x00[0B\x00-0F\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '\x8a\xb0\xff\x1f\x8a\xb0\xff\x1f',
      0,
      8,
      862,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00.\x00.\x00(\x8a\xb0\xff\x1f\x00|\x00[0B\x00-0F\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '0B\x00a0B\x8a\xb0\xff\x1f\x8a\xb0\xff\x1f',
      0,
      14,
      863,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x8a\xb0\xff\x1f\x00|\x00[0B\x00-0F\x00]\x00{\x003\x00}\x00)\x00\\\x001',
      '0F0D0F0F0D0F',
      0,
      12,
      864,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(\x00^0S\x00)\x00\\\x001', '0S0S', 0, 4, 865);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(\x00^0\x80\x00)\x00\\\x001', '0\x810\x800\x80', 866);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(0B\x00\$\x00)\x00\\\x001', '0B0B', 867);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00(0B0D\x00\\\x00Z\x00)\x00\\\x001', '0B0D', 868);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00(0B\x00*\x00\\\x00Z\x00)\x00\\\x001', '0B', 2, 2, 869);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00(0B\x00*\x00\\\x00Z\x00)\x00\\\x001', '0D0B', 2, 4, 870);
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00.\x00(0\x840D0\x86\x00)\x00\\\x002\x00)',
      '\x00z0\x840D0\x860\x840D0\x86',
      0,
      14,
      1,
      871,
    );
    CSuite(enc: utf16BeEncoding).x3(
      '\x00(\x00.\x00(\x00.\x00.\x00\\\x00d\x00.\x00)\x00\\\x002\x00)',
      '0B\x001\x002\x003\x004\x001\x002\x003\x004',
      0,
      18,
      1,
      872,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00(\x00?\x00i\x00:0B\x00v0Z\x00)\x00)\x00\\\x001',
      '0B\x00v0Z0B\x00v0Z',
      0,
      12,
      873,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00(\x00?\x00<a\x1a0K\x00>Y\x09\x00|\x00\\\x00(\x00\\\x00g\x00<a\x1a0K\x00>\x00\\\x00)\x00)',
      '\x00(\x00(\x00(\x00(\x00(\x00(Y\x09\x00)\x00)\x00)\x00)\x00)\x00)',
      0,
      26,
      874,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00A\x00(\x00?\x00:\x00\\\x00g\x00<\x96?\x00_\x001\x00>\x00|\x00\\\x00g\x00<N\x91\x00_\x002\x00>\x00|\x00\\\x00z}BN\x86\x00 \x00 \x00(\x00?\x00<\x96?\x00_\x001\x00>\x89\xb3\x00|\x81\xea\x00\\\x00g\x00<N\x91\x00_\x002\x00>\x81\xea\x00)\x00(\x00?\x00<N\x91\x00_\x002\x00>W(\x00|\x83\xe9\x85\xa9\x00\\\x00g\x00<\x96?\x00_\x001\x00>\x83\xe9\x85\xa9\x00)\x00)\x00\$',
      '\x83\xe9\x85\xa9\x81\xea\x83\xe9\x85\xa9\x81\xeaW(\x81\xea\x83\xe9\x85\xa9\x81\xea\x83\xe9\x85\xa9',
      0,
      26,
      875,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00[0r0u\x00]\x00]', '0u', 0, 2, 876);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00[0D0J0F\x00]0K\x00]', '0K', 0, 2, 877);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00[\x00^0B\x00]\x00]', '0B', 878);
    CSuite(enc: utf16BeEncoding).n('\x00[\x00^\x00[0B\x00]\x00]', '0B', 879);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00^\x00[\x00^0B\x00]\x00]', '0B', 0, 2, 880);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[\x00[0K0M0O\x00]\x00&\x00&0M0O\x00]', '0O', 0, 2, 881);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[0K0M0O\x00]\x00&\x00&0M0O\x00]', '0K', 882);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00[\x00[0K0M0O\x00]\x00&\x00&0M0O\x00]', '0Q', 883);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[0B\x00-0\x93\x00&\x00&0D\x00-0\x92\x00&\x00&0F\x00-0\x91\x00]',
      '0\x91',
      0,
      2,
      884,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00^0B\x00-0\x93\x00&\x00&0D\x00-0\x92\x00&\x00&0F\x00-0\x91\x00]',
      '0\x91',
      885,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00^0B\x00&\x00&0B\x00]\x00&\x00&0B\x00-0\x93\x00]',
      '0D',
      0,
      2,
      886,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00[\x00^0B\x00&\x00&0B\x00]\x00&\x00&0B\x00-0\x93\x00]',
      '0B',
      887,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00^0B\x00-0\x93\x00&\x00&0D0F0H0J\x00]\x00&\x00&\x00[\x00^0F\x00-0K\x00]\x00]',
      '0M',
      0,
      2,
      888,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00[\x00^0B\x00-0\x93\x00&\x00&0D0F0H0J\x00]\x00&\x00&\x00[\x00^0F\x00-0K\x00]\x00]',
      '0D',
      889,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^0B0D0F\x00]\x00&\x00&\x00[\x00^0F0H0J\x00]\x00]',
      '0F',
      0,
      2,
      890,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^0B0D0F\x00]\x00&\x00&\x00[\x00^0F0H0J\x00]\x00]',
      '0H',
      0,
      2,
      891,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00^\x00[\x00^0B0D0F\x00]\x00&\x00&\x00[\x00^0F0H0J\x00]\x00]',
      '0K',
      892,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00[0B\x00-\x00&\x00&\x00-0B\x00]', '\x00-', 0, 2, 893);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^\x00a\x00-\x00z0B0D0F\x00]\x00&\x00&\x00[\x00^\x00b\x00c\x00d\x00e\x00f\x00g0F0H0J\x00]\x00q\x00-\x00w\x00]',
      '0H',
      0,
      2,
      894,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^\x00a\x00-\x00z0B0D0F\x00]\x00&\x00&\x00[\x00^\x00b\x00c\x00d\x00e\x00f\x00g0F0H0J\x00]\x00g\x00-\x00w\x00]',
      '\x00f',
      0,
      2,
      895,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00^\x00[\x00^\x00a\x00-\x00z0B0D0F\x00]\x00&\x00&\x00[\x00^\x00b\x00c\x00d\x00e\x00f\x00g0F0H0J\x00]\x00g\x00-\x00w\x00]',
      '\x00g',
      0,
      2,
      896,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00^\x00[\x00^\x00a\x00-\x00z0B0D0F\x00]\x00&\x00&\x00[\x00^\x00b\x00c\x00d\x00e\x00f\x00g0F0H0J\x00]\x00g\x00-\x00w\x00]',
      '\x002',
      897,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00a\x00<\x00b\x00>0\xd00\xfc0\xb80\xe70\xf30n0\xc00\xa60\xf30\xed0\xfc0\xc9\x00<\x00\\\x00/\x00b\x00>',
      '\x00a\x00<\x00b\x00>0\xd00\xfc0\xb80\xe70\xf30n0\xc00\xa60\xf30\xed0\xfc0\xc9\x00<\x00/\x00b\x00>',
      0,
      40,
      898,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00.\x00<\x00b\x00>0\xd00\xfc0\xb80\xe70\xf30n0\xc00\xa60\xf30\xed0\xfc0\xc9\x00<\x00\\\x00/\x00b\x00>',
      '\x00a\x00<\x00b\x00>0\xd00\xfc0\xb80\xe70\xf30n0\xc00\xa60\xf30\xed0\xfc0\xc9\x00<\x00/\x00b\x00>',
      0,
      40,
      899,
    );
    CSuite(enc: utf16BeEncoding).x2(
      '\x00^\x00\\\x00p\x00{\x00K\x00a\x00t\x00a\x00k\x00a\x00n\x00a\x00}\x00\$',
      '0\xbf',
      0,
      2,
      900,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00o\x00{\x001\x000\x001\x00}', '\x00A', 0, 2, 901);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00o\x00{\x001\x001\x000\x007\x002\x001\x00}',
      '\x91\xd1',
      0,
      2,
      902,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00\\\x00R', '\x00\x0d\x00\x0a', 0, 4, 903);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', '\x00\x0a', 0, 2, 904);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', '\x00\x0d', 0, 2, 905);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', '\x00\x0b', 0, 2, 906);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00R\x00\x0a', '\x00\x0d\x00\x0a', 907);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', '\x00\x85', 0, 2, 908);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', ' (', 0, 2, 909);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00R', ' )', 0, 2, 910);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00R', ' *', 911);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00w', '\x01\x00', 0, 2, 913);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00W', '\x01\x00', 914);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00d', '\x0bf', 0, 2, 915);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00D', '\x0bf', 916);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00s', ' \x01', 0, 2, 917);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00S', ' \x01', 918);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00b', '\x00 \x01\x00', 2, 2, 919);
    CSuite(enc: utf16BeEncoding).n('\x00\\\x00B', '\x01\x00', 920);
    CSuite(enc: utf16BeEncoding).x2('\x00\\\x00B', '\x00 ', 0, 0, 921);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00[\x00[\x00:\x00g\x00r\x00a\x00p\x00h\x00:\x00]\x00]',
      '\x0d0',
      0,
      2,
      922,
    );
    CSuite(enc: utf16BeEncoding).n(
      '\x00[\x00[\x00:\x00g\x00r\x00a\x00p\x00h\x00:\x00]\x00]',
      '\x0a\x00',
      924,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00.\x00\\\x00y\x00\\\x00O', '\x00\x0d\x00\x0a', 930);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00\\\x00Y\x00\\\x00O', '\x00\x0d\x00\x0a', 0, 4, 931);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00^\x00.\x00\\\x00y\x00.\x00\$', '\x00g\x03\x08', 934);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00\\\x00Y\x00.', '\x00g\x03\x08', 0, 4, 935);
    CSuite(enc: utf16BeEncoding).x2(
      '\x00\\\x00y\x00.\x00\\\x00Y\x00.\x00\\\x00y',
      '\x00g\x03\x08',
      0,
      4,
      936,
    );
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00.\x00\\\x00Y\x00.', '\x0b\xa8\x0b\xbf', 0, 4, 939);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00.\x00\\\x00y\x00.', '\x0b\xa8\x0b\xbf', 940);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00X\x00\\\x00X', '\x00\x0d\x00\x0a', 943);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00X\x00\$', '\x00\x0d\x00\x0a', 0, 4, 944);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00X\x00\\\x00X', '\x00g\x03\x08', 946);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00X\x00\$', '\x00g\x03\x08', 0, 4, 947);
    CSuite(
      enc: utf16BeEncoding,
    ).x2('\x00^\x00\\\x00X\x00\$', '\x0b\xa8\x0b\xbf', 0, 4, 949);
    CSuite(
      enc: utf16BeEncoding,
    ).n('\x00\\\x00X\x00\\\x00X', '\x0b\xa8\x0b\xbf', 950);
  });
}
